### DISCUSSION TITLE
Medusa-operator usage post 1.0.0

### DISCUSSION THREAD

**Discussion by burmanm** [k8ssandra/k8ssandra#273] [Ideas]
These are some of the features I'd like to see us improving post-1.0.0 for taking backups. This includes mostly usability and does not as much touch the actual implementation details (although I do have an idea how to implement these - most of them are quite simple). Some API names probably need thinking, this is more of a "how-to" approach in using Medusa inside Kubernetes. These additional options are not necessarily incompatible with the helm, but they also allow configuring the Medusa without using helm.

## Configure target repository

Allow separate target repositories where to store the data, such as daily backups to long term storage and hourly to faster s3 storage:

```yaml
apiVersion: medusa.cassandra-medusa.io/v1alpha1
kind: CassandraBackupRepository
metadata:
  name: cassandrabackuprepository-sample
spec:
  provider: s3
  bucketName: "daily-backups"
  secret: my-aws-secret
  params:
    storageClass: "glacier"
  retentionPolicy:
    ttl: "720d"
```

```yaml
apiVersion: medusa.cassandra-medusa.io/v1alpha1
kind: CassandraBackupRepository
metadata:
  name: cassandrabackuprepositoryshort-sample
spec:
  provider: s3
  bucketName: "hourly-backups"
  secret: my-aws-secret
  params:
    storageClass: "ia"
  retentionPolicy:
    ttl: "14d"
```

## Automated backups

The use of CronJob's format is not necessary, we could simplify these to parameters that are more easily understood such as "schedule, everyHour".

### Daily backups:

```yaml
apiVersion: medusa.cassandra-medusa.io/v1alpha1
kind: CassandraBackupSchedule
metadata:
  name: cassandrabackupschedule-sample
spec:
  schedule: "0 0 * * *"
  name: "cass-daily"
  cassandraDatacenter: dc1
  targetRepository: cassandrabackuprepository-sample
```

### Hourly backups:

```yaml
apiVersion: medusa.cassandra-medusa.io/v1alpha1
kind: CassandraBackupSchedule
metadata:
  name: cassandrabackupschedule-sample
spec:
  schedule: "0 * * * *"
  name: "cass-hourly" 
  cassandraDatacenter: dc1
  targetRepository: cassandrabackuprepositoryshort-sample
```

## View the backups

Whenever medusa creates a backup, it would also create a new object to the Kubernetes so that they could be viewed. These should have necessary information such as TTL that allows expiring the data from S3 as well as medusa-operator to delete the backup object.

```
➜  storage git:(master) ✗ kubectl get cassandrabackup
NAME                        AGE
cass-daily-202101290000     13h
cass-hourly-202101291300    21m
cass-hourly-202101291200    1h
➜  storage git:(master) ✗
```

## Restore the backup

There's no real need to modify the restore process. Although, one additional option could be to modify the ``CassandraDatacenter`` and add a annotation ``restore.medusa.cassandra-medusa.io; cass-hourly-202101290000`` and the the medusa-operator would do the rest. That would be inplace restoration for the cluster, for more complex scenarios we would still require creating a Restore object.
