### ISSUE TITLE
Deployments with ingress enabled fail with newer version of Traefik charts installed

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra#1008]
## Bug Report

**Describe the bug**
When trying to install the latest v1.3.0 release I did a `helm repo update` locally to grab the latest K8ssandra release.  In doing so, I also ended up with an update to the traefik charts.

Attempting to install K8ssandra to a cluster where Traefik was already installed failed with the following error:

```
% ./bootstrap-cluster-1202.sh 
Bootstrapping initial cluster environment...
kind delete cluster --name k8ssandra
Deleting cluster "k8ssandra" ...
kind create cluster --config kind-config.yaml
Creating cluster "k8ssandra" ...
 ✓ Ensuring node image (kindest/node:v1.20.2) 🖼 
 ✓ Preparing nodes 📦 📦 📦 📦  
 ✓ Writing configuration 📜 
 ✓ Starting control-plane 🕹️ 
 ✓ Installing CNI 🔌 
 ✓ Installing StorageClass 💾 
 ✓ Joining worker nodes 🚜 
Set kubectl context to "kind-k8ssandra"
You can now use your cluster with:

kubectl cluster-info --context kind-k8ssandra

Have a question, bug, or feature request? Let us know! https://kind.sigs.k8s.io/#community 🙂
kubectl config use-context kind-k8ssandra
Switched to context "kind-k8ssandra".
Bootstrapping initial cluster environment...
% helm install -f stage-2.traefik.values.yaml traefik traefik/traefik --version v10.0.0               
NAME: traefik
LAST DEPLOYED: Tue Jul 27 20:18:54 2021
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
% helm install -f shortcut.k8ssandra.values.yaml k8ssandra k8ssandra-stable/k8ssandra --version v1.2.0
W0727 20:19:05.941245   82416 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0727 20:19:05.969745   82416 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0727 20:19:06.159302   82416 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0727 20:19:08.975504   82416 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0727 20:19:08.990271   82416 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0727 20:19:09.035386   82416 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(IngressRouteTCP.spec.routes[0].services[0]): unknown field "kind" in us.containo.traefik.v1alpha1.IngressRouteTCP.spec.routes.services
``` 

I was able to confirm that this problem started with the v10.0.0 release of the traefik chart.  Deploying the same set of configurations with v9.20.1 works as expected.

This wasn't caught by our integration tests because they currently pin the traefik version being used, for example:

```
TestStargateDeploymentScenario 2021-07-27T20:23:31Z logger.go:66: Running command helm with args [install traefik traefik/traefik -n traefik --create-namespace -f /home/runner/work/k8ssandra/k8ssandra/docs/content/en/tasks/connect/ingress/kind-deployment/traefik.values.yaml --version 9.19.2]
```

**To Reproduce**

(Assuming that the traefik and k8ssandra repos are already installed and a cluster is available)

1. `helm repo update`
2. `helm install -f traefik.values.yaml traefik traefik/traefik --version v10.0.0`

Where `traefik.values.yaml` looks like:

```
---
providers:
  kubernetesCRD:
    namespaces:
      - default
      - traefik
  kubernetesIngress:
    namespaces:
      - default
      - traefik

ports:
  traefik:
    expose: true
    nodePort: 32090
  web:
    nodePort: 32080
  websecure:
    nodePort: 32443
  cassandra:
    expose: true
    port: 9042
    nodePort: 32091
  cassandrasecure:
    expose: true
    port: 9142
    nodePort: 32092
  sg-graphql:
    expose: true
    port: 8080
    nodePort: 30080
  sg-auth:
    expose: true
    port: 8081
    nodePort: 30081
  sg-rest:
    expose: true
    port: 8082
    nodePort: 30082

service:
  type: NodePort
```

3. `helm install -f k8ssandra.values.yaml k8ssandra k8ssandra-stable/k8ssandra --version v1.2.0`

Where `k8ssandra.values.yaml` looks like:

```
cassandra:
  clusterName: k8ssandra-cassandra-cluster
  heap:
   size: 500M
   newGenSize: 256M
  datacenters:
  - name: dc1
    size: 1
kube-prometheus-stack:
  prometheus:
    enabled: true
    prometheusSpec:
      externalUrl: http://localhost:9090/prometheus
      routePrefix: /prometheus
    ingress:
      enabled: true
      paths:
        - /prometheus
  grafana:
    enabled: true
    ingress:
      enabled: true
      path: /grafana
    adminUser: admin
    adminPassword: admin123
    grafana.ini:
      server:
        root_url: http://localhost:3000/grafana
        serve_from_sub_path: true
stargate:
  enabled: true
  replicas: 1
  ingress:
    enabled: true
reaper:
  enabled: true
  ingress:
    enabled: true
    host: repair.127.0.0.1.nip.io
medusa:
  enabled: false
  storage: s3
  storage_properties:
    region: us-east-1
  bucketName: "k8ssandra-cluster-test"
  storageSecret: "medusa-bucket-key"
```

**Expected behavior**
K8ssandra should be able to deploy with the latest version of the Traefik charts -- v10.0.0 and higher.

**Environment (please complete the following information):**

* Helm charts version info

Traefik: v10.0.0 (or higher)
K8ssandra: v1.2.0 (or v1.3.0)

* Helm charts user-supplied values
See reproduction steps.

* Kubernetes version information:
v1.20.02

* Kubernetes cluster kind:
Kind

**Additional context**

As a workaround, use v9.20.1 (or older) of the Traefik charts.
