### ISSUE TITLE
Reaper image registry tyop

### ISSUE THREAD

**Issue by bradfordcp** [k8ssandra/k8ssandra#1018]
## Bug Report
**Describe the bug**
The Docker registry parameter in values.yaml is misspelled.

https://github.com/k8ssandra/k8ssandra/blob/v1.3.0/charts/k8ssandra/values.yaml#L481

```yaml
image:
    # -- Image registry for reaper
    reigistry: docker.io
    # -- Image repository for reaper
    repository: thelastpickle/cassandra-reaper
    # -- Tag of the reaper image to pull from
    tag: 2.3.1
    # -- Pull policy for the reaper container
    pullPolicy: IfNotPresent
```

**Expected behavior**
This value should be `registry` not `reigistry`

* Helm charts version info
v1.3.0
* Helm charts user-supplied values
N/A
* Kubernetes version information:
N/A
* Kubernetes cluster kind:
N/A

**Additional context**
N/A

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-785) by [Unito](https://www.unito.io)
┆Fix Versions: k8ssandra-1.4.0
┆Issue Number: K8SSAND-785
┆Priority: Medium
