### ISSUE TITLE
Unable to configure service account annotations for medusa-operator

### ISSUE THREAD

**Issue by ilovemysillybanana** [k8ssandra/k8ssandra#1135]
## Bug Report

**Describe the bug**

Unable to configure service account annotations for medusa-operator. 

**To Reproduce**

Apply the following in your configuration:

```yaml
medusa-operator:
  serviceAccount:
    annotations:
      foo: "bar"
```

**Expected behavior**
The `k8ssandra-medusa-operator` service account should now have that annotation, however, it does not.

**Environment (please complete the following information):**
AWS EKS `v1.18.20`

* Helm charts version info
`1.3.1`

* Kubernetes version information:

`kubectl version`

* Kubernetes cluster kind:
AWS EKS
