### ISSUE TITLE
K8SSAND-983 ⁃ SecurityContext default adjustments

### ISSUE THREAD

**Issue by jeffbanks** [k8ssandra/k8ssandra#1140]
As part of the k8ssandra applied security initiative, the `SecurityContext` defaults at the pod and container levels will be applied based on k8s best practices.  The security enhancements are scoped by security epics based on the overall enhancements.

One epic (phase I) will expose the `runAsNonRoot` restriction, whereas another epic (planned for a second phase) will introduce `root filesystem` restrictions per k8s security best practices.

Since root filesystem restrictions are part of a later initiative, the plan is to remove the existing applied default (readOnlyRootFilesystem) as this can be confusing to the k8ssandra user as it is not currently being applied.   This was recently identified as a much larger initiative due to changes required in image dependencies for c*, medusa, reaper, etc.

This issue will include the removal of any `readOnlyRootFilesystem: true | false` defaults, to remove any confusion.  The values.yaml will include the `securityContext: {`} as foundational changes to support upcoming security phased enhancements.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-983) by [Unito](https://www.unito.io)
┆Epic: Pod Security Enhancements
┆Fix Versions: k8ssandra-1.4.0
┆Issue Number: K8SSAND-983
┆Priority: Medium

**Comment by jeffbanks** [comment]
# K8ssandra security - [phase 1 epic](https://k8ssandra.atlassian.net/browse/K8SSAND-705)

* Implementation includes changes for default securityContext settings [PR1126](https://github.com/k8ssandra/k8ssandra/pull/1126).  

* Changes supported in K8ssandra 1.x at this time.

## Placeholders for K8ssandra securityContext 
* Support for all `container`, `init-container`, and `pod` securityContext properties
* Override and default values available in k8ssandra securityContext placeholders [values.yaml](https://github.com/k8ssandra/k8ssandra/blob/3fb6508fb4d97f755732d61715beae55e7fa0eba/charts/k8ssandra/values.yaml).

### Example:

```yaml
baseConfig:
    # -- Security context override for base init container
    securityContext: {}
  # -- The server-config-init init container
  configBuilder:
    # -- Security context override for server-config-init container
    securityContext: {}
    image:
      # -- Container registry for the config builder
      registry: docker.io
      # -- Repository for cass-config-builder image
      repository: datastax/cass-config-builder
      # -- Tag of the config builder image to pull from image repository
      tag: 1.0.4
      # -- Pull policy for the config builder image
      pullPolicy: IfNotPresent
  # -- The jmx-credentials init container that configures JMX credentials.
  jmxCredentialsConfig:
    # -- Security context override for jmx init container
    securityContext: {}
    image:
      # -- Container registry for 
```

## K8ssandra operators - securityContext defaults

* `medusa-operator` and `reaper-operator`  defaults w/ corresponding changes as needed to the operator CRD to support additional security configurations.
* `cassandra-operator` verification for existing securityContext controls

### Applied K8ssandra defaults

```yaml
# -- PodSecurityContext for the reaper-operator pod.
podSecurityContext: {}

# -- SecurityContext for the reaper-operator container.
securityContext:
  runAsNonRoot: true
  runAsUser: 65534
  runAsGroup: 65534
  readOnlyRootFilesystem: true
```

```yaml
# -- SecurityContext for the medusa-operator pod.
podSecurityContext: {}

# -- SecurityContext for the medusa-operator container.
securityContext:
  runAsNonRoot: true
  runAsUser: 65534
  runAsGroup: 65534
  readOnlyRootFilesystem: true
```

```yaml
securityContext:
  runAsNonRoot: true
  runAsGroup: 65534
  runAsUser: 65534
  readOnlyRootFilesystem: true
```

## `reaper-operator` security controls

* `CRD change` to allow init-container scoped security settings along with non-init containers and pods.

```golang
// SchemaInitContainerConfig encapsulates settings applied to the Reaper schema init container
SchemaInitContainerConfig InitContainerConfig `json:"schemaInitContainerConfig,omitempty" yaml:"schemaInitContainerConfig,omitempty"`

// ConfigInitContainerConfig encapsulates settings applied to the Reaper config init container
ConfigInitContainerConfig InitContainerConfig `json:"configInitContainerConfig,omitempty" yaml:"configInitContainerConfig,omitempty"`

// SecurityContext applied to the Reaper non-init container
SecurityContext *corev1.SecurityContext `json:"securityContext,omitempty"`

// PodSecurityContext applied to Reaper pods
PodSecurityContext *corev1.PodSecurityContext `json:"podSecurityContext,omitempty"`
```

## `medusa-operator` deployment spec security controls

```yaml
metadata:
      labels: {{- include "k8ssandra-common.labels" . | indent 8 }}
    spec:
      securityContext: {{- toYaml .Values.podSecurityContext | nindent 8 }}
      ... 
      containers:
      - args:
        - --enable-leader-election
        command:
          - /manager
        image: {{ include "k8ssandra-common.flattenedImage" .Values.image }}
        name: medusa-operator
        securityContext: {{- toYaml .Values.securityContext | nindent 12 }}
    ...
```

## `cass-operator` verification

* Existing non-root capabilities were in-place
* Includes `server-logger` [here](https://github.com/k8ssandra/cass-operator/pull/182).

```text
drwxrwxrwx 1 cassandra cassandra   4096 Sep 28 20:03 cassandra
-rw-r--r-- 1 cassandra cassandra    52807 Sep 28 21:02 system.log
```

## `reaper-operator` reconciler changes

* Startup reorder of `config-init` (new) and `schema-init` (existing) containers.
* Applied reaper configuration file for shared mount paths.

```golang
InitContainers: []corev1.Container{
{
	Name:            "reaper-config-init",
	ImagePullPolicy: corev1.PullPolicy(reaper.Spec.ImagePullPolicy),
	Image:           reaper.Spec.Image,
	SecurityContext: reaper.Spec.ConfigInitContainerConfig.SecurityContext,
	Command:         []string{"/bin/sh"},
	Args:            []string{"-c", "cp -r /etc/cassandra-reaper/* /reaper-base-config/"},
	VolumeMounts: []corev1.VolumeMount{
		{
			Name:      "reaper-config",
			ReadOnly:  false,
			MountPath: "/reaper-base-config/",
		},
	},
},
{
	Name:            "reaper-schema-init",
	ImagePullPolicy: corev1.PullPolicy(reaper.Spec.ImagePullPolicy),
	Image:           reaper.Spec.Image,
	SecurityContext: reaper.Spec.SchemaInitContainerConfig.SecurityContext,
	Env:             envVars,
	Args:            []string{"schema-migration"},
	VolumeMounts: []corev1.VolumeMount{
		{
			Name:      "reaper-config",
			ReadOnly:  false,
			MountPath: "/etc/cassandra-reaper",
		},
	},
},
},
```
## Side effects

### [Security phase-2 epic](https://k8ssandra.atlassian.net/browse/K8SSAND-977)
* Epic will address security configurations for associated images (e.g. Stargate and mgmt-api) and further expansion of _k8s security best-practices_.

### [Security foundations for phase-1 blog](https://medium.com/building-the-open-data-stack/k8ssandra-ramps-up-security-features-to-match-kubernetes-best-practices-741d68ea1a0f) 
* Published as reference for phase-1 goals.
