### ISSUE TITLE
Cassandra Reaper shows additional default rack with customized rack name

### ISSUE THREAD

**Issue by mikekuzak** [k8ssandra/k8ssandra#1171]
## Bug Report

**Describe the bug**
When changing the dc/rack name in the helm chart the Reaper UI shows also an additional default rack

**To Reproduce**
1. 
```
cassandra:
  version: "3.11.10"
  allowMultipleNodesPerWorker: false
  cassandraLibDirVolume:
    storageClass: local-path
    size: 120Gi
  heap:
   size: 6G
   newGenSize: 6G
  resources:
    limits:
      cpu: 4000m
      memory: 10Gi
  datacenters:
  - name: us2
    size: 3
    racks:
    - name: qa
stargate:
  enabled: true
  replicas: 1
  heapMB: 256
  cpuReqMillicores: 200
  cpuLimMillicores: 2000
  ingress:
    enabled: false

reaper:
  autoschedule: true
  enabled: true
  ingress:
    enabled: false
  ```
2. Get to the Reaper Repair website
![image](https://user-images.githubusercontent.com/18675587/140794704-9021c245-168e-4af0-9823-b5fab78ba9c8.png)

**Expected behavior**
Default rack shouldn't be present

**Environment (please complete the following information):**
Cassandra v3.11.10

* Helm charts version info
3.5.0

* Kubernetes version information:
1.19.6

* Kubernetes cluster kind:
 helm chart v.1.3.1

It has something to do with Stargate. The pod has a rack env. variable. When I change it the reaper moves the rack into the custom cluster 

![image](https://user-images.githubusercontent.com/18675587/140796224-1dc876c7-0e97-4d00-b441-53af3bbbbf4e.png)

![image](https://user-images.githubusercontent.com/18675587/140796280-1709202b-447c-440a-9dae-3294d438ddd4.png)
