### ISSUE TITLE
K8SSAND-1044 ⁃ Make Cassandra settings configurable for Stargate

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra#1177]
**Is your feature request related to a problem? Please describe.**
In #1169 questions came up about how to change settings for Stargate, `batch_size_fail_threshold_in_kb` specifically. Currently this is no way to configure properties in Stargate's cassandra.yaml. 

**Describe the solution you'd like**
Ideally we will have a consistent solution for configuring cassandra.yaml for both Cassandra and Stargate. That's not going to happen in k8ssandra 1.x. I want to propose a short term solution which we are using in dev/testing with k8ssandra-operator.

Stargate has a system property named `stargate.unsafe.cassandra_config_path` which specifies the location of a custom cassandra.yaml file. We can add a chart property that will specify the name of a user-supplied ConfigMap. The ConfigMap should contain the custom cassandra.yaml. Here is an example take from k8ssandra-operator:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cassandra-config
data:
  cassandra.yaml: |-
    auto_snapshot: false
    memtable_flush_writers: 1
    commitlog_segment_size_in_mb: 2
    concurrent_compactors: 1
    compaction_throughput_mb_per_sec: 0
    sstable_preemptive_open_interval_in_mb: 0
    key_cache_size_in_mb: 0
    thrift_prepared_statements_cache_size_mb: 1
    prepared_statements_cache_size_mb: 1
    start_rpc: false
    slow_query_log_timeout_in_ms: 0
    counter_cache_size_in_mb: 0
    concurrent_reads: 2
    concurrent_writes: 2
    concurrent_counter_writes: 2
    read_request_timeout_in_ms: 30000
    range_request_timeout_in_ms: 30000
    write_request_timeout_in_ms: 30000
    truncate_request_timeout_in_ms: 30000
    request_timeout_in_ms: 30000
```

The `stargate.yaml` template should be updated to create a ConfigMap volume and mount in the Stargate Deployment. 

We could instead expose individual properties and then generate the ConfigMap for the user. For this values.yaml might look something like this:

```yaml
stargate:
  cassandraYaml:
    # batch_size_fail_threshold_in_kb: 150
    # other properties...
```

While more tedious, this is arguably safer and less error-prone.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1044) by [Unito](https://www.unito.io)
┆Reviewer: 5fa4593062584c006b1e04d0
┆epic: Advanced Component Configuration
┆fixVersions: k8ssandra-1.4.0
┆friendlyId: K8SSAND-1044
┆priority: Medium
