### ISSUE TITLE
Changing medusa backup storage from local to s3 does not work. 

### ISSUE THREAD

**Issue by cheapsolutionarchitect** [k8ssandra/k8ssandra#1197]
## Bug Report

**Describe the bug**
Changing the medusa backup storage from local to s3 does not work. At first glance nothing is updated. After restarting the cassandra/medusa pods the medusa.ini (medusa container) has the correct values but the backup process fails due to wrong credentials. The statefulset reponsible for the pods does not declare the needed volume mounts / mount-paths (medusa-secret) after the update. However, the cassandra.datastax.com/v1beta1/cassandradatacenters k8s object is updated to the new values and contains the volume-mounts/paths. 

Additionally during the update the following exception is raised by the cass-operator. 
```
invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden","stacktrace │
│ ":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n │
│ \t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:258\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/p │
│ kg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/go/pkg/mod/sigs.k8s.io/c │
│ ontroller-runtime@v0.5.2/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:152\nk8 │
│ s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0. │
│ 17.4/pkg/util/wait/wait.go:88"}  
```

**To Reproduce**
I used helm  v3.5.3 and a cluster with kubernetes 1.20.7

- Execute `helm install cassandra k8ssandra/k8ssandra -f k8ssandra-values.yaml -n cassandra --version 1.2.0`, while k8ssandra-values.yaml contains the defintion of the values. (see the appended file) 

- Execute `helm upgrade cassandra k8ssandra/k8ssandra -f medusa-backup-restore.yaml -n cassandra --reuse-values --version 1.2.0`

```
# medusa-backup-restore.yaml (replace the region and bucketName)
cassandra:
  datacenters:
  - name: dc1
    size: 3
    racks:
    - name: rack1    
medusa:
  enabled: true
  storage: s3
  storage_properties:
    region: <region>
    secure: false
  bucketName: <bucketname>
  storageSecret: medusa-bucket-key
  podStorage:
```

**Expected behavior**

After application of the change and the execution of the backup the S3 bucket shows the backup data.

**Environment (please complete the following information):**

* Helm charts version info

```
NAME     	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART          	APP VERSION
cassandra	cassandra	2       	2021-11-19 09:07:54.819309522 +0100 CET	deployed	k8ssandra-1.2.0	
```

* Helm charts user-supplied values

```
cass-operator:
  enabled: true
cassandra:
  auth:
    cacheUpdateIntervalMillis: 3600000
    cacheValidityPeriodMillis: 3600000
    enabled: false
    superuser:
      secret: superuser-secret
  cassandraLibDirVolume:
    size: 10Gi
    storageClass: gp2
  clusterName: mycluster
  datacenters:
  - name: dc1
    racks:
    - name: rack1
    size: 3
  enabled: true
  loggingSidecar:
    enabled: true
  resources:
    limits:
      cpu: 1500m
      memory: 8Gi
  tolerations:
  - effect: NoSchedule
    key: dedicated
    operator: Equal
    value: cassandra
  version: 3.11.10
  versionImageMap:
    3.11.7: k8ssandra/cass-management-api:3.11.7-v0.1.25
    3.11.8: k8ssandra/cass-management-api:3.11.8-v0.1.25
    3.11.9: k8ssandra/cass-management-api:3.11.9-v0.1.25
    3.11.10: k8ssandra/cass-management-api:3.11.10-v0.1.25
    4.0.0: k8ssandra/cass-management-api:4.0.0-v0.1.25
cleaner:
  image: k8ssandra/k8ssandra-tools:latest
client:
  image: k8ssandra/k8ssandra-tools:latest
kube-prometheus-stack:
  enabled: false
medusa:
  bucketName: <bucketname>
  cassandraUser:
    secret: medusa-user-secret
  enabled: true
  image:
    pullPolicy: IfNotPresent
    repository: docker.io/k8ssandra/medusa
    tag: 0.10.1
  storage: s3
  storage_properties:
    region: <region>
    secure: false
  storageSecret: medusa-bucket-key
monitoring:
  grafana:
    provision_dashboards: false
  prometheus:
    provision_service_monitors: true
reaper:
  autoschedule: false
  cassandraUser:
    secret: reaper-user-secret
  enabled: true
  image:
    repository: docker.io/thelastpickle/cassandra-reaper
    tag: 2.2.2
  jmx:
    secret: reaper-jmx-secret
reaper-operator:
  enabled: true
stargate:
  enabled: false
```

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.6", GitCommit:"8a62859e515889f07e3e3be6a1080413f17cf2c3", GitTreeState:"clean", BuildDate:"2021-04-15T03:28:42Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.7-eks-d88609", GitCommit:"d886092805d5cc3a47ed5cf0c43de38ce442dfcb", GitTreeState:"clean", BuildDate:"2021-07-31T00:29:12Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind:

Small AWS test cluster, manual setup. 

**Additional context**
[k8ssandra-values.md](https://github.com/k8ssandra/k8ssandra/files/7569079/k8ssandra-values.md)
