### ISSUE TITLE
Medusa restore fails, because taints are vanished from the STS that the restore deploys

### ISSUE THREAD

**Issue by cheapsolutionarchitect** [k8ssandra/k8ssandra#1205]
## Bug Report

**Describe the bug**
Medusa restore fails, because taints are vanished from the k8ssandra-STS which the restore deploys.

**To Reproduce**
- Create a simple cluster with tainted nodes
- Create a k8ssandra installation where the helm chart contains the settings for the tolerations
- Install a k8ssandra managed cluster
- Create a backup 
- Restore the backup

**Expected behavior**
It works.

* Helm charts user-supplied values
```
USER-SUPPLIED VALUES:
cass-operator:
  enabled: true
cassandra:
  auth:
    cacheUpdateIntervalMillis: 3600000
    cacheValidityPeriodMillis: 3600000
    enabled: false
    superuser:
      secret: superuser-secret
  cassandraLibDirVolume:
    size: 10Gi
    storageClass: gp2
  clusterName: mycluster
  datacenters:
  - heap:
      size: 6G
    name: dc1
    num_tokens: 16
    racks:
    - name: rack1
    size: 3
  enabled: true
  loggingSidecar:
    enabled: true
  resources:
    limits:
      cpu: 1500m
      memory: 8Gi
  tolerations:
  - effect: NoSchedule
    key: dedicated
    operator: Equal
    value: cassandra
  version: 3.11.10
  versionImageMap:
    3.11.7: k8ssandra/cass-management-api:3.11.7-v0.1.25
    3.11.8: k8ssandra/cass-management-api:3.11.8-v0.1.25
    3.11.9: k8ssandra/cass-management-api:3.11.9-v0.1.25
    3.11.10: k8ssandra/cass-management-api:3.11.10-v0.1.25
    4.0.0: k8ssandra/cass-management-api:4.0.0-v0.1.25
cleaner:
  image: k8ssandra/k8ssandra-tools:latest
client:
  image: k8ssandra/k8ssandra-tools:latest
kube-prometheus-stack:
  enabled: false
medusa:
  cassandraUser:
    secret: medusa-user-secret
  enabled: true
  image:
    pullPolicy: IfNotPresent
    repository: docker.io/k8ssandra/medusa
    tag: 0.10.1
  podStorage:
    size: 10Gi
    storageClass: gp2
  storage: local
monitoring:
  grafana:
    provision_dashboards: false
  prometheus:
    provision_service_monitors: true
reaper:
  autoschedule: false
  cassandraUser:
    secret: reaper-user-secret
  enabled: true
  image:
    repository: docker.io/thelastpickle/cassandra-reaper
    tag: 2.2.2
  jmx:
    secret: reaper-jmx-secret
reaper-operator:
  enabled: true
stargate:
  enabled: false
```
* Kubernetes version information:
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.6", GitCommit:"8a62859e515889f07e3e3be6a1080413f17cf2c3", GitTreeState:"clean", BuildDate:"2021-04-15T03:28:42Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.7-eks-d88609", GitCommit:"d886092805d5cc3a47ed5cf0c43de38ce442dfcb", GitTreeState:"clean", BuildDate:"2021-07-31T00:29:12Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind:
AWS manual setup
**Additional context**
The medusa operator spits out the following message

```
2021-11-25T08:27:35.845Z	ERROR	controllers.CassandraRestore	failed to update the cassandradatacenter	{"CassandraDatacenter": "cassandra/dc1", "error": "Operation cannot be fulfilled on cassandradatacenters.cassandra.datastax.com \"dc1\": the object has been modified; please apply your changes to the latest version and try again"}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128
github.com/k8ssandra/medusa-operator/controllers.(*CassandraRestoreReconciler).Reconcile
	/workspace/controllers/cassandrarestore_controller.go:155
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.5/pkg/internal/controller/controller.go:244
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.5/pkg/internal/controller/controller.go:218
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.5/pkg/internal/controller/controller.go:197
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.Until
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:90
2021-11-25T08:27:35.845Z	ERROR	controller	Reconciler error	{"reconcilerGroup": "cassandra.k8ssandra.io", "reconcilerKind": "CassandraRestore", "controller": "cassandrarestore", "name": "restore-medusa-backup-20211125081106", "namespace": "cassandra", "error": "Operation cannot be fulfilled on cassandradatacenters.cassandra.datastax.com \"dc1\": the object has been modified; please apply your changes to the latest version and try again"}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.5/pkg/internal/controller/controller.go:246
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.5/pkg/internal/controller/controller.go:218
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.5/pkg/internal/controller/controller.go:197
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.Until
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:90
```
