### ISSUE TITLE
K8SSAND-1072 ⁃ The PVCs are deleted k8ssandra is upgraded with no additional seeds

### ISSUE THREAD

**Issue by hpdsvg** [k8ssandra/k8ssandra#1209]
@jsanda  the PVCs are deleted when I upgraded k8ssandra. It happened twice. I was able to reproduce

Initial deployment was using this command where I had seeds

```
 helm upgrade k8ssandra k8ssandra/k8ssandra \
  --install \
  --namespace database \
  --values=./services/k8sssandra/helm-charts/values.yaml \
  --values=./services/k8sssandra/helm-charts/secrets/secrets-dev.yaml \
  --set cassandra.cassandraLibDirVolume.storageClass="gp2-encrypted" \
  --set cassandra.cassandraLibDirVolume.size="768Gi" \
  --set cassandra.additionalSeeds='{cassandra-0.database,cassandra-1.database,cassandra-2.database}' \
  --set cassandra.version=4.0.1 \
  --version 1.4.0 \

```

Redeployed using below command and removed additional seeds as shown below and found all the k8ssandra pods and PVCs are missing.

```
helm upgrade k8ssandra k8ssandra/k8ssandra \
  --install \
  --namespace database \
  --values=./services/k8sssandra/helm-charts/values.yaml \
  --values=./services/k8sssandra/helm-charts/secrets/secrets-dev.yaml \
  --set cassandra.cassandraLibDirVolume.storageClass="gp2-encrypted" \
  --set cassandra.cassandraLibDirVolume.size="768Gi" \
  --set cassandra.additionalSeeds='{}' \
  --set cassandra.version=4.0.1 \
  --version 1.4.0 \
;
```

Attached is the cass-operator log
[k8ssandra-cass-operator-76df49bc-fl2g2.log](https://github.com/k8ssandra/k8ssandra/files/7621938/k8ssandra-cass-operator-76df49bc-fl2g2.log)

Why are PVCs deleted. Even after deleting helm charts it should never delete PVCs unless it is explicitly deleted?

_Originally posted by hpdsvg in https://github.com/k8ssandra/k8ssandra/issues/1200#issuecomment-982154594_

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1072) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1072
┆priority: Medium

**Comment by hermeias** [comment]
Possibly the values of  " --values=./services/k8sssandra/helm-charts/values-dev.yaml" were used, and you got yourself a new deployment.

**Comment by hpdsvg** [comment]
> Possibly the values of " --values=./services/k8sssandra/helm-charts/values-dev.yaml" were used, and you got yourself a new deployment.

I think I had that extra line. I have removed it from the above message and confirm that the values were same in both except the seeds.
Additionally, even if with new values it should never delete PVCs and PVCs have the data and it should not be deleted with new deployment/statefulset

**Comment by jsanda** [comment]
As I mentioned in #1200 when the CassandraDatacenter is deleted, cass-operator will in fact delete all of the PVCs. 

What does `./services/k8sssandra/helm-charts/values.yaml` look like?

**Comment by hpdsvg** [comment]
@jsanda Here is the content of the values.yaml file
```
---

cassandra:
  cassandraLibDirVolume:
    storageClass: gp2-encrypted
    size: 100Gi
  allowMultipleNodesPerWorker: true
  heap:
    size: 4G
    newGenSize: 1G
  resources:
    limits: 
      cpu: 4
      memory: 10Gi
    requests: 
      cpu: 2000m
      memory: 8Gi
  datacenters:
  - name: dc2
    size: 6
    racks:
    - name: default
  clusterName: cassandra
  # additionalSeeds:
  # # The following should be replaced with actual IP addresses or
  # # hostnames of pods in the original datacenter.
  
  auth:
    enabled: true
    superuser:
      secret: "[redacted]"
      
reaper:
  enabled: true
  autoschedule: true
  autoschedule_properties:
    autoschedule_properties:
    initialDelayPeriod: PT15S
    periodBetweenPolls: PT10M
    timeBeforeFirstSchedule: PT5M
    scheduleSpreadPeriod: PT6H
    excludedKeyspaces: []
    excludedClusters: []

medusa:
  enabled: true
  multiTenant: true
  bucketName: [redacted]
  storageSecret: [redacted]
  storage_properties:
    region: us-east-2

k8ssandra-operator:
  enabled: false

cass-operator:
  enabled: true

reaper-operator:
  enabled: true

kube-prometheus-stack:
  enabled: false

stargate:
  enabled: false
  replicas: 1
  heapMB: 256
  cpuReqMillicores: 200
  cpuLimMillicores: 1000
```
