### ISSUE TITLE
K8SSAND-1114 ⁃ unknown field "podSecurityContext" in io.cassandra-reaper.reaper.v1alpha1.Reaper.spec

### ISSUE THREAD

**Issue by mikekuzak** [k8ssandra/k8ssandra#1225]
## Bug Report
**Describe the bug**
Helm Update from v1.3.3 to v1.4.1 fails with error:

```
namespace/k8ssandra unchanged
ingress.networking.k8s.io/cassandra-stargate-rest unchanged
ingress.networking.k8s.io/cassandra-stargate-auth unchanged
ingress.networking.k8s.io/cassandra-reaper unchanged
secret/medusa-bucket-key configured
configmap/cassandra-config created
"k8ssandra" already exists with the same configuration, skipping
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "sonatype" chart repository
...Successfully got an update from the "elastic" chart repository
...Successfully got an update from the "k8ssandra" chart repository
...Successfully got an update from the "jupyterhub" chart repository
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈Happy Helming!⎈
Error: UPGRADE FAILED: error validating "": error validating data: [ValidationError(Reaper.spec): unknown field "podSecurityContext" in io.cassandra-reaper.reaper.v1alpha1.Reaper.spec, ValidationError(Reaper.spec): unknown field "securityContext" in io.cassandra-reaper.reaper.v1alpha1.Reaper.spec]
```

**To Reproduce**
Just changed the version of the helm chart and added new property from stargate
cassandraYamlConfigMap: cassandra-config

CI/CD:

```
APP_NAME="k8ssandra"
HELM_REPO_NAME="k8ssandra"
HELM_REPO_URL="https://helm.k8ssandra.io/stable"
HELM_NAME="k8ssandra/k8ssandra"
NAMESPACE="k8ssandra"

install() {
    echo "Running deployment for $ENVIRONMENT"
    getContext
    
    # Create Ingress Definiations
    kubectl apply -n ${NAMESPACE} -f ${CLUSTER}/rancher-crd.yaml
    
    helm repo add ${HELM_REPO_NAME} ${HELM_REPO_URL}
    helm repo update
    helm upgrade --install -n ${NAMESPACE} --values=${CLUSTER}/custom-values.yaml ${APP_NAME} ${HELM_NAME} --version $(cat ${CLUSTER}/version.txt)
    
    # Expose Cassandra directly via TCP
    kubectl patch configmap tcp-services -n ingress-nginx --patch '{"data":{"9042":"k8ssandra/k8ssandra-dc1-stargate-service:9042"}}'
    
}
```

**Expected behavior**
Update successful

**Environment (please complete the following information):**

* Helm charts version info
v1.3.3 installed -> upgrading to v1.4.1
* Helm charts user-supplied values

```
cassandra:
  version: "3.11.10"
  allowMultipleNodesPerWorker: false
  cassandraLibDirVolume:
    storageClass: local-path
    size: 120Gi
  heap:
   size: 6G
   newGenSize: 6G
  resources:
    limits:
      cpu: 4000m
      memory: 10Gi
  datacenters:
  - name: dc1
    size: 3
    racks:
    - name: default

stargate:
  enabled: true
  replicas: 2
  heapMB: 256
  cassandraYamlConfigMap: cassandra-config
  cpuReqMillicores: 200
  cpuLimMillicores: 2000
  ingress:
    enabled: false

reaper:
  autoschedule: true
  enabled: true
  ingress:
    enabled: false

medusa:
  enabled: true
  storage: s3_compatible
  storage_properties:
      host: minio.storage.mycomp.com
      port: 80
      secure: "False"
  bucketName: k8ssandra
  storageSecret: medusa-bucket-key
  
kube-prometheus-stack:
  enabled: false
  prometheusOperator:
    enabled: false
  prometheus:
    enabled: false
    prometheusSpec:
      externalUrl: http://<YOURADDRESS>:8080/prometheus
      routePrefix: /prometheus
    ingress:
      enabled: false
      paths:
        - /prometheus
  grafana:
    enabled: false
    adminPassword: xxxx
    ingress:
      enabled: false
      path: /grafana
    plugins:
      - grafana-polystat-panel
    grafana.ini:
      server:
        root_url: http://<YOURADDRESS>:8080/grafana
        serve_from_sub_path: true
```

* Kubernetes version information:

```
<!-- Replace the command with its output -->
-bash-4.2$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.6", GitCommit:"fbf646b339dc52336b55d8ec85c181981b86331a", GitTreeState:"clean", BuildDate:"2020-12-18T12:01:36Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.22) and server (1.19) exceeds the supported minor version skew of +/-1
```

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1114) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1114
┆priority: Medium
