### ISSUE TITLE
Include Consistent Label Names

### ISSUE THREAD

**Issue by jeffbanks** [k8ssandra/k8ssandra#123]
Observation of current set of labels in the k8ssandra ecosystem reveals the need for standardized key inclusion.

```
Example:  
name=cass-operator,pod-template-hash=cd9b57568

name=cassdc-grafana-operator-k8ssandra,pod-template-hash=6499f6bf5d

name=cassdc-reaper-operator-k8ssandra,pod-template-hash=65785855d8

app=grafana,pod-template-hash=7f69d5bcc8

app=kube-prometheus-stack-operator,chart=kube-prometheus-stack-11.1.6,heritage=Helm,pod-template-hash=6c79b68b,release=k8ssandra

app=prometheus,controller-revision-hash=prometheus-cassdc-prometheus-k8ssandra-96955d798,prometheus=cassdc-prometheus-k8ssandra,statefulset.

chart=traefik-9.11.0,pod-template-hash=78475b54fc
```

It would be good to create consistency of key names for the k8ssandra resources.   Some may differ based on the resource, but all would include a consistent name for inspection.  For example, each one would include a standard `name` key w/ an expected value.

This would assist with `k8ssandra` diagnostics and testing.  A documented standard should also be included based on the outcome of the standards.

**Comment by jsanda** [comment]
Here is an example set of labels that we generate:

```yaml
app.kubernetes.io/instance: stargate-test
app.kubernetes.io/managed-by: Helm
app.kubernetes.io/name: k8ssandra-cluster
app.kubernetes.io/version: 3.11.7
helm.sh/chart: k8ssandra-cluster-0.14.0
```
We should be adding these to every resource that we create in Helm templates. Those labels do not however get added to other resources that are created via operator or in other charts.
