### ISSUE TITLE
K8SSAND-1192 ⁃ maxGcPauseMillis helm chart setting does not execute against JVM command

### ISSUE THREAD

**Issue by Macfelon** [k8ssandra/k8ssandra#1269]
## Bug Report
**Describe the bug**
When setting maxGcPauseMillis, and then checking the options that are running on the JVM, it does not seem to have gone through.

**To Reproduce**

1. In your helm chart, change the maxGcPausMillis value:

```yaml
 datacenters:
      -
        audit_logging: {}
        client_backpressure: {}
        fql: {}
        gc:
          cms: {}
          g1: 
            enabled: true
            maxGcPauseMillis: **200**
            parallelGcThreads: 16
            concurrentGcThreads: 16
```

1. Restart the DataCenter
1. Go into a CLI and ps -ef on the java job to see the setting as the value of 500

**Expected behavior**
We would have expected the value to change to 200

* Helm charts version info
4.14.1
* Helm charts user-supplied values
 maxGcPauseMillis: **200**
4.14.1
* Kubernetes version information:
`1.20.9`
* Kubernetes cluster kind:

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1192) by [Unito](https://www.unito.io)
┆fixVersions: k8ssandra-v1.5.0
┆friendlyId: K8SSAND-1192
┆priority: Medium
