### ISSUE TITLE
K8SSAND-1205 ⁃ Document single-cluster installation on AKS via k8ssandra-operator

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra#1281]
Create straw man documentation to guide users though a single-cluster installation on AKS via K8ssandra-operator with helm.  Include a basic example of using ingress to externally access the Stargate auth and docs APIs.

Leverage the existing install guide as a basis for this documentation:  [https://github.com/k8ssandra/k8ssandra-operator/blob/main/docs/install/README.md](https://github.com/k8ssandra/k8ssandra-operator/blob/main/docs/install/README.md)

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1205) by [Unito](https://www.unito.io)
┆fixVersions: k8ssandra-operator-v1.0.0
┆friendlyId: K8SSAND-1205
┆priority: Medium

**Comment by jdonenine** [comment]
# Azure Kubernetes Service

## Environment

## Tools

Install the Azure CLI locally:

[Azure Documentation](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli)

On MacOS (or Linux) via Homebrew:

```
brew update && brew install azure-cli
```

## Single Cluster

Deploy a cluster via terraform, Azure template, Azure CLI, or the Azure Portal.

Here I've deployed using the Azure Portal:

<img width="838" alt="Screen Shot 2022-02-01 at 8 28 04 AM" src="https://user-images.githubusercontent.com/7901615/152017154-ad62d77f-260b-43c8-a1b4-6e18fd0cfd81.png">

Configure the Azure CLI using the guide provided from within the Azure Portal for your cluster:

```
% az login

% az account set --subscription <subscription-id>

% az aks get-credentials --resource-group k8ssandra-dev --name k8ssandra-operator-demo
Merged "k8ssandra-operator-demo" as current context in /Users/jeffdinoto/.kube/config
```

Verify cluster deployment:

```
% kubectl get nodes
NAME                                STATUS   ROLES   AGE   VERSION
aks-agentpool-34186547-vmss000000   Ready    agent   26m   v1.21.7
aks-agentpool-34186547-vmss000001   Ready    agent   26m   v1.21.7
aks-agentpool-34186547-vmss000002   Ready    agent   26m   v1.21.7
aks-agentpool-34186547-vmss000003   Ready    agent   26m   v1.21.7
```

Deploy cert-manager:

```
$ helm repo add jetstack https://charts.jetstack.io

$ helm repo update

$ helm install cert-manager jetstack/cert-manager --namespace cert-manager --create-namespace --set installCRDs=true
NAME: cert-manager
LAST DEPLOYED: Mon Jan 31 12:29:43 2022
NAMESPACE: cert-manager
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
cert-manager v1.7.0 has been deployed successfully!

In order to begin issuing certificates, you will need to set up a ClusterIssuer
or Issuer resource (for example, by creating a 'letsencrypt-staging' issuer).

More information on the different types of issuers and how to configure them
can be found in our documentation:

https://cert-manager.io/docs/configuration/

For information on how to configure cert-manager to automatically provision
Certificates for Ingress resources, take a look at the `ingress-shim`
documentation:

https://cert-manager.io/docs/usage/ingress/
```

Deploy k8ssandra-operator:
```
$ helm install k8ssandra-operator k8ssandra/k8ssandra-operator -n k8ssandra-operator --create-namespace
NAME: k8ssandra-operator
LAST DEPLOYED: Mon Jan 31 12:30:40 2022
NAMESPACE: k8ssandra-operator
STATUS: deployed
REVISION: 1
TEST SUITE: None
```

Verify k8ssandra-operator deployment:

```
$ kubectl get pods -n k8ssandra-operator
NAME                                                READY   STATUS    RESTARTS   AGE
k8ssandra-operator-7f76579f94-7s2tw                 1/1     Running   0          60s
k8ssandra-operator-cass-operator-794f65d9f4-j9lm5   1/1     Running   0          60s
```

Deploy a K8ssandraCluster:

```
% cat k8c-aks.yaml
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: demo
spec:
  cassandra:
    serverVersion: "4.0.1"
    datacenters:
      - metadata:
          name: dc1
        size: 3
        storageConfig:
          cassandraDataVolumeClaimSpec:
            storageClassName: "managed-premium"
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
        config:
          jvmOptions:
            heapSize: 512M
        stargate:
          size: 1
          heapSize: 256M
          
% kubectl apply -n k8ssandra-operator -f k8c-aks.yaml
```

Extract the username and password: 

```
% CASS_USERNAME=$(kubectl get secret demo-superuser -n k8ssandra-operator -o=jsonpath='{.data.username}' | base64 --decode)

% echo $CASS_USERNAME
demo-superuser

% CASS_PASSWORD=$(kubectl get secret demo-superuser -n k8ssandra-operator -o=jsonpath='{.data.password}' | base64 --decode)

% echo $CASS_PASSWORD
VGwk7C9RbviXmiucJKI2
```

Verify the cluster status:

```
% kubectl exec --stdin --tty demo-dc1-default-sts-0 -n k8ssandra-operator -- nodetool -u $CASS_USERNAME -pw $CASS_PASSWORD status
Defaulted container "cassandra" out of: cassandra, server-system-logger, jmx-credentials (init), server-config-init (init)
Datacenter: dc1
===============
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address     Load        Tokens  Owns (effective)  Host ID                               Rack
UN  10.244.3.5  143.5 KiB   16      100.0%            57c9820b-2476-498a-ae5f-8c2f2fe9c3b1  default
UN  10.244.2.7  150.92 KiB  16      100.0%            358c0618-3f81-482a-bb06-2cae4278f8d5  default
UN  10.244.0.7  149.72 KiB  16      100.0%            5a91ae1e-d9a0-4bea-8199-797345ffde85  default
```

Test some operations via Stargate:

```
% kubectl exec --stdin --tty demo-dc1-default-sts-0 -n k8ssandra-operator -c cassandra -- cqlsh -u $CASS_USERNAME -p $CASS_PASSWORD demo-dc1-stargate-service -e "CREATE KEYSPACE test WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 3};"

% kubectl exec --stdin --tty demo-dc1-default-sts-0 -n k8ssandra-operator -c cassandra -- cqlsh -u $CASS_USERNAME -p $CASS_PASSWORD demo-dc1-stargate-service -e "CREATE TABLE test.users (email text primary key, name text, state text);"

% kubectl exec --stdin --tty demo-dc1-default-sts-0 -n k8ssandra-operator -c cassandra -- cqlsh -u $CASS_USERNAME -p $CASS_PASSWORD demo-dc1-stargate-service -e "insert into test.users (email, name, state) values ('john@gamil.com', 'John Smith', 'NC');"

% kubectl exec --stdin --tty demo-dc1-default-sts-0 -n k8ssandra-operator -c cassandra -- cqlsh -u $CASS_USERNAME -p $CASS_PASSWORD demo-dc1-stargate-service -e "insert into test.users (email, name, state) values ('joe@gamil.com', 'Joe Jones', 'VA');"

% kubectl exec --stdin --tty demo-dc1-default-sts-0 -n k8ssandra-operator -c cassandra -- cqlsh -u $CASS_USERNAME -p $CASS_PASSWORD demo-dc1-stargate-service -e "insert into test.users (email, name, state) values ('sue@help.com', 'Sue Sas', 'CA');"

% kubectl exec --stdin --tty demo-dc1-default-sts-0 -n k8ssandra-operator -c cassandra -- cqlsh -u $CASS_USERNAME -p $CASS_PASSWORD demo-dc1-stargate-service -e "insert into test.users (email, name, state) values ('tom@yes.com', 'Tom and Jerry', 'NV');"

% kubectl exec --stdin --tty demo-dc1-default-sts-0 -n k8ssandra-operator -c cassandra -- cqlsh -u $CASS_USERNAME -p $CASS_PASSWORD demo-dc1-stargate-service -e "select * from test.users;"

 email          | name          | state
----------------+---------------+-------
 john@gamil.com |    John Smith |    NC
  joe@gamil.com |     Joe Jones |    VA
   sue@help.com |       Sue Sas |    CA
    tom@yes.com | Tom and Jerry |    NV

(4 rows)
```

Expose and access services in the cluster remotely with ingress:

Install nginx:

```
% helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
"ingress-nginx" has been added to your repositories

% helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "jfelten" chart repository
...Successfully got an update from the "ingress-nginx" chart repository
...Successfully got an update from the "jetstack" chart repository
...Successfully got an update from the "k8ssandra-stable" chart repository
...Successfully got an update from the "k8ssandra-next" chart repository
...Successfully got an update from the "k8ssandra" chart repository
...Successfully got an update from the "traefik" chart repository
Update Complete. ⎈Happy Helming!⎈

% helm install ingress-nginx ingress-nginx/ingress-nginx --create-namespace --namespace nginx
NAME: ingress-nginx
LAST DEPLOYED: Tue Feb  1 11:22:52 2022
NAMESPACE: nginx
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
The ingress-nginx controller has been installed.
It may take a few minutes for the LoadBalancer IP to be available.
You can watch the status by running 'kubectl --namespace nginx get services -o wide -w ingress-nginx-controller'

An example Ingress that makes use of the controller:
  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: example
    namespace: foo
  spec:
    ingressClassName: nginx
    rules:
      - host: www.example.com
        http:
          paths:
            - backend:
                service:
                  name: exampleService
                  port:
                    number: 80
              path: /
    # This section is only required if TLS is to be enabled for the Ingress
    tls:
      - hosts:
        - www.example.com
        secretName: example-tls

If TLS is enabled for the Ingress, a Secret containing the certificate and key must also be provided:

  apiVersion: v1
  kind: Secret
  metadata:
    name: example-tls
    namespace: foo
  data:
    tls.crt: <base64 encoded cert>
    tls.key: <base64 encoded key>
  type: kubernetes.io/tls
```

Check the ingress controller service and note the external IP address:

```
% kubectl get services -n nginx
NAME                                 TYPE           CLUSTER-IP    EXTERNAL-IP     PORT(S)                      AGE
ingress-nginx-controller             LoadBalancer   10.0.248.21   52.191.19.208   80:32319/TCP,443:32356/TCP   56s
ingress-nginx-controller-admission   ClusterIP      10.0.0.251    <none>          443/TCP                      56s
```

Deploy ingress rules to access Stargate via HTTTP:

```
% cat k8ssandra-stargate-ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k8ssandra-stargate-ingress
  namespace: k8ssandra-operator
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
        - backend:
            service:
              name: demo-dc1-stargate-service
              port:
                number: 8081
          path: /v1/auth
          pathType: Prefix
        - backend:
            service:
              name: demo-dc1-stargate-service
              port:
                number: 8082
          path: /v2/schemas
          pathType: Prefix
        - backend:
            service:
              name: demo-dc1-stargate-service
              port:
                number: 8082
          path: /v2/keyspaces
          pathType: Prefix
          
% kubectl apply -n k8ssandra-operator -f k8ssandra-stargate-ingress.yaml
ingress.networking.k8s.io/k8ssandra-stargate-ingress created

% kubectl get ingress -n k8ssandra-operator
NAME                         CLASS   HOSTS   ADDRESS   PORTS   AGE
k8ssandra-stargate-ingress   nginx   *                 80      6s
```

Retrieve an authentication token:

```
% curl -L -X POST 'http://52.191.19.208/v1/auth' -H 'Content-Type: application/json' --data-raw '{"username": "'$CASS_USERNAME'", "password": "'$CASS_PASSWORD'"}'
{"authToken":"f24f669d-ee5d-4193-8f54-7c1a7d6e9be7"}
```

Now use that token to make a query via the Stargate document API:

```
% STARGATE_AUTH_TOKEN=f24f669d-ee5d-4193-8f54-7c1a7d6e9be7

% echo $STARGATE_AUTH_TOKEN
f24f669d-ee5d-4193-8f54-7c1a7d6e9be7

% curl -L \
-X GET 'http://52.191.19.208/v2/keyspaces/test/users?where=\{"email":\{"$in":\["john@gamil.com","sue@help.com"\]\}\}' \
-H "X-Cassandra-Token: $STARGATE_AUTH_TOKEN" \
-H "accept: application/json"
{"count":2,"data":[{"name":"John Smith","email":"john@gamil.com","state":"NC"},{"name":"Sue Sas","email":"sue@help.com","state":"CA"}]}
```

This can also be tested through a tool like Postman:

![Screen Shot 2022-02-01 at 12 05 00 PM](https://user-images.githubusercontent.com/7901615/152018187-9840d25e-4e53-4785-abcd-6b400fa8db96.png)

![Screen Shot 2022-02-01 at 12 04 50 PM](https://user-images.githubusercontent.com/7901615/152018224-5bae978f-2146-4cab-968b-acdc02d30490.png)
