### ISSUE TITLE
K8SSAND-1295 ⁃ medusa operator against google storage does 1 rack backup instead of 3 in a DC

### ISSUE THREAD

**Issue by alokhom** [k8ssandra/k8ssandra#1328]
## Bug Report
Google Store medusa operator backup does not backup for '3 racks' but only '1 rack' in a DC.

**Describe the bug**
I am facing issues with the cassandra medusa backup using google_storage driver. ( k8ssandra chart version 1.4.1)
The google store folder *.cassandra* shows only folders for _index_ and _main-cluster-dc1-rack1-sts-0_ and **no folders** for _main-cluster-dc1-rack2-sts-0_ and _main-cluster-dc1-rack3-sts-0_ as expected. 

**To Reproduce**
backup manifests

```
    apiVersion: cassandra.k8ssandra.io/v1alpha1
    kind: CassandraBackup
    metadata:
      name: medusa-daily-timestamp
      namespace: cassandra
    spec:
      backupType: "differential"
      name: medusa-daily-timestamp
      cassandraDatacenter: dc1
```
the timestamp is replaced.
`export backupTimestamp="$(date +%Y%m%d%H%M%S)"; cat ./scripts/cassandra_backup.yaml | sed s/timestamp/"$backupTimestamp"/g | kubectl apply -f -`

**Expected behavior**

1. Backups for 3 racks pods should form. 
2. 4 folders to see in google store  *.cassandra* bucket are *index_*, *main-cluster-dc1-rack1-sts-0* ,*main-cluster-dc1-rack2-sts-0* and *main-cluster-dc1-rack3-sts-0*. 

**Screenshots**
![image](https://user-images.githubusercontent.com/12021776/156161198-65f6858d-0397-45c3-9fad-9ffdeee55675.png)

**Environment (please complete the following information):**

* Helm charts version info
k8ssandra 1.4.1

`$ helm ls -A` 
we are using fluxCD HelmRelease manifests to deploy helm chart

* Helm charts user-supplied values
`$ helm get values RELEASE_NAME` 
configuration used in helm values.yaml

```
spec:
  values:
    cassandra:
      cassandraLibDirVolume:
        size: 100Gi
      heap:
        size: 1G
        newGenSize: 1G
      resources:
        requests:
          cpu: 1
          memory: 2Gi
        limits:
          cpu: 1
          memory: 3Gi
      clusterName: main-cluster
      auth:
        enabled: false
      datacenters:
        - name: dc1
          size: 3
          racks:
            - name: rack1
            - name: rack2
            - name: rack3
    stargate:
      enabled: false

    medusa:
      enabled: true
      multiTenant: true
      storage: google_storage
      bucketName: gcloudsxxxxx
      storageSecret: google-storage-s3-json
```

* Kubernetes version information:
`kubectl version`

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.6-gke.1500", GitCommit:"7ce0f9f1939dfc1aee910732e84cba03840df91e", GitTreeState:"clean", BuildDate:"2021-11-17T09:30:26Z", GoVersion:"go1.16.9b7", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:
using gke standard

**Additional context**
all permits for the bucket are offered following https://github.com/spotify/cassandra-medusa/blob/master/docs/permissions-setup.md 
```
iam.serviceAccountKeys.create
iam.serviceAccounts.create
storage.buckets.create
storage.buckets.createTagBinding
storage.buckets.delete
storage.buckets.deleteTagBinding
storage.buckets.get
storage.buckets.getIamPolicy
storage.buckets.list
storage.buckets.listTagBindings
storage.buckets.setIamPolicy
storage.buckets.update
storage.objects.create
storage.objects.delete
storage.objects.get
storage.objects.getIamPolicy
storage.objects.list
storage.objects.update
```

logs for medusa operator 
[cassandra-medusa-operator-54fb4b8b9d-x47kq.txt](https://github.com/k8ssandra/k8ssandra/files/8161499/cassandra-medusa-operator-54fb4b8b9d-x47kq.txt)

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1295) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1295
┆priority: Medium
