### ISSUE TITLE
K8SSAND-1323 ⁃ Reg: Supported Cassandra versions in k8ssandra-operator

### ISSUE THREAD

**Issue by prasus** [k8ssandra/k8ssandra#1352]
Greetings 👋🏿 The [documentation](https://docs.k8ssandra.io/release-notes/#k8ssandra-operator-10x-deployments) of the k8ssandra operator indicates that it supports cassandra versions `3.11.7`, `3.11.8` etc. but when I attempt to spin up a `3.11.7` cluster it fails to deploy and leaves the below messages in the operator logs.

```
ERROR	controller.k8ssandracluster	Reconciler error	{"reconciler group": "k8ssandra.io", "reconciler kind": "K8ssandraCluster", "name": "cassandra", "namespace": "default", "error": "CassandraDatacenter.cassandra.datastax.com \"jaam\" is invalid: spec.serverVersion: Unsupported value: \"3.11.7\": supported values: \"6.8.0\", \"3.11.6\", \"4.0.0\""}
```

Surprisingly, I get the same behavior when I tried to deploy with versions `4.0.1` (the one mentioned as the default in the docs).

```
ERROR	controller.k8ssandracluster	Reconciler error	{"reconciler group": "k8ssandra.io", "reconciler kind": "K8ssandraCluster", "name": "cassandra", "namespace": "default", "error": "CassandraDatacenter.cassandra.datastax.com \"jaam\" is invalid: spec.serverVersion: Unsupported value: \"4.0.1\": supported values: \"6.8.0\", \"3.11.6\", \"4.0.0\""}
```

The version `4.0.0` deploys without issues, and other versions like `3.11.6` which is listed as supported in the operator logs fail with `ImagePullBackOff` as there are no docker images available in the  docker repo.

```
Warning  Failed     19s (x2 over 20s)  kubelet            Error: ImagePullBackOff
  Normal   BackOff    19s (x2 over 20s)  kubelet            Back-off pulling image "k8ssandra/cass-management-api:3.11.6"
  Normal   Pulling    4s (x2 over 22s)   kubelet            Pulling image "k8ssandra/cass-management-api:3.11.6"
  Warning  Failed     3s (x2 over 21s)   kubelet            Failed to pull image "k8ssandra/cass-management-api:3.11.6": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/k8ssandra/cass-management-api:3.11.6": failed to resolve reference "docker.io/k8ssandra/cass-management-api:3.11.6": docker.io/k8ssandra/cass-management-api:3.11.6: not found
```

**Expected behavior**
We should either correct the documentation or make the operator works with the supported versions listed in the docs 

**Environment (please complete the following information):**

* Helm charts version info

k8ssandra-operator-0.37.0 `(app version: 1.0.0)`

    NAME              	NAMESPACE         	REVISION	UPDATED                                	STATUS  	CHART                    	APP VERSION
    k8ssandra-operator	k8ssandra-operator	2       	2022-02-28 05:38:28.792202062 +0000 UTC	deployed	```* Kubernetes version information:

`kubectl version`  : `v1.22.7`
* Kubernetes cluster kind:
Self hosted.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1323) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1323
┆priority: Medium

**Comment by jsanda** [comment]
Hi @prasus 

Can you share your K8ssandraCluster manifest? You mentioned trying 3.11.7 but the `ImagePullBackOff` error indicates you were trying to pull a 3.11.6 image. 3.11.7 is indeed the earliest supported version.

For K8ssandra Operator, there is no default version. You have to explicitly set the version.

The k8ssandra Helm chart (not the operator) does set a default version. That default currently is 4.0.1.

**Comment by prasus** [comment]
Thanks for the response, @jsanda 🙏🏿 

Please find the manifest furnished below,

```
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: cassandra
spec:
  auth: false
  reaper:
    autoScheduling:
     enabled: true
    uiUserSecretRef: 
     name: reaper-secret
  medusa:
   storageProperties:
      storageProvider: s3_compatible
      host: nas2.dus5.jaumo.com
      port: 9000
      secure: False
      storageSecretRef: 
        name: medusa-secret
      bucketName: k8ssandra-medusa
  cassandra:
    serverVersion: "3.11.7"
    telemetry:
      prometheus:
        enabled: true
    racks:
    - name: "rack1"
      nodeAffinityLabels:
        operations.infra.com/power-distribution-unit: "PDU1"
    - name: "rack2"
      nodeAffinityLabels:
        operations.infra.com/power-distribution-unit: "PDU2"
    - name: "rack3"
      nodeAffinityLabels:
        operations.infra.com/power-distribution-unit: "PDU3"
    datacenters:
      - metadata:
          name: jaam
        size: 3
        storageConfig:
          cassandraDataVolumeClaimSpec:
            storageClassName: local-ssd
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
        config:
          jvmOptions:
            heapSize: 512M
```

This manifest fails to provision  the `StatefulSet` objects, leaving the below messages in the operator pod logs.

```
kubectl -n k8ssandra-operator logs k8ssandra-operator-6b94bc6c8-kc2r7 --since=2m | tail
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/internal/controller/controller.go:311
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/internal/controller/controller.go:227
2022-03-14T02:11:19.741Z	INFO	controller.k8ssandracluster	updated k8ssandracluster status	{"reconciler group": "k8ssandra.io", "reconciler kind": "K8ssandraCluster", "name": "cassandra", "namespace": "default", "K8ssandraCluster": "default/cassandra"}
2022-03-14T02:11:19.741Z	ERROR	controller.k8ssandracluster	Reconciler error	{"reconciler group": "k8ssandra.io", "reconciler kind": "K8ssandraCluster", "name": "cassandra", "namespace": "default", "error": "CassandraDatacenter.cassandra.datastax.com \"jaam\" is invalid: spec.serverVersion: Unsupported value: \"3.11.7\": supported values: \"6.8.0\", \"3.11.6\", \"4.0.0\""}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/internal/controller/controller.go:227
```

**Comment by jsanda** [comment]
By any chance do you have another cass-operator instance installed in the namespace?

**Comment by prasus** [comment]
No, It is a fresh installation and nothing else is running on the `k8ssandra-cluster` namespace, it was created as part of helm deployment as I have used the `--create-namespace` flag of helm install, Thanks! 

```
$ kubectl -n k8ssandra-operator get pods
NAME                                                READY   STATUS    RESTARTS   AGE
k8ssandra-operator-6b94bc6c8-kc2r7                  1/1     Running   0          9d
k8ssandra-operator-cass-operator-7b85b55c9c-cvzgm   1/1     Running   0          9d
pkr@node1:~/k8ssandra-operator$ helm -n k8ssandra-operator ls
NAME              	NAMESPACE         	REVISION	UPDATED                                	STATUS  	CHART                    	APP VERSION
k8ssandra-operator	k8ssandra-operator	2       	2022-02-28 05:38:28.792202062 +0000 UTC	deployed	k8ssandra-operator-0.37.0	1.0.0      
pkr@node1:~/k8ssandra-operator$ 
```

**Comment by jsanda** [comment]
I deployed a simplified version of your manifest:

```
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: test
spec:
  auth: false
  cassandra:
    serverVersion: "3.11.7"
    datacenters:
      - metadata:
          name: jaam
        size: 1
        storageConfig:
          cassandraDataVolumeClaimSpec:
            storageClassName: standard
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
        config:
          jvmOptions:
            heapSize: 512M
```
Cassandra pod was coming up fine.

This part of your log, `Unsupported value: \"3.11.7\": supported values: \"6.8.0\", \"3.11.6\", \"4.0.0\"`, make me think you might have another, older version of cass-operator already running in the `default` namespace. k8ssandra-operator deploys cass-operator so if another version is running, that would cause problems.

**Comment by jsanda** [comment]
The logs indicate that the K8ssandraCluster and CassandraDatacenter were created in the `default` namespace,

`2022-03-14T02:11:19.741Z	ERROR	controller.k8ssandracluster	Reconciler error	{"reconciler group": "k8ssandra.io", "reconciler kind": "K8ssandraCluster", "name": "cassandra", "namespace": "default", ...` Maybe that is the problem. 

Do you have another cass-operator installed in the `default` namespace?

**Comment by prasus** [comment]
Weird.. there are no other `cass-operator` deployment in the `default` namespace. The operator is deployed in the `k8ssandra-operator` namespace and I am attempting to deploy a `K8ssandraCluster` named `cassandra` to the `default` namespace. The same manifest works fine if I change the ` serverVersion: "3.11.7"` to ` serverVersion: "4.0.0" 😕 

`cluster manifest.`

```
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: cassandra
spec:
  auth: false
  reaper:
    autoScheduling:
     enabled: true
    uiUserSecretRef: 
     name: reaper-secret
  medusa:
   storageProperties:
      storageProvider: s3_compatible
      host: nas2.dus5.infra.com
      port: 9000
      secure: False
      storageSecretRef: 
        name: medusa-secret
      bucketName: k8ssandra-medusa
  cassandra:
    serverVersion: "3.11.7"
    telemetry:
      prometheus:
        enabled: true
    racks:
    - name: "rack1"
      nodeAffinityLabels:
        operations.infra.com/power-distribution-unit: "PDU1"
    - name: "rack2"
      nodeAffinityLabels:
        operations.infra.com/power-distribution-unit: "PDU2"
    - name: "rack3"
      nodeAffinityLabels:
        operations.infra.com/power-distribution-unit: "PDU3"
    datacenters:
      - metadata:
          name: dc101
        size: 3
        storageConfig:
          cassandraDataVolumeClaimSpec:
            storageClassName: local-ssd
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
        config:
          jvmOptions:
            heapSize: 512M
```
