### ISSUE TITLE
Java garbage collection properties are not configurable for Cassandra 4.x

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra#1353]
## Bug Report

**Describe the bug**
I deployed K8ssandra with Cassandra 4.0.0 and 4.0.3. I tried configured garbage collection settings. None of the properties that I configured in the chart properties were configured in the Cassandra pod. This was initially reported in #1269. I found that the problem is not specific to a single property but rather how [cass-config-definitions](https://github.com/datastax/cass-config-definitions) handles JVM properties for Cassandra 4.x.

The k8ssandra chart configures jvm-server.options when deploying Cassandra 4.x. cass-config-definitions configure GC properties in jvm11-server.options and jvm8-server.options for Java 11 and Java 8 respectively. Moreover it appears that cass-config-definitions only makes G1 configurable for Java 11. That might be fine, but it should be documented in the event someone tries to use a different collector.

**To Reproduce**
Install the k8ssandra chart with the following chart properties:

```yaml
cassandra:
  version: 4.0.0
  heap:
    size: 512M
  datacenters:
  - name: dc1
    size: 1
    gc:
      g1:
        enabled: true
        maxGcPauseMillis: 200
        parallelGcThreads: 16
        concurrentGcThreads: 16
stargate:
  enabled: false
reaper:
  enabled: false
kube-prometheus-stack:
  enabled: false
```
Once the Cassandra pod becomes ready check the jvm-server.options and jvm11-server.options config files with this:

`kubectl exec -it <cassandra-pod> -c cassandra -- cat /etc/cassandra/jvm-server.options`

and 

`kubectl exec -it <cassandra-pod> -c cassandra -- cat /etc/cassandra/jvm11-server.options`

The G1 properties will have their default values.

**Expected behavior**
GC propertites should be set based on the chart properties.

**Screenshots**

**Environment (please complete the following information):**

* Helm charts version info

`1.4.1`

**Comment by adutra** [comment]
I have some bad news. I installed K8ssandra with the above values.

Generated cass-config-builder configuration:

```json
{
  "cassandra-yaml": {
    ...
  },
  "cluster-info": {
    "name": "k8ssandra",
    "seeds": "k8ssandra-seed-service,k8ssandra-dc1-additional-seed-service"
  },
  "datacenter-info": {
    ...
  },
  "jvm-server-options": {
    "additional-jvm-opts": [
      "-Dcassandra.system_distributed_replication_dc_names=dc1",
      "-Dcassandra.system_distributed_replication_per_dc=1",
      "-Dcassandra.allow_alter_rf_during_range_movement=true"
    ],
    "conc_gc_threads": 16,
    "garbage_collector": "G1",
    "initial_heap_size": "512M",
    "max_gc_pause_millis": 200,
    "max_heap_size": "512M",
    "parallel_gc_threads": 16
  }
}
```

We can notice that 4 properties are invalid for the key `jvm-server-options`:

* `conc_gc_threads`
* `garbage_collector`
* `max_gc_pause_millis`
* `parallel_gc_threads`

So not only they weren't applied, but they generated garbage in `jvm.options` – see their values below printed with no flag associated to them:

```
...
16
-XX:+DebugNonSafepoints
-ea
G1
-XX:GuaranteedSafepointInterval=300000
-XX:+HeapDumpOnOutOfMemoryError
-Xms512M
-Dio.netty.eventLoop.maxPendingTasks=65536
-Djava.net.preferIPv4Stack=true
-Djdk.nio.maxCachedBufferSize=1048576
200
-Xmx512M
-Dsun.nio.PageAlignDirectMemory=true
16
...
-Dcassandra.system_distributed_replication_dc_names=dc1
-Dcassandra.system_distributed_replication_per_dc=1
-Dcassandra.allow_alter_rf_during_range_movement=true
```

These 4 keys should go under `jvm-options` for Cassandra 3 and under `jvm11-server-options` for Cassandra 4. I will try CMS next.

**Comment by adutra** [comment]
So it seems CMS is just unusable.

I installed k8ssandra with the below values:

```yaml
cassandra:
  version: 4.0.0
  heap:
    size: 512M
  datacenters:
    - name: dc1
      size: 1
      gc:
        cms:
          enabled: true
          survivorRatio: 4
          maxTenuringThreshold: 1
          initiatingOccupancyFraction: 66
          waitDuration: 15000
stargate:
  enabled: false
reaper:
  enabled: false
kube-prometheus-stack:
  enabled: false
```

Generated cass-config builder config:

```json
{
  "cassandra-yaml": {
    ...
  },
  "cluster-info": {
    "name": "k8ssandra",
    "seeds": "k8ssandra-seed-service,k8ssandra-dc1-additional-seed-service"
  },
  "datacenter-info": {
    ...
  },
  "jvm-server-options": {
    "additional-jvm-opts": [
      "-Dcassandra.system_distributed_replication_dc_names=dc1",
      "-Dcassandra.system_distributed_replication_per_dc=1",
      "-Dcassandra.allow_alter_rf_during_range_movement=true"
    ],
    "cms_initiating_occupancy_fraction": 66,
    "cms_wait_duration": 15000,
    "garbage_collector": "CMS",
    "initial_heap_size": "512M",
    "max_heap_size": "512M",
    "max_tenuring_threshold": 1,
    "survivor_ratio": 4
  }
}
```

Again the values are under the wrong key and produce garbage in `jvm-server.options`:

```
66
15000
-XX:+DebugNonSafepoints
-ea
CMS
-XX:GuaranteedSafepointInterval=300000
-XX:+HeapDumpOnOutOfMemoryError
-Xms512M
-Dio.netty.eventLoop.maxPendingTasks=65536
-Djava.net.preferIPv4Stack=true
-Djdk.nio.maxCachedBufferSize=1048576
-Xmx512M
1
-Dsun.nio.PageAlignDirectMemory=true
-Xss256k
-XX:+PerfDisableSharedMem
-XX:+PreserveFramePointer
-Dcassandra.printHeapHistogramOnOutOfMemoryError=false
-XX:+ResizeTLAB
-XX:-RestrictContended
-XX:StringTableSize=1000003
4
```

As a consequence, Cassandra is using G1:

```
INFO  [main] 2022-03-15 15:22:03,935 CassandraDaemon.java:636 - G1 Eden Space Heap memory: init = 41943040(40960K) used = 191889408(187392K) committed = 336592896(328704K) max = -1(-1K)
INFO  [main] 2022-03-15 15:22:03,935 CassandraDaemon.java:636 - G1 Old Gen Heap memory: init = 494927872(483328K) used = 8663664(8460K) committed = 494927872(483328K) max = 536870912(524288K)
INFO  [main] 2022-03-15 15:22:03,941 CassandraDaemon.java:636 - G1 Survivor Space Heap memory: init = 0(0K) used = 5242880(5120K) committed = 5242880(5120K) max = -1(-1K)
```
