### ISSUE TITLE
K8SSAND-1441 ⁃ Webhook does not deny invalid CR specifications

### ISSUE THREAD

**Issue by kevin85421** [k8ssandra/k8ssandra#1380]
# What did you do?
* I want to deploy Cassandra with Webhook, and thus invalid CR specifications can be denied before the operator receives the custom resource events.

### Step1: Install cert-manager
```
kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.5.3/cert-manager.yaml
```

### Step2: Update webhook-secret.yaml 
* We generated tls.crt and tls.key by converting the testdata files to base64.
* testdata: https://github.com/k8ssandra/cass-operator/tree/15917792ae37b3b6a1e47aa3bd1891d35b375f08/pkg/httphelper/testdata

```
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-webhook
  labels: {{ include "k8ssandra-common.labels" . | indent 4 }}
data:
  tls.crt: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMrekNDQWVPZ0F3SUJBZ0lKQU45VFI3cklRbXRJTUEwR0NTcUdTSWIzRFFFQkRRVUFNQk14RVRBUEJnTlYKQkFNTUNFMTVVbTl2ZEVOQk1DQVhEVEU1TVRFd056RTROVE14TTFvWUR6SXhNVGt4TURFME1UZzFNekV6V2pBVApNUkV3RHdZRFZRUUREQWhOZVZKdmIzUkRRVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DCmdnRUJBTHNPaEc5OFNHTS84UktpNHR3QXQ1QkthdTdOTlVtM1FtdEJJMWtOMjloSktHNGRNQ3hyOWZ4T2NuN3oKRTJDN2NEQURSa2pJTFE5VWthNy9DM0NNQlF3bGtOQUlxRGE0b1FxL3dXMTJwd0NwemhPYjE4bzY3cDgxSW9kcApuR2Y1Ykl3Qk1UNzVPM0hZV3dkV1BNV2FNS3FpOFNSUDQrR1dzNU0yL2orTU1CN3RkYUMveFNuOXp0K2o1NkhLCnA2N2xEajJ4WjJlMGpuM2pHUEtaSkx5dXp3WGltMnFKL3c0LzZCRjVSNDVWZVl6YjJ4VGM2bXdKMnVkcllwQXUKVkNKcW96Y3N5S3JjbHNrU3FiZmdLbG9zUytPWVRGWTlaVGg4YjdwU0VnNENoZzlQd20vY0lQUzNxaHVqa0hNKwphLzljbjNIUzQxdzBFSWRJSGVUS2s0NVBheGtDQXdFQUFhTlFNRTR3SFFZRFZSME9CQllFRkZjdndyWThaNmhaClN1NkNKbFgwdkJScHhDc1hNQjhHQTFVZEl3UVlNQmFBRkZjdndyWThaNmhaU3U2Q0psWDB2QlJweENzWE1Bd0cKQTFVZEV3UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRU5CUUFEZ2dFQkFFVXJLaGgvOTNRSDNKUzhHQnZ5ZGhGMApHZUlLZVFnUnRFbmYyK3NSMEc3WEJCY1hsci9kYkFBNW5zMTZRUFBGM250Uk9WdW1sRE9zSm5YK0hpdVo4M2tJCnowWk5JWHh3ZUlHalNGZGt4R3c3bWVDVktBOUJPUDI1c1F6VVNTU0ZWRzdKLzBvNXRIT2g0TEZLS3RPdUd4cUcKYnlZVzVPeXc0WEdNVmtyL1NEUDBSM2czOXB6a3FUVmNhMGZvcVBxMzdLTVg3dTkxQXBaRE9hOHJzeUJhRlMydAovNnNkLzVBYjJuV250Qi9vNDh4N1ZOZWhheGpET3o3SHdXeUxZZ1h4eGRLcWlmVGRKVjR2N1R0RmFTLzg2ODRyCnZoQVBQd01wYW85SHBBRXN1MW5BU0swSnV5VDlaUEkvR2M2WS8zM2FCS0YzOVU1b21kdFdzVWFMSVdWa0RNND0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
  tls.key: "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRQzdEb1J2ZkVoalAvRVMKb3VMY0FMZVFTbXJ1elRWSnQwSnJRU05aRGR2WVNTaHVIVEFzYS9YOFRuSis4eE5ndTNBd0EwWkl5QzBQVkpHdQovd3R3akFVTUpaRFFDS2cydUtFS3Y4RnRkcWNBcWM0VG05ZktPdTZmTlNLSGFaeG4rV3lNQVRFKytUdHgyRnNIClZqekZtakNxb3ZFa1QrUGhsck9UTnY0L2pEQWU3WFdndjhVcC9jN2ZvK2VoeXFldTVRNDlzV2RudEk1OTR4ankKbVNTOHJzOEY0cHRxaWY4T1ArZ1JlVWVPVlhtTTI5c1UzT3BzQ2RybmEyS1FMbFFpYXFNM0xNaXEzSmJKRXFtMwo0Q3BhTEV2am1FeFdQV1U0ZkcrNlVoSU9Bb1lQVDhKdjNDRDB0Nm9ibzVCelBtdi9YSjl4MHVOY05CQ0hTQjNrCnlwT09UMnNaQWdNQkFBRUNnZ0VCQUplVUxRZDJpK1k1WTIzNXBxSW14cGxiWkltOHFvamd3eWJNc3dzd0tzMTYKZ3hPdi9XQ1IzOVNqOFM0a1piaUdTMlBzMDJDWkxjSjFnbFJ2Z21LaVpGaXlmRVhJTGgraHY0WkpXMElMMjBxegpUelllbkYvWkg1TE42UHdZUGRFWGtybGxJZlhvMngzbTkrVGJJZ1h5YTZ0cXZNUHpKVE9oL2tTMlZKTkVVNTVLCjQxNUdzUjVqbW5saHBKdXB6VU5qT3JvdmxZdDdDTEdaZDZWMkdJSGFjY0tWZmdPNmNpR3Y0MlMzUUJqb1lQOXUKUmkwOFVCY0t0dy9IRW5zbVdOdC91RC9PSjFPRnBKdVNYZFNIT0ZMNDlXNGVNWmE4eWFNREl5NUhqMVRWZk9KbAprRlNTQ0ZEZm1DYi9wYzlSaEZFMEFQZWJSeGhKbXBrd0FOcFJZcHN5ZkRFQ2dZRUE5alREc2phYTVwdmZmWjQzCmwyM3I4c2JYa0NsemNVZmZ0SEtSUnBPWm5vZFRDNXRhYlloWnBocFlTdHZuTkxFWXB4SzZpcFUweERNL0FncS8KQ3JOMHo4eDVtYzgzOU82L3FacUZIeFdRRGlIL2JIcjRMM3EzeW5yZWJmSUVrZGdLNmpici9jc0xBQ2gwSDJkSwo3aTZUMXd3cm4xcUpLUEcrZ2ZCVFhDSGpWelVDZ1lFQXduOW43MFl0MWEvT3ZWV0dhM2N2dG40elhPQWxoOVlnCjl3TndDSUR0R3JoaGhnU1ZxVjFJUE9hbEJUTVRxTWhaWnAyb3ZQdXd4cE5uT284ZXJkdlhpa1lDYmtOVXpncDUKMDhsSUpNcVpMdUZEdWpDWE13T00xOHhJV2JRbFViV08wMUw5cU1iVG5PL0pzVHN4NG1mSFhDVmQyTUlkdTdnUApDZ3c5TVdvWDdOVUNnWUFrVERjbHlRTWhTSTIwZVdUOHdFbnU2djNRMVN1ZDRkakxRN0REVlBOcStjeDJnNXJiClZ5VFFaa1hxRTIyTXlTYzNTbjJSL05sZ3E2VjRhWmtzdkxSV0JuRlBDY3ZZSW5MRFVIS2IySlA2WVd6RTA0UlAKaTZvWkFmQlZDVDgvT1RpeXV4SWp3cEdHbm5Bd1NRdzAvVXp5Z1dyVS9ZWUhNVXpDMzJtS3hidzhtUUtCZ1FDaApDNCtLdndoS3JIUzVydXhMWlhmYldxbTYyRm9iSElGVkpzS0lPQUNicEZvVDl3M1pHOFVwc0N5cG5uNUR2Z2pRCmYvRHM4bGFRUmhNdW1MemxabWdWTlJ6a0lkcEJkTWtsUkwvNHZzeVIxYklYcEE0K0RrMTdqY25HaFBSMXNLaWYKY0ZOYWdhOU1mZnY2UlRKcjdsUlRoeGtxMXFoNSs5QndHR3crMDBNV05RS0JnQnY3VWRaYUVrdElBeFBKZnpucQpWVFRFRS8raHRFSVZnTUVTRW5aWnZIQlhJK09pZXNCMlg4cEVaQkJyejNxMTlncGMyaGhKd3JwdzFxVW1pVHpXCktzMXBJSW1Bd29qeVUweUZHd0txdGJsVU1lS3U4cHhnaWVZWXBHYkswVmdWMjhBQldQdjdvMDZSdWxBK1k0blIKMStQMlpJeUhoa3E0UlNacVpLTllWQVVOCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K"
```

### Step3: Update values.yaml
```
admissionWebhooks.enabled: true  
```

### Step5: Install operator
```
helm install cass-operator cass-operator
```

### Step6: Check operator log
* The log indicates that the webhook is launched successfully.

```
kubectl logs ${operator_pod} 
```

### Step7: Use some custom resource specifications to test the webhook.
* webhook tests: https://github.com/k8ssandra/cass-operator/blob/master/tests/webhook_validation/webhook_validation_suite_test.go
* The following CR spec should be denied by the webhook because the number of racks (3) is more than the number of size (1). However, it did not.

```
 apiVersion: cassandra.datastax.com/v1beta1
 kind: CassandraDatacenter
 metadata:
   name: cassandra-datacenter
 spec:
   clusterName: cluster1
   config:
     cassandra-yaml:
       authenticator: org.apache.cassandra.auth.PasswordAuthenticator
       authorizer: org.apache.cassandra.auth.CassandraAuthorizer
       role_manager: org.apache.cassandra.auth.CassandraRoleManager
     jvm-options:
       initial_heap_size: 800M
       max_heap_size: 800M
   managementApiAuth:
     insecure: {}
   serverType: cassandra
   serverVersion: 3.11.7
   size: 1
   racks:
   - name: "r1"
   - name: "r2"
   - name: "r3"
   storageConfig:
     cassandraDataVolumeClaimSpec:
       accessModes:
       - ReadWriteOnce
       resources:
         requests:
           storage: 3Gi
       selector:
         matchExpressions:
         - key: qvcldwgddm
           operator: plaxmaaocg
           values:
           - xaglfuesig
         matchLabels:
           lzgmt: sajacaletx
       storageClassName: server-storage
```

# Did you expect to see some different?
In Step7, I expected the invalid specification will be denied by Webhook, but it did not. The CR spec is invalid because the number of racks (3) is more than the number of size (1). However, it did not.

# Environment
* Cass Operator version:

    `docker.io/k8ssandra/cass-operator:v1.9.0`
    
    * Kubernetes version information:

    ```
    Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:11:29Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
    Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:25:06Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
    ```
    * Kubernetes cluster kind:

```
minikube start --vm-driver=docker --cpus 4 --memory 4096 --kubernetes-version v1.21.0
```

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1441) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1441
┆priority: Medium

**Comment by burmanm** [comment]
I assume with the helm install you used the helm charts under k8ssandra/cass-operator and version 1.4?

**Comment by kevin85421** [comment]
Hi @burmanm, thank you for your reply! To clarify my instructions, I updated my helm chart to the latest commit in https://github.com/k8ssandra/k8ssandra/tree/main/charts/cass-operator (Version: 0.35.0, AppVersion: 1.10.0).

The behavior mentioned in Step7 can still be reproduced after I updated the chart version.

Thank you!

**Comment by kevin85421** [comment]
Hi @burmanm, I tried to deploy the cass-operator by Kustomize, and the webhook works.

```sh
# Step1: Install cert-manager
kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.7.1/cert-manager.yaml

# Step2: Install CRD
# https://github.com/k8ssandra/k8ssandra/blob/main/charts/cass-operator/crds/cassandradatacenter.yaml
kubectl apply -f customresourcedefinition.yaml

# Step3: Install operator
kubectl apply -k github.com/k8ssandra/cass-operator/config/deployments/cluster

# Step4: Pass invalid CR spec
kubectl apply -f cr1_spec.yaml
kubectl apply -f cr2_spec.yaml # modify clusterName => should be denied

# Step5: cr2_spec.yaml is denied by webhook as shown in the following figure.

```



# cr1_spec.yaml
```
 apiVersion: cassandra.datastax.com/v1beta1
 kind: CassandraDatacenter
 metadata:
   name: cassandra-datacenter
 spec:
   clusterName: cluster1
   config:
     cassandra-yaml:
       authenticator: org.apache.cassandra.auth.PasswordAuthenticator
       authorizer: org.apache.cassandra.auth.CassandraAuthorizer
       role_manager: org.apache.cassandra.auth.CassandraRoleManager
     jvm-options:
       initial_heap_size: 800M
       max_heap_size: 800M
   managementApiAuth:
     insecure: {}
   serverType: cassandra
   serverVersion: 3.11.7
   size: 1
   storageConfig:
     cassandraDataVolumeClaimSpec:
       accessModes:
       - ReadWriteOnce
       resources:
         requests:
           storage: 3Gi
       storageClassName: server-storage
```

# cr2_spec.yaml
```
 apiVersion: cassandra.datastax.com/v1beta1
 kind: CassandraDatacenter
 metadata:
   name: cassandra-datacenter
 spec:
   clusterName: cluster2
   config:
     cassandra-yaml:
       authenticator: org.apache.cassandra.auth.PasswordAuthenticator
       authorizer: org.apache.cassandra.auth.CassandraAuthorizer
       role_manager: org.apache.cassandra.auth.CassandraRoleManager
     jvm-options:
       initial_heap_size: 800M
       max_heap_size: 800M
   managementApiAuth:
     insecure: {}
   serverType: cassandra
   serverVersion: 3.11.7
   size: 1
   storageConfig:
     cassandraDataVolumeClaimSpec:
       accessModes:
       - ReadWriteOnce
       resources:
         requests:
           storage: 3Gi
       storageClassName: server-storage
```

# cr2_spec.yaml is denied by webhook.
![截圖 2022-04-09 下午4 28 45](https://user-images.githubusercontent.com/20109646/162592186-dc5aece7-c62b-4eab-a2de-3b74896b8e60.png)
