### ISSUE TITLE
K8SSAND-1454 ⁃ storageSecret is not referenced correctly

### ISSUE THREAD

**Issue by discostur** [k8ssandra/k8ssandra#1383]
Hi,

if you deploy a k8ssandra cluster with medusa backup enabled via k8ssandra-operator and change the default storageSecret name it is not referenced correctly:

**Helm Values File:**

```
cassandra:
  enabled: true
  version: "4.0.3"
stargate:
  enabled: false
reaper:
  enabled: false
medusa:
  enabled: true
  storage: s3_compatible
  storage_properties:
    host: s3.minio.de
    secure: true
    bucketName: k8ssandra
    storageSecret: medusa-custom-secret
monitoring:
  grafana:
    provision_dashboards: true
  prometheus:
    provision_service_monitors: true
cass-operator:
  enabled: false
reaper-operator:
  enabled: false
kube-prometheus-stack:
  enabled: false
```

As you can see `storageSecret: medusa-bucket-key` is change from default to `storageSecret: medusa-custom-secret`. 

Then pod fails to start because it cannot find the secret with custom name created before. If you template the helm chart you can see that: 

```
337811-          - mountPath: /var/lib/cassandra
337853-            name: server-data
337883-          - name: podinfo
337909-            mountPath: /etc/podinfo
337945:          - name:  medusa-bucket-key
337982-            mountPath: /etc/medusa-secrets
338025-      containers:
338043-      - name: cassandra
338067-        securityContext:
--
340048-            mountPath: /etc/cassandra
340086-          - mountPath: /var/lib/cassandra
340128-            name: server-data
340158-          - mountPath: /etc/medusa-secrets
340201:            name: medusa-bucket-key
340237-      volumes:
340252-      - name: cassandra-config
340283-        emptyDir: {}
340304-      - name: cassandra-metrics-coll-config
--
340673-          items:
340690-            - key: medusa.ini
340720-              path: medusa.ini
340751:      - name:  medusa-bucket-key
340784-        secret:
340800:          secretName: medusa-bucket-key
```

is still referenced with the wrong default name in the k8ssandra pod template. Only the medusa backup config is referenced correctly: 

```
326638-    bucketName = k8ssandra
326673-    host = s3.minio.de
326700-    secure = true
326718:    storageSecret = medusa-custom-secret
326774-    bucket_name = awstest
326800-    key_file = /etc/medusa-secrets/medusa_s3_credentials
```

Regards,
Kilian

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1454) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1454
┆priority: Medium
