### ISSUE TITLE
K8SSAND-1498 ⁃ How to connect to microk8s k8ssandra from different machine

### ISSUE THREAD

**Issue by uchiha-pain** [k8ssandra/k8ssandra#1403]
Hi, I am a new k8ssandra user. I need a bit help with to connect to k8ssandra from external machine.

### My Setup:
I have created 4 Ubuntu virtual machines in Proxmox. 3 machines are to make my microk8s cluster highly-available and the 4th machine is to install my software.
I have installed k8ssandra separately on each of the 3 nodes using [guide1](https://docs-v1.k8ssandra.io/install/local/), [guide2](https://k8ssandra.io/blog/tutorials/how-to/multi-region-cassandra-on-eks-with-k8ssandra-and-kubefed/), and [guide3](https://medium.com/building-the-open-data-stack/deploy-a-multi-datacenter-apache-cassandra-cluster-in-kubernetes-cfd668629974).

### What i have done:
I formed a highly available microk8s cluster using three different Ubuntu VMs with the help of command
`microk8s add-node`
The status of my cluster is

    `microk8s is running`
    `datastore master nodes: 192.168.0.10:19001 192.168.0.56:19001 192.168.0.199:19001`
    `  datastore standby nodes: none`
    `addons:`
      `enabled:`
        `dns                  # CoreDNS`
        `ha-cluster           # Configure high availability on the current node`
        `helm3                # Helm 3 - Kubernetes package manager`
        `storage              # Storage class; allocates storage from host directory`
        `traefik              # traefik Ingress controller for external access`
      `disabled:`
        `ambassador           # Ambassador API Gateway and Ingress`
        `cilium               # SDN, fast with full network policy`
       ` dashboard            # The Kubernetes dashboard`
        `dashboard-ingress    # Ingress definition for Kubernetes dashboard`
       `fluentd              # Elasticsearch-Fluentd-Kibana logging and monitoring`
       gpu                  # Automatic enablement of Nvidia CUDA`
       helm                 # Helm 2 - the package manager for Kubernetes`
       host-access          # Allow Pods connecting to Host services smoothly`
       inaccel              # Simplifying FPGA management in Kubernetes`
       ingress              # Ingress controller for external access`
       istio                # Core Istio service mesh services`
       jaeger               # Kubernetes Jaeger operator with its simple config`
       kata                 # Kata Containers is a secure runtime with lightweight VMS`
       keda                 # Kubernetes-based Event Driven Autoscaling`
       knative              # The Knative framework on Kubernetes.`
       kubeflow             # Kubeflow for easy ML deployments`
       linkerd              # Linkerd is a service mesh for Kubernetes and other frameworks`
       metallb              # Loadbalancer for your Kubernetes cluster`
       metrics-server       # K8s Metrics Server for API access to service metrics`
       multus               # Multus CNI enables attaching multiple network interfaces to pods`
      openebs              # OpenEBS is the open-source storage solution for Kubernetes`
       openfaas             # OpenFaaS serverless framework`
      portainer            # Portainer UI for your Kubernetes cluster`
       prometheus           # Prometheus operator for monitoring and logging`
        rbac                 # Role-Based Access Control for authorisation`
        registry             # Private image registry exposed on localhost:32000`After creating cluster I installed k8ssandra separately on each of the three nodes.
First, I created three different namesspaces and secrets on each of the nodes
`microk8s kubectl create namespace cassandra-1`
`microk8s kubectl create secret generic cassandra-admin-secret --from-literal=username=cassandra-admin --from-literal=password=cassandra-admin-password -n cassandra-1`
Then installed k8ssandra in this namespace
`microk8s helm3 install -f k8ssandra.yaml k8ssandra-1 k8ssandra/k8ssandra -n cassandra-1`
Below is my k8ssandra.yaml

```
cassandra:
   version: "4.0.1"
   auth:
    superuser:
        secret: cassandra-admin-secret
   cassandraLibDirVolume:
      storageClass: local-path
      size: 5Gi
   allowMultipleNodesPerWorker: true
   heap:
      size: 1G
      newGenSize: 1G
   resources:
      requests:
        cpu: 700m
        memory: 2Gi
      limits:
        cpu: 1000m
        memory: 10Gi
   clusterName: microk8s-cluster
   datacenters:
   - name: dc1
     size: 1
     racks:
     - name: rack
stargate:
  enabled: true
  replicas: 1
  heapMB: 256
  cpuReqMillicores: 200
  cpuLimMillicores: 1000

```

I got the seeds with below command
`microk8s kubectl get pods -n cassandra-1 -o jsonpath="{.items[*].status.podIP}" --selector cassandra.datastax.com/seed-node=true`
Added the seeds in other two k8ssandra installations 

```
cassandra:
   version: "4.0.1"

   auth:
    superuser:
        secret: cassandra-admin-secret
   additionalSeeds: [ 10.1.202.9 ]
   cassandraLibDirVolume:
      storageClass: local-path
      size: 5Gi

   allowMultipleNodesPerWorker: true
   heap:
      size: 1G
      newGenSize: 1G
   resources:
      requests:
        cpu: 700m
        memory: 2Gi
      limits:
        cpu: 1000m
        memory: 10Gi

   clusterName: microk8s-cluster

   datacenters:
   - name: dc2
     size: 1
     racks:
     - name: rack

stargate:
  enabled: true
  replicas: 1
  heapMB: 256
  cpuReqMillicores: 200
  cpuLimMillicores: 1000
```

My 3rd k8ssandra installation

```
cassandra:
   version: "4.0.1"

   auth:
    superuser:
        secret: cassandra-admin-secret
   additionalSeeds: [ 10.1.202.9 ]
   cassandraLibDirVolume:
      storageClass: local-path
      size: 5Gi

   allowMultipleNodesPerWorker: true
   heap:
      size: 1G
      newGenSize: 1G
   resources:
      requests:
        cpu: 700m
        memory: 2Gi
      limits:
        cpu: 1000m
        memory: 10Gi

   clusterName: microk8s-cluster

   datacenters:
   - name: dc3
     size: 1
     racks:
     - name: rack

stargate:
  enabled: false
  replicas: 1
  heapMB: 512
  cpuReqMillicores: 200
  cpuLimMillicores: 1000

```

This installation is working fine

```

itachi@itachi-server:~$ microk8s kubectl -n cassandra-1 exec -it microk8s-cluster-dc1-rack-sts-0 -c cassandra -- nodetool -u cassandra-admin -pw cassandra-admin-password status
Datacenter: dc1
===============
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address     Load        Tokens  Owns  Host ID                               Rack
UN  10.1.202.9  385.63 KiB  16      ?     5f1c021c-4fa2-40d1-ae57-796c05f4dd85  rack

Datacenter: dc2
===============
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address     Load        Tokens  Owns  Host ID                               Rack
UN  10.1.78.15  235.9 KiB   16      ?     35825370-fe31-4e22-bac0-5dbc76bb965f  rack

Datacenter: dc3
===============
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address     Load        Tokens  Owns  Host ID                               Rack
UN  10.1.8.220  241.12 KiB  16      ?     b362f8e0-95ce-4b0f-b057-a772dd371aaa  rack

Note: Non-system keyspaces don't have the same replication settings, effective ownership information is meaningless
```

### What i want
Now, I have installed my software in 4th machine and trying to connect to k8ssandra from that node. I am not able to connect to k8ssandra from that node. There are many things confusing me. First thing is this
`The provided Traefik ingress solutions are not recommended for production environments. As an alternative, consider port forwarding. It’s another way to provide external access to resources that have been deployed by K8ssandra in your Kubernetes environment. The kubectl port-forward command does not require an Ingress/Traefik to work.`
I have done port-forwarding but I am still not able to connect to k8ssandra to any of the port. I have installed cqlsh standalone tool and used command 
`./cqlsh.py 192.168.0.10 9042 -u cassandra-admin -p cassandra-admin-password`
`./cqlsh.py 192.168.0.10 8080 -u cassandra-admin -p cassandra-admin-password`
`./cqlsh.py 10.152.183.1 8080 -u cassandra-admin -p cassandra-admin-password`
Neither of these command is able to connect me to k8ssandra.
The second confusing thing is traefik. There are 2 provided traefik, one is provided by k8ssandra and the second is provided by microk8s. The microk8s traefik documentation is horrible to understand.

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: http-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: some-service
          servicePort: 80
```

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-tcp-microk8s-conf
  namespace: ingress
data:
  6379: "default/redis:6379"
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-ingress-microk8s-controller
  namespace: ingress
spec:
  template:
    spec:
      containers:
      - name: nginx-ingress-microk8s
        ports:
        - containerPort: 80
        - containerPort: 443
        - name: proxied-tcp-6379
          containerPort: 6379
          hostPort: 6379
          protocol: TCP
```

Nothing is explained what is happening and how it is happening. It is just going above my head.
I don't know how to connect to my k8ssandra database from different node. Please help me.

Thanks
Uchiha Itachi

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1498) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1498
┆priority: Medium
