### ISSUE TITLE
K8SSAND-1504 ⁃ The state of the cassandra pods in second data center is always unhealthy. 

### ISSUE THREAD

**Issue by mpaulgreen** [k8ssandra/k8ssandra#1405]
## Bug Report

**Describe the bug**
I am having one dc in one ns and second dc is second ns. The cassandra pods of 1st DC comes up fine. The cassandra pods of 2nd dc is always unhealthy. This is on OpenShift cluster built on AWS.

**To Reproduce**

* Steps to reproduce the behavior:

```

oc apply -f storageclass.yaml

// first cluster

oc new-project txndc
oc adm policy add-scc-to-group anyuid system:serviceaccounts:txndc
oc adm policy add-scc-to-group cluster-admin system:serviceaccounts:txndc // This has been used to debug the error
oc create secret generic cassandra-admin-secret --from-literal=username=cassandra-admin --from-literal=password=cassandra-admin-password -n txndc
helm install txndc k8ssandra/k8ssandra -f dc1.yaml -n txndc  
kubectl exec mixed-workload-dc1-rack1-sts-0 -n txndc -- nodetool --username cassandra-admin --password cassandra-admin-password status
oc apply -f mgmt-route.yaml
oc apply -f native-route.yaml

// second cluster

oc new-project analyticsdc
oc adm policy add-scc-to-group cluster-admin system:serviceaccounts:analyticsdc // This has been used to debug the error
oc create secret generic cassandra-admin-secret --from-literal=username=cassandra-admin --from-literal=password=cassandra-admin-password -n analyticsdc
helm install analyticsdc k8ssandra/k8ssandra -f dc2.yaml -n analyticsdc
```

* dc1.yaml

```
cassandra:
  version: "4.0.1"
  auth:
    superuser: 
      secret: cassandra-admin-secret
  cassandraLibDirVolume:
    storageClass: standard-rwo
  clusterName: mixed-workload
  heap:
    size: 8G
    newGenSize: 1G
  datacenters:
    - name: dc1
      size: 3
      racks:
        - name: rack1
          affinityLabels:
            failure-domain.beta.kubernetes.io/zone: ca-central-1a
        - name: rack2
          affinityLabels:
            failure-domain.beta.kubernetes.io/zone: ca-central-1b
        - name: rack3
          affinityLabels:
            failure-domain.beta.kubernetes.io/zone: ca-central-1d
```

* dc2.yaml

```
cassandra:
  version: "4.0.1"
  additionalSeeds: [mixed-workload-seed-service-mgmt-txndc.apps.mpkongdemo.51ty.p1.openshiftapps.com, mixed-workload-seed-service-native-txndc.apps.mpkongdemo.51ty.p1.openshiftapps.com]
  auth:
    superuser: 
      secret: cassandra-admin-secret
  cassandraLibDirVolume:
    storageClass: standard-rwo
  clusterName: mixed-workload
  datacenters:
    - name: dc2
      heap: 
        newGenSize: 1G
        size: 8G
      size: 3
      racks:
        - name: rack1
          affinityLabels:
            failure-domain.beta.kubernetes.io/zone: ca-central-1b
        - name: rack2
          affinityLabels:
            failure-domain.beta.kubernetes.io/zone: ca-central-1d
        - name: rack3
          affinityLabels:
            failure-domain.beta.kubernetes.io/zone: ca-central-1a
```

* storage class

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard-rwo
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
```

* native-route.yaml

## ```
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: mixed-workload-seed-service-native
spec:
  port:
    targetPort: native
  to:
    kind: Service
    name: mixed-workload-seed-service

```
- mgmt-route.yaml
```

- - -
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: mixed-workload-seed-service-mgmt
spec:
  port:
    targetPort: mgmt-api
  to:
    kind: Service
    name: mixed-workload-seed-service

```
- pod status of txndc ns
```

NAME                                                  READY   STATUS    RESTARTS   AGE
mixed-workload-dc1-rack1-sts-0                        2/2     Running   0          95m
mixed-workload-dc1-rack2-sts-0                        2/2     Running   0          95m
mixed-workload-dc1-rack3-sts-0                        2/2     Running   0          95m
prometheus-txndc-kube-prometheus-stac-prometheus-0    2/2     Running   0          95m
txndc-cass-operator-6467867659-dnr4z                  1/1     Running   0          95m
txndc-dc1-stargate-6cd9c8fcc9-fzlln                   1/1     Running   0          95m
txndc-grafana-64c8866488-6vznb                        2/2     Running   0          95m
txndc-kube-prometheus-stac-operator-d64b8f85c-6l29p   1/1     Running   0          95m
txndc-reaper-operator-7d95b8fd5b-hjc6w                1/1     Running   0          95m

```

- pod status of analyticsdc
```

NAME                                                   READY   STATUS     RESTARTS   AGE   IP             NODE                                            NOMINATED NODE   READINESS GATES
analyticsdc-cass-operator-f64865ddc-x4fzj              1/1     Running    0          23m   10.131.1.46    ip-10-0-130-187.ca-central-1.compute.internal   <none>           <none>
analyticsdc-dc2-stargate-55b4b87cc4-5thl7              0/1     Init:0/1   0          23m   10.131.1.44    ip-10-0-130-187.ca-central-1.compute.internal   <none>           <none>
analyticsdc-grafana-544f87f4c8-nsnsw                   2/2     Running    0          23m   10.128.2.111   ip-10-0-206-232.ca-central-1.compute.internal   <none>           <none>
analyticsdc-kube-prometheu-operator-7566dccd89-qwkln   1/1     Running    0          23m   10.131.1.45    ip-10-0-130-187.ca-central-1.compute.internal   <none>           <none>
analyticsdc-reaper-operator-569585d48b-qhk44           1/1     Running    1          23m   10.128.2.110   ip-10-0-206-232.ca-central-1.compute.internal   <none>           <none>
mixed-workload-dc2-rack1-sts-0                         1/2     Running    0          22m   10.129.2.61    ip-10-0-188-227.ca-central-1.compute.internal   <none>           <none>
mixed-workload-dc2-rack2-sts-0                         1/2     Running    0          22m   10.128.2.113   ip-10-0-206-232.ca-central-1.compute.internal   <none>           <none>
mixed-workload-dc2-rack3-sts-0                         1/2     Running    0          22m   10.131.1.48    ip-10-0-130-187.ca-central-1.compute.internal   <none>           <none>
prometheus-analyticsdc-kube-prometheu-prometheus-0     2/2     Running    0          23m   10.128.2.112   ip-10-0-206-232.ca-central-1.compute.internal   <none>           <none>

```
- Modified service mixed-workload-seed-service (definition provided that has been modified)
```

spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ipFamilies:
    - IPv4
  ports:
    - name: native
      protocol: TCP
      port: 9042
      targetPort: 9042
    - name: mgmt-api
      protocol: TCP
      port: 8080
      targetPort: 8080
  clusterIPs:
    - None
  type: ClusterIP

    **Expected behavior**
    All 
    
    **Screenshots**
    
    **Environment (please complete the following information):**
    
    * Helm charts version info
    
    
    `$ helm ls -A` NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
analyticsdc     analyticsdc     1               2022-05-11 15:32:11.68789 -0400 EDT     deployed        k8ssandra-1.5.0

txndc           txndc           1               2022-05-11 14:19:59.291781 -0400 EDT    deployed        k8ssandra-1.5.0

    * Helm charts user-supplied values
    
    
    `$ helm get values analyticsdc` USER-SUPPLIED VALUES:
cassandra:
  additionalSeeds:

* mixed-workload-seed-service-mgmt-txndc.apps.mpkongdemo.51ty.p1.openshiftapps.com
* mixed-workload-seed-service-native-txndc.apps.mpkongdemo.51ty.p1.openshiftapps.com
  auth:
    superuser:
      secret: cassandra-admin-secret
  cassandraLibDirVolume:
    storageClass: standard-rwo
  clusterName: mixed-workload
  datacenters:
* heap:
      newGenSize: 1G
      size: 8G
    name: dc2
    racks:
  * affinityLabels:
        failure-domain.beta.kubernetes.io/zone: ca-central-1b
      name: rack1
  * affinityLabels:
        failure-domain.beta.kubernetes.io/zone: ca-central-1d
      name: rack2
  * affinityLabels:
        failure-domain.beta.kubernetes.io/zone: ca-central-1a
      name: rack3
    size: 3
  version: 4.0.1

    
    - `$ helm get values txndc
    
    `USER-SUPPLIED VALUES:
cassandra:
  auth:
    superuser:
      secret: cassandra-admin-secret
  cassandraLibDirVolume:
    storageClass: standard-rwo
  clusterName: mixed-workload
  datacenters:

* name: dc1
    racks:
  * affinityLabels:
        failure-domain.beta.kubernetes.io/zone: ca-central-1a
      name: rack1
  * affinityLabels:
        failure-domain.beta.kubernetes.io/zone: ca-central-1b
      name: rack2
  * affinityLabels:
        failure-domain.beta.kubernetes.io/zone: ca-central-1d
      name: rack3
    size: 3
  version: 4.0.1

    * Kubernetes version information:
    
    `oc version`Client Version: 4.6.19
Server Version: 4.8.0
Kubernetes Version: v1.21.1+f36aa36

```

* Kubernetes cluster kind:
- Cluster Creation - IPI install of OpenShift on AWS.
```

compute:

* architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform:
    aws:
      type: c5.4xlarge
      zones:
  * ca-central-1a
  * ca-central-1b
  * ca-central-1d
  replicas: 3
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform:
    aws:
      zones:
  * ca-central-1a
      rootVolume:
      type: t2.xlarge
  replicas: 3

```

**Additional context**


* The logs are attached here
[mixed-workload-dc2-rack3-sts-0-cassandra.log](https://github.com/k8ssandra/k8ssandra/files/8673084/mixed-workload-dc2-rack3-sts-0-cassandra.log)
[mixed-workload-dc2-rack3-sts-0-server-system-logger.log](https://github.com/k8ssandra/k8ssandra/files/8673085/mixed-workload-dc2-rack3-sts-0-server-system-logger.log)

-



┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1504) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1504
┆priority: Medium

**Comment by jsanda** [comment]
Note this warning from the Cassandra log in dc2:

```
WARN  [main] 2022-05-11 19:36:00,128 K8SeedProvider4x.java:58 - Seed provider couldn't lookup host mixed-workload-seed-service
```
Since the seed service for dc1 is in a different namespace you need to specify it as `mixed-workload-seed-service.txndc`in the `additionalSeeds` property for dc2.

I encourage you to check out [k8ssandra-operator](https://github.com/k8ssandra/k8ssandra-operator). It provides a lot of multi-dc and multi-cluster capabilities. That is where all of the new feature work will be done for k8ssandra.

**Comment by mpaulgreen** [comment]
@jsanda Thanks for replying quickly to this issue. Yes, my initial deployment was with ```mixed-workload-seed-service.txndc```. How ever the operator throws this warning and cassandra pods never comes up.  Here is the error from the operator. ```"reason": "ReconcileFailed", "message": "endpoints \"mixed-workload-dc2-additional-seed-service\" is forbidden: endpoint address 10.131.0.251 is not allowed"}```
[analyticsdc-cass-operator-f64865ddc-clqtb-cass-operator.log](https://github.com/k8ssandra/k8ssandra/files/8673636/analyticsdc-cass-operator-f64865ddc-clqtb-cass-operator.log)
To avoid that I modified the seed service as mentioned above and created routes. After which the pods are coming up but the pods remains in unhealthy state.

**Comment by jsanda** [comment]
I am not very familiar with routes. The problem with endpoints came up in https://github.com/k8ssandra/k8ssandra-operator/issues/510. See this [comment](https://github.com/k8ssandra/k8ssandra-operator/issues/510#issuecomment-1096673380) for a solution.

**Comment by mpaulgreen** [comment]
Hi @jsanda I was able to deploy 2 dc with 3 racks in each by updating roles of the operator. The operator k8ssandra-operator, when deployed using helm charts is restricted to a namespace or it can be clausterwide?

**Comment by jsanda** [comment]
You can deploy with cluster scope. You need to set `global.clusterScoped: true`. See [here](https://github.com/k8ssandra/k8ssandra/blob/main/charts/k8ssandra-operator/values.yaml#L5).

**Comment by mpaulgreen** [comment]
Hi @jsanda The operator now needs IP addresses instead of ```mixed-workload-seed-service.txndc``` in additionalSeeds configuration. The pods are ephermal. Is it a bug with a new operator or do we need to do any additional configuration?

**Comment by jsanda** [comment]
The operator accepts either IPs or hostnames for `additionalSeeds`. 

What do you have `additionalSeeds` set to?

What kind of error are you getting?

**Comment by mpaulgreen** [comment]
This is what I expected. When I used the old version of the operator https://github.com/k8ssandra/k8ssandra then it did resolve the host name ```mixed-workload-seed-service.txndc```. But when I use the new version https://github.com/k8ssandra/k8ssandra-operator, the hostname is not resolved. It's trying to use ```mixed-workload-seed-service.txndc``` as an ip address. I had to use the IP Adresses of the endpoints of headless service. The second DC also takes about 20 min - 30 min to come up from health check errors.

**Comment by jsanda** [comment]
The old version of the operator to which you are referring is cass-operator. cass-operator is by both k8ssandra and k8ssandra-operator. The `addtionalSeeds` property in k8ssandra-operator is a bit different than the one in cass-operator.

Your original comment describe a k8ssandra 1.x cluster. Now you are talking about k8ssandra-operator. What exactly are you running or trying to run :) 

If you are trying to deploy a multi-DC cluster with k8ssandra-operator, you don't need to worry about `additionalSeeds`. It handles it for you. See these api [docs](https://github.com/k8ssandra/k8ssandra-operator/blob/main/apis/k8ssandra/v1alpha1/k8ssandracluster_types.go#L204).

**Comment by mpaulgreen** [comment]
It was very confusing to begin with. I started with this repo https://github.com/k8ssandra/cass-operator and then moved on https://github.com/k8ssandra/k8ssandra and then you pointed to https://github.com/k8ssandra/k8ssandra-operator. Now my earlier deployment was https://github.com/k8ssandra/k8ssandra and new deployment is with k8ssandra-operator. When I used the k8ssandra/k8ssandra, the hostNames were being resolved. So, I was trying to use the example from your previous repo and trying to run it with k8ssandra-operator. Thanks for sending the reference for additionalSeeds. I will try to run it without additionalSeeds. Coming back to second question of mine ```The second DC also takes about 20 min - 30 min to come up from health check errors. Is it normal for second DC to be in healthy state in 20-30 min.```

**Comment by jsanda** [comment]
See https://github.com/k8ssandra/k8ssandra-operator/blob/main/test/testdata/fixtures/multi-dc-cluster-scope/k8ssandra.yaml for an example k8ssandra-operator manifest for a multi-DC deployment within a single k8s cluster. It requires a cluster-scoped deployment. Also check out the docs at https://docs-v2.k8ssandra.io/.

The time it takes for the 2nd DC to become ready largely depends on the number of nodes. 2 to 3 minutes per C* node is pretty common. 20-30 minutes seems long for a 3-node DC.

**Comment by mpaulgreen** [comment]
Thanks @jsanda. It definitely helps. I will give this a try and will observe the time taken by the 2nd cluster

**Comment by mpaulgreen** [comment]
@jsanda I was able to deploy the both the data centers with 3 racks each on 2 openshift cluster. However, when I exec into the pod and check the nodetool status I get the listing for only one data center only. The expected output needs to be for both the data centers. 

The following manifest was applied in Control Plane

```
cat <<EOF | kubectl -n k8ssandra-operator apply -f -
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: demo
spec:
  cassandra:
    serverVersion: "3.11.11"
    storageConfig:
      cassandraDataVolumeClaimSpec:
        storageClassName: standard-rwo
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
    config:
      jvmOptions:
        heapSize: 512M
    networking:
      hostNetwork: false    
    datacenters:
      - metadata:
          name: dc1
        size: 3
        stargate:
          size: 1
          heapSize: 256M
      - metadata:
          name: dc2
        k8sContext: k8smpdp
        size: 3
        stargate:
          size: 1
          heapSize: 256M 
EOF
```

```
kubectl exec demo-dc1-default-sts-0 -n k8ssandra-operator -- nodetool --username demo-superuser --password RNxk00Thh0rfGntNhNob status
```
Output
```
Defaulted container "cassandra" out of: cassandra, server-system-logger, jmx-credentials (init), server-config-init (init)
Datacenter: dc1
===============
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address       Load       Tokens       Owns (effective)  Host ID                               Rack
UN  10.131.0.59   83.07 KiB  256          100.0%            c7d0c045-6669-4eb8-b75b-f6a7f903ed3c  default
UN  10.129.2.108  83.06 KiB  256          100.0%            000964b0-2213-4fa1-8082-2393e7c2ecc1  default
UN  10.128.2.15   102.63 KiB  256          100.0%            e002197c-e994-4cb1-b12f-54eca4d0f511  default
```
I could see both data centers in kind clusters.

I am attaching both the operator logs for CP and DP,

[dp-k8ssandra-operator-cass-operator-7647776896-ppgbr-cass-operator.log](https://github.com/k8ssandra/k8ssandra/files/8712084/dp-k8ssandra-operator-cass-operator-7647776896-ppgbr-cass-operator.log)
[dp-k8ssandra-operator-595f94dc47-gxpcr-k8ssandra-operator.log](https://github.com/k8ssandra/k8ssandra/files/8712085/dp-k8ssandra-operator-595f94dc47-gxpcr-k8ssandra-operator.log)
[cp- k8ssandra-operator-cass-operator-7647776896-55f87-cass-operator.log](https://github.com/k8ssandra/k8ssandra/files/8712086/cp-.k8ssandra-operator-cass-operator-7647776896-55f87-cass-operator.log)
[cp-k8ssandra-operator-57f544b455-9gll9-k8ssandra-operator.log](https://github.com/k8ssandra/k8ssandra/files/8712087/cp-k8ssandra-operator-57f544b455-9gll9-k8ssandra-operator.log)
