### ISSUE TITLE
K8SSAND-1509 ⁃ G1GC not applied on k8ssandra with Cassandra version 3.11.8 

### ISSUE THREAD

**Issue by renoypaulose** [k8ssandra/k8ssandra#1408]
I have K8ssandra cluster with 1.5.0 version and the Cassandra version is 3.11.8. Even though all G1GC related configurations are applied in jvm.options -XX:+UseG1GC is missing.
[jvm.options.txt](https://github.com/k8ssandra/k8ssandra/files/8684770/jvm.options.txt)

When i checked gc.log i saw -XX:+UseParallelGC in CommandLine flags. 

Config property from CassandraDatacenter.

```
config:
    cassandra-yaml:
      authenticator: PasswordAuthenticator
      authorizer: CassandraAuthorizer
      credentials_update_interval_in_ms: 900000
      credentials_validity_in_ms: 900000
      num_tokens: 16
      permissions_update_interval_in_ms: 900000
      permissions_validity_in_ms: 900000
      role_manager: CassandraRoleManager
      roles_update_interval_in_ms: 900000
      roles_validity_in_ms: 900000
    jvm-options:
      additional-jvm-opts:
      - -Dcassandra.system_distributed_replication_dc_names=scass-dc2
      - -Dcassandra.system_distributed_replication_per_dc=3
      - -Dcassandra.allow_alter_rf_during_range_movement=true
      conc_gc_threads: 8
      g1r_set_updating_pause_time_percent: 5
      garbage_collector: G1
      initial_heap_size: 16G
      initiating_heap_occupancy_percent: 20
      max_gc_pause_millis: 250
      max_heap_size: 16G
      parallel_gc_threads: 8
```

As discussed over Discord K8ssandra-community, editing CassandraDatacenter to change garbage_collector to G1GC from G1 fixed the issue.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1509) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1509
┆priority: Medium
