### ISSUE TITLE
K8SSAND-1538 ⁃ Allow Cassandra pods from different clusters to be co-located on the same worker node

### ISSUE THREAD

**Issue by renoypaulose** [k8ssandra/k8ssandra#1422]
**What is missing?**
 To allow Cassandra pods from different clusters to be co-located on the same worker nodes. This cannot be done without a different pod anti-affinity.
**Why do we need it?**
Our application uses different Cassandra clusters (in VMs) for different components within. While migrating to K8ssandra, these clusters have to co-exist in a single Kubernetes cluster. With allowMultipleNodesPerWorker set to false, no two pods can run in the same worker node and kubernetes cluster is not big enough to accommodate all pods from all Cassandra clusters. With allowMultipleNodesPerWorker set to true, there was a situation where all pods of a cluster started running in a single worker node. pods are not distributed.

With the current implementation of K8ssandra, pod anti-affinity is controlled by allowMultipleNodesPerWorker, setting this to false will set below rule in podtemplate.

```
 affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: cassandra.datastax.com/cluster
            operator: Exists
          - key: cassandra.datastax.com/datacenter
            operator: Exists
          - key: cassandra.datastax.com/rack
            operator: Exists
        topologyKey: kubernetes.io/hostname
```

Setting allowMultipleNodesPerWorker to true completely removes this.

With this FR I'm requesting for an option to edit podAntiAffinity rule and give 'IN' instead of 'Exists' with value as cluster name by which we can achieve multiple pods of the different clusters in same worker node.

**Environment**

K8ssandra 1.5
Kubernetes 1.22.6

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1538) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1538
┆priority: Medium
