### ISSUE TITLE
Upgrading k8ssandra-operator can make the cluster unavailable

### ISSUE THREAD

**Issue by mlallaouret** [k8ssandra/k8ssandra#1432]
## Bug Report

**Describe the bug**
I had an issue when doing the k8ssandra-operator chart upgrade from 0.37.1 and 0.37.4. 
After applying the upgrade, it triggers a restart of the cluster. A first node is restarted and once it's up, the second one is restarted and at the same time the first one is again restarted a second time. 
Having 3 nodes, it makes the cassandra cluster unavailable because we are using a replication factor of 3 and local_quorum consistency level.
The issue seems to be linked to reaper being enabled in the chart.
To workaround this issue I had to disable reaper deployment before doing the upgrade and enable it back after.

**To Reproduce**
1. Install k8ssandra-operator chart 0.37.1
2. Install a k8ssandra cluster with reaper enabled
3. Upgrade k8ssandra-operator chart to 0.37.4

**Expected behavior**
The k8ssandra-operator should not be unavailable the upgrade process.

**Environment (please complete the following information):**

* Helm charts version info

Migration from k8ssandra-operator 0.37.1 to 0.37.4

* Helm charts user-supplied values

None

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.10", GitCommit:"eae22ba6238096f5dec1ceb62766e97783f0ba2f", GitTreeState:"clean", BuildDate:"2022-05-24T12:56:35Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.8-gke.201", GitCommit:"2dca91e5224568a093c27d3589aa0a96fd3ddc9a", GitTreeState:"clean", BuildDate:"2022-05-11T18:39:02Z", GoVersion:"go1.16.14b7", Compiler:"gc", Platform:"linux/amd64"}

**Comment by jsanda** [comment]
@mlallaouret Can you share your K8ssandraCluster spec so I can test and try to reproduce?

**Comment by mlallaouret** [comment]
Yes, here it is:
```
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: main-cluster
spec:
  cassandra:
    serverVersion: "3.11.12"
    superuserSecretRef:
      name: k8ssandra-cluster-credentials
    datacenters:
      - metadata:
          name: dc2
        size: 3
        racks:
          - name: rack1
            nodeAffinityLabels:
              type: cassandra
        storageConfig:
          cassandraDataVolumeClaimSpec:
            storageClassName: cassandra-ssd
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 50Gi
        telemetry:
          prometheus:
            enabled: true
    config:
      cassandraYaml:
        authenticator: PasswordAuthenticator
        authorizer: CassandraAuthorizer
        memtable_allocation_type: offheap_objects
        write_request_timeout_in_ms: 5000
      jvmOptions:
        heapSize: 1Gi
    tolerations:
      - key: type
        operator: Equal
        value: cassandra
        effect: NoSchedule
    resources:
      requests:
        cpu: 1.5
        memory: 3Gi
      limits:
        cpu: 1.5
        memory: 3Gi
  medusa:
    storageProperties:
      storageProvider: google_storage
      storageSecretRef:
        name: <key_secret>
      bucketName: <google_bucket>
      prefix: <prefix>
      region: <region>
      secure: true
      maxBackupCount: 10
  reaper:
    autoScheduling:
      enabled: true
      repairType: ADAPTIVE
``` 
For information.
* We use a custom storage class
* We use some configuration to deploy the cluster on a certain node type
* I put placeholder for medusa configuration. But I think you can remove the medusa part as the issue does not seem to come from there (I did not test without it).

**Comment by jsanda** [comment]
I tested the upgrade on a local kind cluster with this K8ssandraCluster:

```yaml
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: test
spec:
  cassandra:
    serverVersion: "3.11.12"
    storageConfig:
      cassandraDataVolumeClaimSpec:
        storageClassName: standard
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
    config:
      jvmOptions:
        heapSize: 1Gi
    networking:
      hostNetwork: true
    datacenters:
      - metadata:
          name: dc1
        size: 3
  reaper: {}
```
The upgrade did trigger a rolling restart of Cassandra. This was due to a couple small configuration changes in the CassandraDatacenter. Here is a screenshot of the differences:

<img width="1287" alt="Screen Shot 2022-06-23 at 11 35 09 PM" src="https://user-images.githubusercontent.com/168121/175457035-d7e41a08-09fa-4f4a-a073-0deba795c4b2.png">

I then observed an update of the Reaper deployment as well. I'm not sure what triggered it.

I didn't run into any problems as reported. Maybe I need to adjust my test.

There is detail from the description I want to mention:

>A first node is restarted and once it's up, the second one is restarted and at the same time the first one is again restarted a second time.

The underlying statefulsets are configured to do rolling updates and use a pod management policy of parallel. I believe that updates should be applied one pod at a time.

I agree that Medusa isn't involved here. Besides Medusa can you try removing other things and see if you can reproduce? For example, can you reproduce without the tolerations and telemetry?

**Comment by mlallaouret** [comment]
Thanks for taking some time to test the issue.
I did some other tests with a simpler configuration. Here is the base configuration I used:
```
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: test-cluster
spec:
  cassandra:
    serverVersion: "3.11.13"
    datacenters:
      - metadata:
          name: dc2
        size: 3
        racks:
          - name: rack1
        storageConfig:
          cassandraDataVolumeClaimSpec:
            storageClassName: standard
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
    config:
      jvmOptions:
        heapSize: 1Gi
    resources:
      requests:
        cpu: 1.5
        memory: 3Gi
      limits:
        cpu: 1.5
        memory: 3Gi
  reaper:
    autoScheduling:
      enabled: true
      repairType: ADAPTIVE

```

With the base configuration I had no issue.
Here are the other tests I did:
* + telemetry configuration: No issue
* + nodeAffinity configuration: 2 restarts of the cluster (no bug)
* + toleration configuration: 2 restarts of the cluster (no bug)
* + telemetry and selector: 2 restarts of the cluster (no bug)
* + telemetry and toleration configuration: 1 restart of the cluster (no bug)
* + toleration and nodeAffiinity configuration: 2 restarts of the cluster (no bug)
* + telemetry, toleration and nodeAffinity configuration: bug (I tested it a second time and I had only 2 restarts of the cluster without bug)

What I notice when there was 2 restarts without bug, it's that the reaper instance was up some seconds after the first cassandra node is restarted. I am wondering if the bug happens only when reaper has time to restart before the first cassandra node is completely restarted.

When I tested the upgrade the first time, we did it on our tests environment where there was data in the cluster and it happened each time. Maybe when there are data in the cluster it taked a bit more time to start and so reaper has time to be restarted before the cassandra node ?

Maybe I will have some time to do some other tests next week. I keep you posted.

**Comment by jsanda** [comment]
Thanks for the detailed update. I'll try to do some more testing as well.

**Comment by mlallaouret** [comment]
Small update after doing some others tests.

I still did not managed to repeat the issue at 100% with one configuration.
It seems the issue appears more when I use my full configuration: the simple configuration posted above + telemetry + tolerations + nodeAffinity + custom storage class (ssd) + medusa.

I monitored the rollout with the command: `kubectl rollout status statefulset <statefulsetName> --watch`
I saw this when the issue appears:
First, I do the `helm upgrade` command to update the operator, then I monitor with the command above.
```
Waiting for 1 pods to be ready...
Waiting for partitioned roll out to finish: 1 out of 3 new pods have been updated...
Waiting for 1 pods to be ready...
Waiting for 1 pods to be ready...
Waiting for partitioned roll out to finish: 2 out of 3 new pods have been updated...
Waiting for statefulset spec update to be observed...
Waiting for partitioned roll out to finish: 0 out of 3 new pods have been updated...
Waiting for 1 pods to be ready...
Waiting for 1 pods to be ready...
Waiting for 2 pods to be ready...
Waiting for 2 pods to be ready...
```
We can see that the 2 first pods are restarted, then there is an update that seems to be done on the statefulset and after this point there is 2 pods down.
For now, I did not managed to find something in the operator logs but I did not search a lot yet.

Another remark: reaper is not always restarting when I do the upgrade, I don't know why sometimes it restarts and sometimes not.

I'll post another message if I have new evidences.

**Comment by mlallaouret** [comment]
Hello,

I did some other tests.

What I found is between the beginning of the upgrade and the end of it, the `generation` metadata property is changed from `1` to `3`, So it means there is 2 updates of the statefulset during the upgrade process. These 2 updates occur with and without the bug.
I am wondering if the bug happens with a certain timing for the last statefulset update. (as we can see in my last message that when the bug occurs we can observe the statefulset update in the status events)

I did not see any particular log in the operator logs that could explain the issue.

**Comment by mlallaouret** [comment]
Hello,

I have some news since last time. I did not encounter the issue too much. And this week I got it twice in a row on two different clusters.
For informations the kubernetes cluster version is 1.26.x on google cloud, the cassandra cluster is made of 3 nodes and the cluster is deployed with reaper and medusa enabled.
I was upgrading the operator from 1.10.3 to 1.12.0.
As in the previous comments, after the upgrade of the operator, once first node is restarted, at the same time first node and second node are restarted which make the cluster unavailable.
Thanks to the history kubectl plugin I was able to see some interesting facts.

Here is the history of the first cluster statefulset
```
$ kubectl history list statefulset -n cassandra-test main-cluster-dc1-rack1-sts
 # | CREATE TIME                   | NAME                                  
---+-------------------------------+---------------------------------------
 3 | 2024-02-07 16:07:08 +0100 CET | main-cluster-dc1-rack1-sts-f79695696  
 2 | 2024-02-07 16:05:38 +0100 CET | main-cluster-dc1-rack1-sts-7bb4c98646 
 1 | 2024-02-07 11:30:15 +0100 CET | main-cluster-dc1-rack1-sts-577488dc8b
```
The second entry corresponds to the launch of the operator upgrade and we can see that a third entry appearing less than 2 minutes after the beginning of the upgrade and is a bit before the second restart of the first node.
After upgrade is finished, start time of first and seconde node to be restared shows the same value:
```
Start Time:       Wed, 07 Feb 2024 16:07:22 +0100
```

Here is the diff between version 1 and 2
```
$ kubectl history diff statefulset -n cassandra-test main-cluster-dc1-rack1-sts 1 2
--- OLD
+++ NEW
@@ -62,7 +62,7 @@
           value: "true"
         - name: DSE_MGMT_EXPLICIT_START
           value: "true"
-        image: k8ssandra/cass-management-api:4.1.2
+        image: cr.k8ssandra.io/k8ssandra/cass-management-api:4.1.2
         imagePullPolicy: IfNotPresent
         lifecycle:
           preStop:
@@ -234,7 +234,7 @@
             fieldRef:
               apiVersion: v1
               fieldPath: metadata.namespace
-        image: k8ssandra/system-logger:v1.18.2
+        image: cr.k8ssandra.io/k8ssandra/system-logger:v1.18.2
         imagePullPolicy: IfNotPresent
         name: server-system-logger
         resources:
@@ -259,7 +259,7 @@
         - cp -rf /etc/cassandra/* /cassandra-base-config/
         command:
         - /bin/sh
-        image: k8ssandra/cass-management-api:4.1.2
+        image: cr.k8ssandra.io/k8ssandra/cass-management-api:4.1.2
         imagePullPolicy: IfNotPresent
         name: server-config-init-base
         resources: {}
@@ -292,7 +292,7 @@
           value: cassandra
         - name: CONFIG_FILE_DATA
           value: '{"cassandra-env-sh":{"additional-jvm-opts":["-Dcassandra.allow_alter_rf_during_range_movement=true","-Dcassandra.system_distributed_replication=dc1:3","-Dcassandra.jmx.authorizer=org.apache.cassandra.auth.jmx.AuthorizationProxy","-Djava.security.auth.login.config=$CASSANDRA_HOME/conf/cassandra-jaas.config","-Dcassandra.jmx.remote.login.config=CassandraLogin","-Dcom.sun.management.jmxremote.authenticate=true"]},"cassandra-yaml":{"authenticator":"PasswordAuthenticator","authorizer":"CassandraAuthorizer","materialized_views_enabled":true,"memtable_allocation_type":"offheap_objects","num_tokens":256,"role_manager":"CassandraRoleManager","write_request_timeout":"5000ms"},"cluster-info":{"name":"main-cluster","seeds":"main-cluster-seed-service,main-cluster-dc1-additional-seed-service"},"datacenter-info":{"graph-enabled":0,"name":"dc1","solr-enabled":0,"spark-enabled":0},"jvm-server-options":{"initial_heap_size":1000000000,"max_heap_size":1000000000},"jvm11-server-options":{"garbage_collector":"G1GC"}}'
-        image: k8ssandra/k8ssandra-client:v0.2.2
+        image: cr.k8ssandra.io/k8ssandra/k8ssandra-client:v0.2.2
         imagePullPolicy: IfNotPresent
         name: server-config-init
         resources:
```
We can see it update only the fields of cassandra related images.

Here is the diff between version 2 and 3:
```
$ kubectl history diff statefulset -n cassandra-test main-cluster-dc1-rack1-sts 2 3
--- OLD
+++ NEW
@@ -163,7 +163,7 @@
             secretKeyRef:
               key: password
               name: main-cluster-medusa
-        image: docker.io/k8ssandra/medusa:0.16.2
+        image: docker.io/k8ssandra/medusa:0.17.2
         imagePullPolicy: IfNotPresent
         livenessProbe:
           exec:
@@ -329,7 +329,7 @@
             secretKeyRef:
               key: password
               name: main-cluster-medusa
-        image: docker.io/k8ssandra/medusa:0.16.2
+        image: docker.io/k8ssandra/medusa:0.17.2
         imagePullPolicy: IfNotPresent
         name: medusa-restore
         resources:
```
We can see that in a second time the medusa image is updated.

I did not find something interesting in cass-operator logs about this event.

What do you think ? Could it be a race condition between the statefulset controller and the operator doiing operations at the same time on the statefulset ? Is it normal that the update of the statefulset is done in two parts ?

Hoping these news can help you understand the issue :smiley:

**Comment by burmanm** [comment]
What you see is two separate events happening here. First is the actual upgrade of cass-operator, which caused it to read the new config files and apply the cr-prefix. This is then reconciled and StatefulSet is updated. 

After that, k8ssandra-operator updated itself and updated the CassandraDatacenter eventually with new configuration. Thus, cass-operator sees the update (new Medusa images) and updates the StatefulSets.

There's no simple way to make all that happen in a single update, since the resources are updated in Kubernetes at a different time and as such are reconciled at a different time (different here could be a millisecond or two, but that's enough).

To prevent this type of events from happening (and cascading everything to a single update) would require an install tool that disables cass-operator for a moment, letting k8ssandra-operator upgrade itself, then waiting for CassandraDatacenter to be reconciled by the k8ssandra-operator and only then enabling cass-operator with new config applied. But this is beyond what kubectl / Helm / OLM can do.

**Comment by mlallaouret** [comment]
Thanks for your answer @burmanm 

Let me make a sequence of what we see on our 3-nodes cluster during this two phases upgrade:

| Time | Node 1 status | Node 2 status | Node 3 status | Comment |
|--------|--------|--------|--------|--------|
| T0 | :heavy_check_mark: (v0) |  :heavy_check_mark: (v0) |  :heavy_check_mark: (v0) | Cluster is stable and all nodes in sync with statefulset in v0 |
| T1 |  :heavy_check_mark: (v0) |  :heavy_check_mark: (v0) | :x: (v1) | Node 3 is restarted after upgrade launch, statefulset now in v1 |
| T2 | :heavy_check_mark: (v0) |  :heavy_check_mark: (v0) |  :heavy_check_mark: (v1) |Node 3 finished restarting and is up in v1 |
| T3 | :heavy_check_mark: (v0) | :x: (v2)  |  :x: (v2) |Node 2 and 3 are restarted simultaneously after the statefulset is updated to v2|
| T4 | :heavy_check_mark: (v0) |  :heavy_check_mark: (v2)  |   :heavy_check_mark: (v2) |Node 2 and 3 finished restarting and are up in v2, order not guaranteed|
| T5 | :x:  (v2) |  :heavy_check_mark: (v2)  |   :heavy_check_mark: (v2) |Node 1 is restarted to upgrade to v2|
| T6 | :heavy_check_mark: (v2) |  :heavy_check_mark: (v2) |  :heavy_check_mark: (v2) | Cluster is stable and all nodes in sync with statefulset in v2 |

As you can see, at time T3, two nodes out of 3 are down, so we lose datacenter quorum !

When medusa is disabled, here is the sequence of the upgrade:

| Time | Node 1 status | Node 2 status | Node 3 status | Comment |
|--------|--------|--------|--------|--------|
| T0 | :heavy_check_mark: (v0) |  :heavy_check_mark: (v0) |  :heavy_check_mark: (v0) | Cluster is stable and all nodes in sync with statefulset in v0 |
| T1 |  :heavy_check_mark: (v0) |  :heavy_check_mark: (v0) | :x: (v1) | Node 3 is restarted after upgrade launch, statefulset now in v1 |
| T2 | :heavy_check_mark: (v0) |  :heavy_check_mark: (v0) |  :heavy_check_mark: (v1) |Node 3 finished restarting and is up in v1 |
| T3 | :heavy_check_mark: (v0) | :x: (v1)  | :heavy_check_mark: (v1) |Node 2 is restarted to be updated to v1|
| T4 | :heavy_check_mark: (v0) |  :heavy_check_mark: (v1) |  :heavy_check_mark: (v1) |Node 2 finished restarting and is up in v1 |
| T5 | :x:  (v1) |  :heavy_check_mark: (v1)  |   :heavy_check_mark: (v1) |Node 1 is restarted to upgrade to v1|
| T6 | :heavy_check_mark: (v1) |  :heavy_check_mark: (v1) |  :heavy_check_mark: (v1) | Cluster is stable and all nodes in sync with statefulset in v1 |

As you can see, the sequence works as expected and we never lose the datacenter quorum.
 
We have a pod disruption budget that allow only 1 pod down at a time and the statefulset has the default update strategy (RollingUpdate one node at a time):
```
updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
```
So for me those two nodes restarted at the same time are not caused by the kubernetes scheduler.

I don't know all the internals of the k8ssandra operator and the cass-operator but maybe the cass-operator should wait that the CassandraDatacenter is in an Healthy state before updating the statefulset (all nodes up and no RollingRestart in progress) ?

What do you think ? I am available to push further my tests if needed.
