### ISSUE TITLE
K8SSAND-81 ⁃ Generate the secret needed for accessing S3 bucket

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra#148]
**Is your feature request related to a problem? Please describe.**
Medusa can be configured to use an S3 bucket for remote storage. Medusa needs credentials in the form of an AWS access key in order to make the necessary S3 API calls. Those credentials are provided in a secret that the user has to create as a prerequisite set before deploying k8ssandra.

Here is an example of what the secret should look like:

```yaml
apiVersion: v1
kind: Secret
metadata:
 name: medusa-bucket-key
type: Opaque
stringData:
 # Note that this currently has to be set to medusa_s3_credentials!
 medusa_s3_credentials: |-
   [default]
   aws_access_key_id = my_access_key
   aws_secret_access_key = my_secret_key
```

**Describe the solution you'd like**
The goal of this ticket is to automate creating the secret. Helm provides functions for working with files (see [here](https://helm.sh/docs/chart_template_guide/accessing_files/)) that are intended to help with creating secrets and config maps. 

By simply specifying the path to an AWS credentials file, we should be able to generate the secret. 

Here is an example credentials file:

```
[default]
aws_access_key_id = my_access_key
aws_secret_access_key = my_secret_key
```

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-81) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-81
┆priority: Medium
