### ISSUE TITLE
k8ssandra-operator should define all bound ports in pod spec

### ISSUE THREAD

**Issue by petercable** [k8ssandra/k8ssandra#1488]
**Is your feature request related to a problem? Please describe.**
The k8ssandra-operator defined in the helm chart binds three TCP ports but only one of those ports (the webhook) is defined in the deployment's pod spec.

In some environments any workload providing a validating or mutating webhook must be run on the host network (for example, EKS with an alternative CNI). Without _all_ ports being defined, kubernetes cannot deconflict other host network workloads that attempt to bind the same port, leading to failures.

**Describe the solution you'd like**
Update the helm chart to include all bound ports.

**Describe alternatives you've considered**
None

**Additional context**
Using chart version `0.38.0`

**Comment by petercable** [comment]
```
-        {{- if .Values.controlPlane }}
         ports:
+          - containerPort: 8080
+            name: metrics
+            protocol: TCP
+          - containerPort: 8081
+            name: health
+            protocol: TCP
+          {{- if .Values.controlPlane }}
           - containerPort: 9443
             name: webhook-server
             protocol: TCP
-        {{- end }}
+          {{- end }}
```

**Comment by petercable** [comment]
Here's my post renderer in case someone lands on this after searching:

```
  postRenderers:
    - kustomize:
        patchesStrategicMerge:
          - apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: k8ssandra-operator
            spec:
              template:
                spec:
                  hostNetwork: true
                  containers:
                    - name: k8ssandra-operator
                      ports:
                        - name: metrics
                          containerPort: 8080
                          protocol: TCP
                        - name: health
                          containerPort: 8081
                          protocol: TCP
                        - name: webhook-server
                          containerPort: 9443
                          protocol: TCP
```
