### ISSUE TITLE
how to set cass-operator version through helm chart?

### ISSUE THREAD

**Issue by yaoyao12138** [k8ssandra/k8ssandra#1504]
https://github.com/k8ssandra/cass-operator#installing-cluster-via-helm
How to set  cass-operator version through this helm chart?
```
helm repo add k8ssandra https://helm.k8ssandra.io/stable
helm install cass-operator k8ssandra/cass-operator -n cass-operator --create-namespace
```
https://github.com/k8ssandra/k8ssandra/blob/main/charts/cass-operator/Chart.yaml
```
type: application
version: 0.37.1
appVersion: 1.12.0
dependencies:
  - name: k8ssandra-common
    version: 0.28.6
    repository: file://../k8ssandra-common
```
Check this `Chart.yaml`, there are different versions. Which version could be set if we need fix to a specific version?
