### ISSUE TITLE
Cassandra reaper deployments initContainer image version doesn't update on helm chart upgrade

### ISSUE THREAD

**Issue by Shivam0609** [k8ssandra/k8ssandra#1554]
## Bug Report

**Describe the bug**
When upgrading k8ssandra helm chart from v1.5.0  to v1.5.2 , reaper-operator is not updating the `cassandra-reaper` initContainer image while main container image gets updated.

**To Reproduce**
1. Install k8ssandra chart version v1.5.0
2. Check `cassandra-reaper` deployment images version (containers & initContainers) - should be 3.1.1 for both images
3. Upgrade chart version to v1.5.2
4. Check `cassandra-reaper` deployment images version (containers & initContainers) - should be 3.2.1 for both image, but initContainers image is still on version 3.1.1 which is vulnerable image.

**Expected behavior**
Post upgrade to k8ssandra v1.5.2, cassandra-reaper's container and initContainer images must be on version 3.2.1

Cassandra reaper image 3.2.1 released in v1.5.2 of k8ssandra chart fixes a Critical vulnerability `CVE-2022-42889` in `cassandra-reaper` image. But chart upgrade partially fixes this vulnerability in cassandra-reaper as initContainer image is still on vulnerable version.

**Screenshots**

**Environment (please complete the following information):**

* Helm charts version info

    Upgrading from v1.5.0 to v1.5.2

* Helm charts user-supplied values

```yaml
cassandra:
  auth:
    enabled: false
  version: "3.11.12"
  cassandraLibDirVolume:
    storageClass: gp3
    size: 8Gi
  heap:
    size: 4G
  resources: {}
  loggingSidecar:
    enabled: false
  metric_filters: []
kube-prometheus-stack:
  enabled: false
stargate:
  enabled: false
```

* Kubernetes version information:

```bash   
(root:~) kubectl version --short
 Client Version: v1.23.9
 Server Version: v1.23.13-eks-fb459a0
```

* Kubernetes cluster kind:

```
Amazon EKS 
```

**Additional context**
