### ISSUE TITLE
Adding details for deploying reaper pod in k8ssandra

### ISSUE THREAD

**Issue by RachanKaur** [k8ssandra/k8ssandra#1570]
Currently there are no details in the documentation about how to deploy reaper pod with k8ssandra.
https://docs-v2.k8ssandra.io/components/reaper/

We should have the information about adding reaper pod deployment in our current docs.

This is the information which can be used for documentation:

There are two ways we can deploy reaper pod by editing the cluster or by editing the `k8c1.yml` file and reapplying it:

edit the cluster to deploy reaper pod 

 `kubectl edit k8cs -n k8ssandra-operator`
add reaper specs just above cassandra like this:
```
reaper:
    heapSize: 512Mi
    autoScheduling:
      enabled: false
cassandra:
  ...
  ...
```

2. Edit the `k8c1.yml` file 

`vi k8c1.yml`
add the details and save the file:
```
reaper:
    heapSize: 512Mi
    autoScheduling:
      enabled: false
cassandra:
  ...
  ...
```

reapply the file

`kubectl apply -n k8ssandra-operator -f k8c1.yml`
