### ISSUE TITLE
Exposing stargate component externally

### ISSUE THREAD

**Issue by hoangpham95** [k8ssandra/k8ssandra#1583]
**Type of question**
I have trouble with exposing stargate service with an external IP address in GKE.

**What did you do?**
1. Create an ingress and attach to the service with the following yaml:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-name
  annotations:
spec:
  defaultBackend:
    service:
      name: service-name
      port:
        number: 9042
```
However when describing the ingress, the address is empty.
2. Update the service with a static IP with
```kubectl patch svc service-name -p '{"spec": {"externalIPs": ["some-ip"]}}'```
but the service's external IP address is still missing.

**Did you expect to see some different?**

**Environment**

* Helm charts version
version.BuildInfo{Version:"v3.11.0", GitCommit:"472c5736ab01133de504a826bd9ee12cbe4e7904", GitTreeState:"clean", GoVersion:"go1.19.5"}
