### ISSUE TITLE
Make default super user configurable

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra#159]
**Is your feature request related to a problem? Please describe.**
cass-operator generates a super user that is configurable. If authentication is enabled (see #151), we should make the super user configurable.

**Describe the solution you'd like**
I should have the option to bring my own credentials which should be specified via a secret name. Alternatively, I should be able to just specify a username and have k8ssandra generate a password and the secret for me.

We might have properties something like this:

```yaml
# example values.yaml
k8ssandra:
  auth:
    enabled: true
    superuser:      
      secret: ""
      username: admin
```
If the `secret` property is set, we ignore `username`. If `username` is set we generate a random password and create the secret that will get specified in the cassdc.yaml template.
