### ISSUE TITLE
Passing imagePullSecrets in the Helm charts is broken

### ISSUE THREAD

**Issue by adejanovski** [k8ssandra/k8ssandra#1601]
It looks like the changes made [here](https://github.com/k8ssandra/k8ssandra/pull/1421/files#diff-0aa6e01e1095bfe2f57646f7fed7aed71876d875f8cc5b664e97f755c55fbe4fR46-R47) broke the template for passing imagePullSecrets in the values file.

Using this value:

```
imagePullSecret:
  name: regcred
```

Generates this:
```
apiVersion: config.k8ssandra.io/v1beta1
kind: ImageConfig
images:
  system-logger: "k8ssandra/system-logger:v1.14.0"
  config-builder: "datastax/cass-config-builder:1.0-ubi7"
imagePullSecret: map[name:regcred]
imagePullPolicy: IfNotPresent
...
```

We should re-instate using `toYaml` in the template so that the list of pull secrets is correctly formatted in the ImageConfig output.
