### ISSUE TITLE
Trying to set up ingress with nginx

### ISSUE THREAD

**Issue by sergio-moreira-everi** [k8ssandra/k8ssandra#1639]
**Type of question**

How to perform a particular operation

**What did you do?**
1. I have the helm operator installed; 
`helm install k8ssandra-operator k8ssandra/k8ssandra-operator -n k8ssandra-operator  --set global.clusterScoped=true`
For now I just want the operator and a k8ssandra cluster deployed in the same cluster.
1. I can successfully port forward to 9042 and use cqlsh 
```sh
cqlsh 127.0.0.1 50672 -u <USERNAME> -p <PASSWORD>
```
1. So I tried setting up Ingress with nginx to point to the cluster service for port 9042
```yaml
metadata:
  name: <CASS_INGRESS>
  namespace: <CASS_NS>
spec:
  ingressClassName: nginx
  rules:
  - host: <HOSTNAME>
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: <NAME>-dc1-service
            port:
              number: 9042
```
1. Now I try hitting the endpoint with <HOSTNAME>
```sh
cqlsh <HOSTNAME> 80 -u <USERNAME> -p <PASSWORD>
```
and I get the following error:
```sh
Connection error: ('Unable to connect to any servers', {'<IP>:80': ProtocolError('This version of the driver does not support protocol version 72')})
```

**Did you expect to see some different?**
I'd expect to be able to run cqlsh just fine and enter the shell

**Environment**

* Helm charts version
1.11.1
