### ISSUE TITLE
Add updateStrategy configuration option for K8ssandraCluster 

### ISSUE THREAD

**Issue by gdrozda-kio** [k8ssandra/k8ssandra#1656]
**Is your feature request related to a problem? Please describe.**
I would like to have possibility to manually restart pods in manually when changing statefulset. 

**Describe the solution you'd like**
I would like to have possibility to configure updateStrategy for statefulsets when configure cluster CRD K8ssandraCluster eg:
```
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
spec:
  cassandra:
    updateStrategy:
        type: OnDelete
```
**Describe alternatives you've considered**
I believe adding posibility to configure updateStrategy would be best solution.

**Additional context**
I really appreciate your hard work 👍
