### ISSUE TITLE
An in-place restore with an incorrect cluster name gets stuck

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra#189]
## Bug Report

**Describe the bug**
When I perform a restore and specify the cluster name incorrectly, the operation fails as would be expected. The problem is that the status of the CassandraRestore object indicate the progress or lack thereof. Nor is there any event generated. I was only able to discover a problem by checking the logs of medusa-operator.

**To Reproduce**
1. Create a cluster with backup/restore support enabled
2. Use a `values.yaml` like this: 
```yaml
k8ssandra:
  clusterName: test
  size: 3
  cassandraVersion: "3.11.7"
backupRestore:
  medusa:
    enabled: true
    bucketName: k8ssandra-dev
    bucketSecret: medusa-bucket-key
    multiTenant: false
    storage: s3
```
3. Create the cluster,

```
$ helm install test k8ssandra/k8ssandra-cluster -f values.yaml
```

4. Wait for the cluster to become ready
5. Create a backup. 
6. Use a values.yaml file like this:

```yaml
name: backup-1
cassandraDatacenter:
  name: dc1
```
7. Run Helm

```
$ helm install backup-test k8ssandra/backup -f values.yaml
```
8. Wait for the backup to complete
9. Create a restore 
10. Use a values.yaml file like this:

```yaml
name: restore-1
backup:
  name: backup-1
cassandraDatacenter:
  name: dc1-invalid
  clusterName: k8ssandra
inPlace: true
```
11. The CassandraRestore object will look like this:

```yaml
apiVersion: cassandra.k8ssandra.io/v1alpha1
kind: CassandraRestore
metadata:
  annotations:
    meta.helm.sh/release-name: restore-test
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2021-01-12T21:53:28Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
  name: restore-1
  namespace: default
  resourceVersion: "4435363"
  selfLink: /apis/cassandra.k8ssandra.io/v1alpha1/namespaces/default/cassandrarestores/restore-1
  uid: 28557e22-ef55-44f5-871b-76a77f1f0b8d
spec:
  backup: backup-1
  cassandraDatacenter:
    clusterName: dc1-restored
    name: dc1-restored
  inPlace: true
status:
  restoreKey: a3451212-27b4-4f41-be13-60e514c87018
```
The status is never updated beyond what is seen here.

12. medusa-operator logs report the following:

```
2021-01-12T21:54:57.610Z	INFO	controllers.CassandraRestore	performing in place restore
2021-01-12T21:54:57.610Z	ERROR	controllers.CassandraRestore	failed to get cassandradatacenter	{"CassandraDatacenter": "default/dc1-restored", "error": "CassandraDatacenter.cassandra.datastax.com \"dc1-restored\" not found"}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128
github.com/k8ssandra/medusa-operator/controllers.(*CassandraRestoreReconciler).Reconcile
	/workspace/controllers/cassandrarestore_controller.go:134
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:235
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:209
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:188
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.Until
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:90
```

**Expected behavior**
There should be something in the status of the CassandraRestore to indicate that the operation failed. Alternatively a validating webhook could also be used to ensure that the cluster actually exists. I consider the webhook a nice to have enhancement that could be added in the future.

**Screenshots**

**Environment (please complete the following information):**

* Helm charts version info
0.23.0
