### ISSUE TITLE
In-place restores report being finished too soon

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra#192]
## Bug Report

**Describe the bug**
When a restore operation is created the status of the CassandraRestore object reports it as finished before the cluster rolling restart has finished. 

Here is what it looks like:

```yaml
apiVersion: cassandra.k8ssandra.io/v1alpha1
kind: CassandraRestore
metadata:
  annotations:
    meta.helm.sh/release-name: restore-test
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2021-01-12T23:20:46Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
  name: restore-1
  namespace: default
  resourceVersion: "4473081"
  selfLink: /apis/cassandra.k8ssandra.io/v1alpha1/namespaces/default/cassandrarestores/restore-1
  uid: 4943ea69-7128-4ead-92b2-e509010ee778
spec:
  backup: backup-1
  cassandraDatacenter:
    clusterName: dc1
    name: dc1
  inPlace: true
status:
  finishTime: "2021-01-12T23:20:46Z"
  restoreKey: 87f36737-21d1-4c08-8591-91b4f38316f1
  startTime: "2021-01-12T23:20:46Z"
```

`cassandrarestore_controller` in medusa-operator is adding `.status.finishTime` prematurely. It needs to wait for the cluster rolling restart to finish.

**Expected behavior**
`cassandrarestore_controller` in medusa-operator is adding `.status.finishTime` prematurely. It needs to wait for the cluster rolling restart to finish.

**Screenshots**

**Environment (please complete the following information):**

* Helm charts version info
0.23.0

**Comment by burmanm** [comment]
This happens because the rolling restart is not initiated by the cass-operator, but by the reaper shutting down the nodes after it has restored the backups (using stop_cmd). So the status of the Datacenter never changes.

**Comment by burmanm** [comment]
The reason is that cass-operator and medusa-operator do not discuss with each other. The medusa-operator sets the resources with update process and immediately check if the CassDc is ready. It is of course instantly ready as the cass-operator does not catch this type of restart event.

The first PR I sent (and closed) was using a method of checking the individual pods underneath the CassandraDatacenter and that their start time was newer than the repair start time. I'm just not sure if that's a perfect method, or did you happen to have some better method of doing this? Without modifications to the cass-operator it might be difficult (we could set the rollingRestartRequired of course - after the patch updates, without hopefully restarting everything twice).

**Comment by jsanda** [comment]
I have been using the term _rolling restart_ a bit loosely and should provide some clarification. Any update to the underlying StatefulSet's PodTemplateSpec will cause an update of the StatefulSet which has the effect of a rolling restart in the sense that the nodes are going down and coming back up. The restore controller updates the CassandraDatacenter spec which in turn causes a StatefulSet update, hence the rolling restart.

CassandraDatacenter also has a `.spec.requestRollingRestart` property which can be used to trigger a rolling restart without updating the StatefulSet. We were previously setting that as well, but it caused two rolling restarts. See https://github.com/datastax/cass-operator/issues/326.

CassandraDataCenter has various status conditions that are represented by the `DatacenterCondition` struct which has this definition:

```go
type DatacenterCondition struct {
	Type               DatacenterConditionType `json:"type"`
	Status             corev1.ConditionStatus  `json:"status"`
	Reason             string                  `json:"reason"`
	Message            string                  `json:"message"`
	LastTransitionTime metav1.Time             `json:"lastTransitionTime,omitempty"`
}
```

One of the DatacenterConditions is named `RollingRestart`. It is added to `CassandraDatacenter.Status.Conditions` with a value of `true` when `.spec.requestRollingRestart` is flipped to `true`.

There is another condition named `Updating`. It is added to `CassandraDatacenter.Status.Conditions` with a value of `true` when the StatefulSet is updated. The status value is flipped to `false` after the update completes. 

I don't think we need to make any modifications to fix this. Nor do I think we need to check individual pods. After updating/patching the CassandraDatacenter, the restore controller will requeue the request. On the subsequent reconciliation it should find that the `Updating` condition has transitioned to `true`. There is also the `.Status.LastServerNodeStarted` field  which I believe gets updated each time a Cassandra node is started. Once the `Updating` condition transitions back to `false` and the CassandraDatacenter is ready, then the restore is complete.

**Comment by burmanm** [comment]
The problem with that assumption is the requeue. It already does the requeue after sending the details:

```java
		if err = r.Update(ctx, cassdc); err == nil {
			r.Log.Info("the cassandradatacenter has been updated and will be restarted", "CassandraDatacenter", cassdcKey)
			return ctrl.Result{RequeueAfter: 10 * time.Second}, err
```

And in the next step is checks just for the Ready status (not for Updating status) - that's a problem, however in your example we have another issue:

```
  finishTime: "2021-01-12T23:20:46Z"
  startTime: "2021-01-12T23:20:46Z"
```

This indicates the requeue has happened immediately, inside one second (startTime and finishTime can't be set in the same loop iteration) and quite likely the cass-operator has not had a chance to update the status meanwhile.

**Comment by jsanda** [comment]
Here partial output of my CassandraDatacenter status:

```yaml
status:
  cassandraOperatorProgress: Updating
  conditions:
  - lastTransitionTime: "2021-01-19T00:23:41Z"
    message: ""
    reason: ""
    status: "False"
    type: ScalingUp
  - lastTransitionTime: "2021-01-19T00:25:51Z"
    message: ""
    reason: ""
    status: "True"
    type: Updating
...
  lastServerNodeStarted: "2021-01-19T00:28:29Z"
```

We should be able do this in a way that it does not matter if the next reconcile happens in 30 milliseconds or in 30 minutes. On the next reconciliation, we first need to compare `startTime` with the `lastTransitionTime` of the `Updating` condition. If `startTime` >= `lastTransitionTime` I think we can simply requeue as cass-operator has not made any changes yet. 

Eventually the `status` field in the `Updating` condition should flip to `true`. We need to keep requeuing the request until it flips back to `false`.

We could alternatively check timestamps on the initContainers. The initContainers have a status that looks like this:

```yaml
  initContainerStatuses:
  - containerID: docker://0217c3f4d699f0ae42c1568c4ed4e0cc5d5d023264f13901eb2974ba00930464
    image: datastax/cass-config-builder:1.0.3-ubi7
    imageID: docker-pullable://datastax/cass-config-builder@sha256:aafd81e97d61d9851bd0191be1bf478ed2f167c51ad21a072e021584198ef701
    lastState: {}
    name: server-config-init
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: docker://0217c3f4d699f0ae42c1568c4ed4e0cc5d5d023264f13901eb2974ba00930464
        exitCode: 0
        finishedAt: "2021-01-19T00:35:01Z"
        reason: Completed
        startedAt: "2021-01-19T00:34:57Z"
```
If `state.startedAt`<= `startTime` we know that the restore for that C* node has not happened yet.
