### ISSUE TITLE
backup/restore does not restore dropped keyspace

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra#193]
## Bug Report

**Describe the bug**
I was doing some testing with backup/restore where created a keyspace and table, performed a backup, dropped the keyspace, and then did a restore. The dropped keyspace was not restored. I verified that it existed in the backup.

**To Reproduce**
1. Create a cluster with backup/restore enabled:

```
$ helm install k8ssandra k8ssandra/k8ssandra

$ helm install test k8ssandra/k8ssandra-cluster -f backup-restore-values.yaml 
```

backup-restore-values.yaml:
```yaml
k8ssandra:
  clusterName: test
  size: 3
  cassandraVersion: "3.11.7"
backupRestore:
  medusa:
    enabled: true
    bucketName: k8ssandra-dev
    bucketSecret: medusa-bucket-key
    multiTenant: false
    storage: s3
```
2. Wait for cluster to become ready
3. Log into cqlsh

```
$ kubectl exec -it <cassandra-pod> -c cassandra -- cqlsh
```
4. Create some test data

```
cqlsh> CREATE KEYSPACE test WITH replication = {'class': 'NetworkTopologyStrategy', 'dc1': 3};

cqlsh> CREATE TABLE test.users (email text primary key, name text);

cqlsh> INSERT INTO test.users (email, name) VALUES ('john@test.com', 'John Smith');
```

5. Create a backup

```
$ helm install backup-test k8ssandra/backup -f backup-values.yaml
```

backup-values.yaml:
```
name: backup-1
cassandraDatacenter:
  name: dc1
```
6. Wait for backup to finish. The backup is finished when the CassandraBackup has a `.status.finishTime` property set, e.g.

```
$ kubectl get cassandrabackup backup-1 -o yaml
apiVersion: cassandra.k8ssandra.io/v1alpha1
kind: CassandraBackup
...
status:
...
  finishTime: "2021-01-12T23:36:55Z"
  finished:
  - upgrade-test-dc1-default-sts-2
  - upgrade-test-dc1-default-sts-0
  - upgrade-test-dc1-default-sts-1
  startTime: "2021-01-12T23:36:26Z"
```

7. Drop the keyspace
8. Perform a restore

```
$ helm install restore-test k8ssandra/restore -f restore-values.yaml
```
restore-values.yaml:
```
name: restore-1
backup:
  name: backup-1
cassandraDatacenter:
  name: dc1
  clusterName: k8ssandra
inPlace: true
```
8. Wait for the rolling restart of the cluster to finish. The CassandraDatacenter has a status condition named `Updating`. It will be set to `true` when the restore begins. The rolling restart is complete when it is reset back to `false`.

9. Log back into cqlsh and check to see if the keyspace is restored.

**Expected behavior**
The dropped keyspace should be restored.

**Environment (please complete the following information):**

* Helm charts version info
0.23.0
