### ISSUE TITLE
How can we deploy Reaper without an ingress?

### ISSUE THREAD

**Issue by Miles-Garnsey** [k8ssandra/k8ssandra#201]
**Type of question**

Repair-related question.

**What did you do?**

I would like to be able to deploy Reaper without having to deploy an ingress alongside it. The [documentation](https://k8ssandra.io/docs/topics/accessing-services/repair/) doesn't really mention Reaper except in the context of accessing its UI.

**Did you expect to see some different?**

It seems that the only way to deploy Reaper via the Helm charts is by running helm with `--set ingress.traefik.enabled=true`. Why is turning Reaper on dependant on also turning on an Ingress? 

Is this just a gap in the documentation that I can help with, or is there a deeper reason why Reaper cannot be enabled without also enabling the ingress.

**Comment by jsanda** [comment]
Hey @Miles-Garnsey,

Reaper is deployed by default. Traefik does not have to be deployed in order to run Reaper. Here is the relevant config from the k8ssandra chart's `values.yaml`:

```yaml
# Configuration regarding configuration of repair services
repair:
  # Reaper repair service and UI
  reaper:
    autoschedule: false
    enabled: true
    jmx:
      username: ""
      password: ""
    operator:
      enabled: true
```
Maybe the docs need to be made more clear?
