### ISSUE TITLE
Make Reaper auto scheduling configurable

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra#224]
**Is your feature request related to a problem? Please describe.**
We added initial support for auto scheduling in https://github.com/k8ssandra/k8ssandra/issues/95. Reaper allows you to configure auto scheduling. Here is an example take from the Reaper [docs](http://cassandra-reaper.io/docs/configuration/reaper_specific/):

```yaml
autoScheduling:
  enabled: true
  initialDelayPeriod: PT15S
  periodBetweenPolls: PT10M
  timeBeforeFirstSchedule: PT5M
  scheduleSpreadPeriod: PT6H
  excludedKeyspaces: [myTTLKeyspace, ...]
```

**Describe the solution you'd like**
I would like the Reaper CRD (see [here](https://github.com/k8ssandra/reaper-operator/blob/master/api/v1alpha1/reaper_types.go)) to allow me to configure auto scheduling.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-95) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-95
