### ISSUE TITLE
Backups do not work with Cassandra 3.11.8 or 3.11.9

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra#226]
## Bug Report

**Describe the bug**
I ran into this issue while trying to test https://github.com/k8ssandra/k8ssandra/issues/193. Creating a backup fails with a validation error in medusa-operator like this:

```
2021-01-22T04:08:30.225Z	ERROR	controllers.CassandraBackup	failed to patch status with CassdcTemplateSpec	{"CassandraDatacenter": "default/dc1", "error": "CassandraBackup.cassandra.k8ssandra.io \"backup-1\" is invalid: status.cassdcTemplateSpec.spec.serverVersion: Unsupported value: \"3.11.9\": supported values: \"6.8.0\", \"6.8.1\", \"6.8.2\", \"6.8.3\", \"3.11.6\", \"3.11.7\", \"4.0.0\""}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128
github.com/k8ssandra/medusa-operator/controllers.(*CassandraBackupReconciler).Reconcile
	/workspace/controllers/cassandrabackup_controller.go:108
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:235
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:209
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:188
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.Until
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:90
```
The CassandraBackup CRD includes the CassandraDatacenter CRD because we have the `CassandraBackup.Status.CassdcTemplateSpec` field which is imported from `github.com/datastax/cass-operator/operator/pkg/apis/cassandra/v1beta1`. The embedded CassandraDatacenter CRD is out of date. It has this validation:

```yaml
                     serverVersion:
                        description: Version string for config builder, used to generate
                          Cassandra server configuration
                        enum:
                        - 6.8.0
                        - 6.8.1
                        - 6.8.2
                        - 6.8.3
                        - 3.11.6
                        - 3.11.7
                        - 4.0.0
                        type: string
```

More recent versions of the CassandraDatacenter CRD use a regex validation check that will allow any 3.11.x version.

Unfortunately we have multiple copies of the CassandraDatacenter CRD floating around in different places. We need to keep them in sync.

**Comment by burmanm** [comment]
Is this because of outdated version? I can't see that restriction anywhere in the master-branch:

```yaml
                    serverVersion:
                      description: Version string for config builder, used to generate
                        Cassandra server configuration
                      pattern: (6\.8\.\d+)|(3\.11\.\d+)|(4\.0\.\d+)
                      type: string
```
