### ISSUE TITLE
Improve configuration for multi-namespace support in cass-operator chart

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra#231]
**Is your feature request related to a problem? Please describe.**
We recently added the cass-operator chart. It has the property `clusterScoped` which determines whether cass-operator watches only the release namespace or watches all namespaces. There are two problems. First, the name `clusterScoped` is not very as to its intent. Secondly, cass-operator, like many operators, supports watching multiple namespaces. The configuration currently does not allow for that.

**Describe the solution you'd like**
I would like to replace the `clust.erScoped` property with something similar to what I have seen in other charts like kube-prometheus-stack. 

Something like this would work:

```yaml
namespaces: 
    releaseNamespace: true
    allNamespaces: false
    # additional:
    # - another-namespace-1
    # - another-namespace-2
    # - another-namespace-3
```
This provides the flexibility to watch just the release namespace, all namespaces, or a list of namespaces.
