### ISSUE TITLE
k8ssandra will not install on k8s v1.15.12 

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra#251]
## Bug Report

**Describe the bug**
Trying to install k8ssandra into kubernetes v1.15.12 (via kind) fails with errors.  It works for v1.16.15, v1.17.11, and v1.18.8.

**To Reproduce**
1. Create a kind cluster with the following configuration:

```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: k8ssandra
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 32080
        hostPort: 8080
        protocol: TCP
      - containerPort: 32443
        hostPort: 8443
        protocol: TCP
      - containerPort: 32090
        hostPort: 9000
        protocol: TCP
      - containerPort: 32091
        hostPort: 9042
        protocol: TCP
      - containerPort: 32092
        hostPort: 9142
        protocol: TCP
  - role: worker
  - role: worker
  - role: worker
```

with the following command:

```
kind create cluster --image "kindest/node:v1.15.12" --config kind.config.yaml
```
2. Attempt to install k8ssandra:

```
% helm install k8ssandra ~/github/k8ssandra/k8ssandra/charts/k8ssandra --debug
```

3. Results in the following error message:

```
install.go:172: [debug] Original chart version: ""
install.go:189: [debug] CHART PATH: /Users/jeffdinoto/github/k8ssandra/k8ssandra/charts/k8ssandra

client.go:122: [debug] creating 1 resource(s)
client.go:122: [debug] creating 1 resource(s)
client.go:122: [debug] creating 1 resource(s)
client.go:122: [debug] creating 1 resource(s)
client.go:122: [debug] creating 1 resource(s)
client.go:122: [debug] creating 1 resource(s)
Error: failed to install CRD crds/crd-alertmanagerconfigs.yaml: unable to recognize "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1"
helm.go:81: [debug] unable to recognize "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1"
failed to install CRD crds/crd-alertmanagerconfigs.yaml
helm.sh/helm/v3/pkg/action.(*Install).installCRDs
        /private/tmp/helm-20201209-32798-18s27r6/pkg/action/install.go:133
helm.sh/helm/v3/pkg/action.(*Install).Run
        /private/tmp/helm-20201209-32798-18s27r6/pkg/action/install.go:190
main.runInstall
        /private/tmp/helm-20201209-32798-18s27r6/cmd/helm/install.go:241
main.newInstallCmd.func2
        /private/tmp/helm-20201209-32798-18s27r6/cmd/helm/install.go:120
github.com/spf13/cobra.(*Command).execute
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842
github.com/spf13/cobra.(*Command).ExecuteC
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main
        /private/tmp/helm-20201209-32798-18s27r6/cmd/helm/helm.go:80
runtime.main
        /usr/local/Cellar/go/1.15.5/libexec/src/runtime/proc.go:204
runtime.goexit
        /usr/local/Cellar/go/1.15.5/libexec/src/runtime/asm_amd64.s:1374
```

**Expected behavior**
Installation should complete without error.

**Environment (please complete the following information):**

* Kubernetes version information:

```
% kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.12", GitCommit:"e2a822d9f3c2fdb5c9bfbe64313cf9f657f0a725", GitTreeState:"clean", BuildDate:"2021-01-22T21:57:01Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

Cluster deployment outlined in steps to reproduce above, resulting in the following environment:

```
% kubectl cluster-info     
Kubernetes master is running at https://127.0.0.1:57495
KubeDNS is running at https://127.0.0.1:57495/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
```

```
% kubectl get nodes
NAME                      STATUS   ROLES    AGE   VERSION
k8ssandra-control-plane   Ready    master   57s   v1.15.12
k8ssandra-worker          Ready    <none>   21s   v1.15.12
k8ssandra-worker2         Ready    <none>   22s   v1.15.12
k8ssandra-worker3         Ready    <none>   21s   v1.15.12
```
