### ISSUE TITLE
Finalize Stargate ingress routing

### ISSUE THREAD

**Issue by jakerobb** [k8ssandra/k8ssandra#253]
As of PR #163, Stargate ingress routing relies on a single hostname for all Stargate services (auth, graphql, rest, and cql). The CQL service uses a native Traefik ingress (because Kubernetes's native Ingress doesn't support non-HTTP) and routes based on port number; the other three use native Ingress (which doesn't support port-based routing) and routes based on path.

We're interested in changing this, but there are forces pulling in several directions. @bradfordcp asked to have until the end of this week (29 Jan 2021) to come back with a decision on what we want to do. This issue is the placeholder for whatever work is needed to act on said decision.

**Comment by jdonenine** [comment]
@bradfordcp did you have any more feedback on how you want to proceed here after thinking about it?

**Comment by bradfordcp** [comment]
Default `values.yaml` should focus on the developer deployment experience. To that end we should assume the user does not have a hostname or DNS entry to match on and omit this from our ingresses.

```yaml
# ...
spec:
  rules:
    - http:
        paths:
          - path: /v1/auth
            backend:
              serviceName: stargate-service
              servicePort: 8081
```

Given we're moving to subcharts we should consider the following as the shape for our `values.yaml`. (Note this starts at the root of `values.yaml` **not** the `ingress` key.)

```yaml
stargate:
  # ... existing stargate configuration
  
  # New pieces here
  ingress:
    auth:
      enabled: true
      # -- Optional hostname used to match requests
      host:
      # tls:
      #   # -- Hostnames to match as part of SNI routing
      #   hosts:
      #     - example.com
      #   # -- Secret containing the TLS certificate and key for encrypting requests to this endpoint
      #   secretName: my-secret

    rest:
      # -- Enables REST
      enabled: true
      # -- Optional hostname used to match requests
      host:
      # tls:
      #   # -- Hostnames to match as part of SNI routing
      #   hosts:
      #     - example.com
      #   # -- Secret containing the TLS certificate and key for encrypting requests to this endpoint
      #   secretName: my-secret

    graphql:
      # -- Enables GraphQL API endpoint ingress
      enabled: true
      # -- Optional hostname used to match requests
      host:
      # tls:
      #   # -- Hostnames to match as part of SNI routing
      #   hosts:
      #     - example.com
      #   # -- Secret containing the TLS certificate and key for encrypting requests to this endpoint
      #   secretName: my-secret

    cassandra:
      # -- Enables C* native protocol ingress with Traefik
      enabled: false
      # -- Determines which TCP-based ingress custom resources to template out. Currently only `traefik` is supported
      method: traefik
      # -- Parameters used by the Traefik IngressRoute custom resource
      traefik:
        entrypoint: cassandra
        # Future parameters
        # tls:
        #   client_auth:
        #     # -- Collection of Secrets containing TLS certificates. KEYS ARE NOT REQUIRED HERE
        #     ca_secrets:
        #       - ca_secret_1
        #   domains:
        #     - example.com
        #   # -- Secret containing the TLS certificate and key for the listener
        #   secretName: tls-secret
        
```

**Comment by bradfordcp** [comment]
If `stargate.auth.host` is specified we would template out

```yaml
# ...
spec:
  rules:
    - host: my-hostname-here
      http:
        paths:
          - path: /v1/auth
            backend:
              serviceName: stargate-service
              servicePort: 8081
```
