### ISSUE TITLE
Reaper chart

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra#263]
We want to pull out the Reaper bits from the k8ssandra into their own separate chart. See #202 and #219 for reference.

**Comment by jsanda** [comment]
I am moving this out of the 1.0 bucket due to some challenges I ran into with Helm. I will summarize them here.

The reaper chart needs to know about certain Cassandra settings such as auth, the cluster name, the cluster size, and the datacenter name. I will illustrate one of the big pain points using auth as an example. 

Cassandra authentication/authorization is configured in `k8ssandra/values.yaml` as follows:

```yaml
# k8ssandra/values.yaml
cassandra:
  auth:
    enabled: true
```
A child chart cannot access properties from the parent chart. They are out of scope. A parent chart _can_ override child chart properties. This means that you can push down properties from the parent to child charts. Given this we need the following in the values.yaml of the reaper chart:

```yaml
# reaper/values.yaml
cassandra:
  auth:
    enabled: true
```
Then in `k8ssandra/values.yaml` we would have:

```yaml
# k8ssandra/values.yaml
cassandra:
  auth:
    enabled: true

reaper:
  cassandra:
    auth:
      enabled: true
```
To enable/disable auth we need to update two properties. It is actually worse than this. There will be additional places that we have to do this when we add more charts that need the auth properties.

I explored using global variables. A potential solution is described [here](https://github.com/helm/helm/issues/5676#issuecomment-672819390). The idea is to put the auth properties in a global variable as follows:

```yaml
# k8ssandra/values.yaml
global:
  cassandra:
    auth:
      enabled: true
```
In `reaper/values.yaml` we just have:

```yaml
# reaper/values.yaml
cassandra: {}
```
In the reaper templates that need to access the auth properties we create a map (dict to be more precise):

```
{{- $cassandra := merge .Values.cassandra $.Values.global.cassandra }}
```
This solves part of the problem. It allows us to eliminate the duplication of properties in the parent and child charts' values.yaml files. That is great. 

There is still an issue though. Variables are scoped to the the template in which they are defined. I have to redefine `$cassandra` in each template where it is needed. 

It actually gets a bit worse. With a dict, I cannot do `$cassandra.auth.enabled` as I can with chart properties. Instead I have to use a function calls like this:

```
{{- $cassandra := merge .Values.cassandra $.Values.global.cassandra -}}
{{- $cassandraAuth := pick $cassandra "auth" -}}
{{- $authEnabled := get $cassandraAuth "enabled" -}}
```
As far as I know it is not possible to write custom template functions. With variable scope being limited to the template in which they are defined and without the ability to encapsulate this code inside a custom function, I fear we will quickly wind up with hard to maintain code.
