### ISSUE TITLE
Heap settings are not applied to Cassandra

### ISSUE THREAD

**Issue by adejanovski** [k8ssandra/k8ssandra#337]
## Bug Report

**Describe the bug**
Heap settings are not set correctly for Cassandra despite being customized in the charts.

**To Reproduce**
1. Run `helm template test charts/k8ssandra --set cassandra.heap.size=500`.
2. Check the config by looking at the output of `kubectl get cassdc dc1 -o yaml`.
3. Heap size isn't explicitely set there although it should be.

**Expected behavior**
Cassandra nodes should be customized with the heap settings from the charts.
It looks like leaving empty heap settings at the rack level causes the issue.
The following gives the buggy behavior:

```
  heap:
   size: 500M
   newGenSize: 200M
  resources: {}
  datacenters:
  - 
    name: dc1
    size: 3
    racks:
    - 
      name: rack1
      affinityLabels: {}
    heap:
      size: 
      newGenSize:
```

but this works as expected:

```
  size: 500M
   newGenSize: 200M
  resources: {}
  datacenters:
  - 
    name: dc1
    size: 3
    racks:
    - 
      name: rack1
      affinityLabels: {}
```

**Environment (please complete the following information):**

* Helm charts version info

```
NAME	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART           	APP VERSION
test	default  	1       	2021-02-08 14:35:23.241510784 +0000 UTC	deployed	k8ssandra-0.44.0	3.11.7
```

* Helm charts user-supplied values

```
USER-SUPPLIED VALUES:
backupRestore:
  medusa:
    bucketName: k8ssandra-medusa-dev
    bucketSecret: medusa-bucket-key
    cassandraUser:
      secret: cassandra
      username: cassandra
    enabled: true
    image:
      pullPolicy: IfNotPresent
      repository: docker.io/k8ssandra/medusa
      tag: 6ab6a55541e9
    multiTenant: false
    storage: s3
cass-operator:
  enabled: true
cassandra:
  allowMultipleNodesPerWorker: false
  auth:
    enabled: false
    superuser:
      secret: cassandra
      username: cassandra
  cassandraLibDirVolume:
    size: 5Gi
    storageClass: standard
  clusterName: k8ssandra
  datacenters:
  - name: dc1
    size: 3
  heap:
    newGenSize: 200M
    size: 500M
  resources: {}
  version: 3.11.10
  versionImageMap:
    3.11.10: datastax/cassandra-mgmtapi-3_11_10:v0.1.19
cleaner:
  image: k8ssandra/k8ssandra-cleaner:618b8ff9d368
kube-prometheus-stack:
  alertmanager:
    enabled: false
    serviceMonitor:
      selfMonitor: false
  coreDns:
    enabled: false
  enabled: true
  grafana:
    adminPassword: secret
    adminUser: admin
    defaultDashboardsEnabled: false
    enabled: true
    grafana.ini: {}
    ingress:
      enabled: false
      path: null
    plugins:
    - grafana-polystat-panel
    serviceMonitor:
      selfMonitor: false
  kubeApiServer:
    enabled: false
  kubeControllerManager:
    enabled: false
  kubeDns:
    enabled: false
  kubeEtcd:
    enabled: false
  kubeProxy:
    enabled: false
  kubeScheduler:
    enabled: false
  kubeStateMetrics:
    enabled: false
  kubelet:
    enabled: false
  nodeExporter:
    enabled: false
  prometheus:
    enabled: true
    ingress:
      enabled: false
      paths: []
    prometheusSpec:
      externalUrl: ""
      routePrefix: /
    serviceMonitor:
      selfMonitor: false
  prometheusOperator:
    enabled: true
    namespaces:
      additional: []
      releaseNamespace: true
    serviceMonitor:
      selfMonitor: false
monitoring:
  grafana:
    provision_dashboards: true
  prometheus:
    provision_service_monitors: true
reaper-operator:
  enabled: true
repair:
  reaper:
    autoschedule: false
    cassandraUser:
      secret: cassandra
      username: cassandra
    enabled: true
    image:
      repository: docker.io/thelastpickle/cassandra-reaper
      tag: 2.1.3
    jmx:
      password: ""
      username: ""
stargate:
  cassandraUser:
    secret: ""
    username: ""
  clusterVersion: "3.11"
  containerImage: auto
  enabled: false
  replicas: 1
```

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.11", GitCommit:"ea5f00d93211b7c80247bf607cfa422ad6fb5347", GitTreeState:"clean", BuildDate:"2020-09-14T07:50:38Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:
kind
