### ISSUE TITLE
Rework ingress configuration in values.yaml

### ISSUE THREAD

**Issue by jakerobb** [k8ssandra/k8ssandra#361]
In #253 and #342, @bradfordcp described a new, cleaner approach to configuration of ingress for the various components which will become necessary when we split off separate subcharts.

Reaper:
```
repair:
  reaper:
    # ... existing configuration
    ingress:
      enabled: true
      # -- Optional hostname used to match requests
      host:
      # tls:
      #   # -- Hostnames to match as part of SNI routing
      #   hosts:
      #     - example.com
      #   # -- Secret containing the TLS certificate and key for encrypting requests to this endpoint
      #   secretName: my-secret
```

Stargate:
```
stargate:
  # ... existing stargate configuration
  
  # New pieces here
  ingress:
    auth:
      enabled: true
      # -- Optional hostname used to match requests
      host:
      # tls:
      #   # -- Hostnames to match as part of SNI routing
      #   hosts:
      #     - example.com
      #   # -- Secret containing the TLS certificate and key for encrypting requests to this endpoint
      #   secretName: my-secret

    rest:
      # -- Enables REST
      enabled: true
      # -- Optional hostname used to match requests
      host:
      # tls:
      #   # -- Hostnames to match as part of SNI routing
      #   hosts:
      #     - example.com
      #   # -- Secret containing the TLS certificate and key for encrypting requests to this endpoint
      #   secretName: my-secret

    graphql:
      # -- Enables GraphQL API endpoint ingress
      enabled: true
      # -- Optional hostname used to match requests
      host:
      # tls:
      #   # -- Hostnames to match as part of SNI routing
      #   hosts:
      #     - example.com
      #   # -- Secret containing the TLS certificate and key for encrypting requests to this endpoint
      #   secretName: my-secret

    cassandra:
      # -- Enables C* native protocol ingress with Traefik
      enabled: false
      # -- Determines which TCP-based ingress custom resources to template out. Currently only `traefik` is supported
      method: traefik
      # -- Parameters used by the Traefik IngressRoute custom resource
      traefik:
        entrypoint: cassandra
        # Future parameters
        # tls:
        #   client_auth:
        #     # -- Collection of Secrets containing TLS certificates. KEYS ARE NOT REQUIRED HERE
        #     ca_secrets:
        #       - ca_secret_1
        #   domains:
        #     - example.com
        #   # -- Secret containing the TLS certificate and key for the listener
        #   secretName: tls-secret
        
```

And so on. 

Leaving those issues open to tackle the Reaper- and Stargate-specific changes not related to restructuring values.yaml, I'm spinning this issue off to do just the restructuring part of the work.
