### ISSUE TITLE
Stargate Cassandra ingress is configured incorrectly

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra#371]
## Bug Report

**Describe the bug**

When deploying stargate with ingress (the new default) the Cassandra ingress has errors and cannot be used:

![image](https://user-images.githubusercontent.com/7901615/107805345-3d0db400-6d33-11eb-88cd-ccbcc4d45802.png)

**To Reproduce**
1. Install traefik

(For Kind):
```
---
providers:
  kubernetesCRD:
    namespaces:
      - default
      - traefik
  kubernetesIngress:
    namespaces:
      - default
      - traefik

ports:
  traefik:
    expose: true
    nodePort: 32090
  web:
    nodePort: 32080
  websecure:
    nodePort: 32443
  cassandra:
    expose: true
    port: 9042
    nodePort: 32091
  cassandrasecure:
    expose: true
    port: 9142
    nodePort: 32092
  sg-graphql:
    expose: true
    port: 8080
    nodePort: 30080
  sg-auth:
    expose: true
    port: 8081
    nodePort: 30081
  sg-rest:
    expose: true
    port: 8082
    nodePort: 30082

service:
  type: NodePort
```

2. Deploy k8ssandra:

```
cassandra:
  version: "3.11.10"
  auth:
    enabled: false
  clusterName: k8ssandra-cluster
  datacenters:
  - name: dc1
    size: 1
kube-prometheus-stack:
  prometheus:
    enabled: true
    prometheusSpec:
      externalUrl: http://localhost:9090/prometheus
      routePrefix: /prometheus
    ingress:
      enabled: true
      paths:
        - /prometheus
  grafana:
    enabled: true
    ingress:
      enabled: true
      path: /grafana
    adminUser: admin
    adminPassword: admin123
    grafana.ini:
      server:
        root_url: http://localhost:3000/grafana
        serve_from_sub_path: true
ingress:
  traefik:
    enabled: true
    repair:
      host: repair.127.0.0.1.nip.io
    stargate:
      host: stargate.127.0.0.1.nip.io
backupRestore:
  medusa:
    enabled: true
    storage: s3
    bucketName: "jdinoto-k8ssandra-test"
    bucketSecret: "medusa-bucket-key"
```
3. Populate the cluster with some data

test-data.cql
```
CREATE KEYSPACE medusa_test WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 3};
USE medusa_test;
CREATE TABLE users (email text primary key, name text, state text);
insert into users (email, name, state) values ('john@gamil.com', 'John Smith', 'NC');
insert into users (email, name, state) values ('joe@gamil.com', 'Joe Jones', 'VA');
insert into users (email, name, state) values ('sue@help.com', 'Sue Sas', 'CA');
insert into users (email, name, state) values ('tom@yes.com', 'Tom and Jerry', 'NV');
```

```
kubectl exec -it k8ssandra-cluster-dc1-default-sts-0 -c cassandra -- mkdir /tmp/scripts/
```

```
kubectl cp ./test-data.cql k8ssandra-cluster-dc1-default-sts-0:/tmp/scripts -c cassandra
```

```
kubectl exec -it k8ssandra-cluster-dc1-default-sts-0 -c cassandra -- cqlsh -f /tmp/scripts/test-data.cql
```

```
kubectl exec -it k8ssandra-cluster-dc1-default-sts-0 -c cassandra -- cqlsh -e "select * from medusa_test.users;"
```
4. Observe the Traefik dashboard has errors as shown above and that access via CQL fails:

get-data.py
```
from cassandra.cluster import Cluster
from cassandra.auth import PlainTextAuthProvider

auth_provider = PlainTextAuthProvider(username='k8ssandra-cluster-superuser', password='XOHBHcJs_f8CFcciczCJYjmZEvoJmpBKpHVTVjO3G386yqWV6HtrEA')
cluster = Cluster(['stargate.127.0.0.1.nip.io'], auth_provider=auth_provider)
session = cluster.connect('medusa_test')
print(session.execute("SELECT * FROM users").one())
```

```
python get-data.py
```

**Expected behavior**

Access to Cassandra via the python driver used in the example should work as if it was the natively exposed Cassandra CQL access.

**Screenshots**

**Environment (please complete the following information):**

* Helm charts version info

```
% helm ls -A
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
k8ssandra       default         1               2021-02-12 09:44:05.487311 -0500 EST    deployed        k8ssandra-0.49.0        3.11.10    
traefik         default         1               2021-02-12 09:43:50.885753 -0500 EST    deployed        traefik-9.14.2          2.4.2  
``` 

* Helm charts user-supplied values

```
% helm get values k8ssandra
USER-SUPPLIED VALUES:
backupRestore:
  medusa:
    bucketName: jdinoto-k8ssandra-test
    bucketSecret: medusa-bucket-key
    enabled: true
    storage: s3
cassandra:
  auth:
    enabled: false
  clusterName: k8ssandra-cluster
  datacenters:
  - name: dc1
    size: 1
  version: 3.11.10
ingress:
  traefik:
    enabled: true
    repair:
      host: repair.127.0.0.1.nip.io
    stargate:
      host: stargate.127.0.0.1.nip.io
kube-prometheus-stack:
  grafana:
    adminPassword: admin123
    adminUser: admin
    enabled: true
    grafana.ini:
      server:
        root_url: http://localhost:3000/grafana
        serve_from_sub_path: true
    ingress:
      enabled: true
      path: /grafana
  prometheus:
    enabled: true
    ingress:
      enabled: true
      paths:
      - /prometheus
    prometheusSpec:
      externalUrl: http://localhost:9090/prometheus
      routePrefix: /prometheus
```

* Kubernetes version information:

```
% k version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.17", GitCommit:"f3abc15296f3a3f54e4ee42e830c61047b13895f", GitTreeState:"clean", BuildDate:"2021-01-22T22:20:06Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:
Kind

**Additional context**
@jakerobb confirmed that he was already aware of this and would include it in his current work.
