### ISSUE TITLE
Stargate requests fail with < 2 replicas

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra#390]
## Bug Report

**Describe the bug**
When trying to generate an auth token from stargate requests fail when there is < 2 replicas running with error:

```
{"description":"Failed to create token: org.apache.cassandra.stargate.exceptions.UnavailableException: Cannot achieve consistency level ONE"}
```

**To Reproduce**

(Using kind)

1. Deploy traefik with a config like

```
---
providers:
  kubernetesCRD:
    namespaces:
      - default
      - traefik
  kubernetesIngress:
    namespaces:
      - default
      - traefik

ports:
  traefik:
    expose: true
    nodePort: 32090
  web:
    nodePort: 32080
  websecure:
    nodePort: 32443
  cassandra:
    expose: true
    port: 9042
    nodePort: 32091
  cassandrasecure:
    expose: true
    port: 9142
    nodePort: 32092
  sg-graphql:
    expose: true
    port: 8080
    nodePort: 30080
  sg-auth:
    expose: true
    port: 8081
    nodePort: 30081
  sg-rest:
    expose: true
    port: 8082
    nodePort: 30082

service:
  type: NodePort
```

2. Deploy k8ssandra with a config like

```
cassandra:
  version: "3.11.7"
  clusterName: k8ssandra-cluster
  heap:
   size: 500M
   newGenSize: 500M
  datacenters:
  - name: dc1
    size: 3
ingress:
  traefik:
    enabled: true
    repair:
      enabled: true
      host: repair.127.0.0.1.nip.io
kube-prometheus-stack:
  prometheus:
    enabled: true
    prometheusSpec:
      externalUrl: http://localhost:9090/prometheus
      routePrefix: /prometheus
    ingress:
      enabled: true
      paths:
        - /prometheus
  grafana:
    enabled: true
    ingress:
      enabled: true
      path: /grafana
    adminUser: admin
    adminPassword: admin123
    grafana.ini:
      server:
        root_url: http://localhost:3000/grafana
        serve_from_sub_path: true
stargate:
  replicas: 1
```

3. Confirm that all components have been deployed as expected

```
$ kubectl get pods
NAME                                                  READY   STATUS      RESTARTS   AGE
k8ssandra-cass-operator-86958b76d5-w8ntw              1/1     Running     0          3h5m
k8ssandra-cluster-dc1-default-sts-0                   2/2     Running     0          108m
k8ssandra-cluster-dc1-default-sts-1                   2/2     Running     0          111m
k8ssandra-cluster-dc1-default-sts-2                   2/2     Running     0          114m
k8ssandra-dc1-stargate-65444d8cb-nxlg9                1/1     Running     0          3h5m
k8ssandra-grafana-b485f8785-htmv6                     2/2     Running     0          44m
k8ssandra-kube-prometheus-operator-65d6cc8fd4-2c94c   1/1     Running     0          3h5m
k8ssandra-reaper-k8ssandra-5877c75f54-2zhgs           1/1     Running     20         3h
k8ssandra-reaper-k8ssandra-schema-zl4hk               0/1     Completed   0          3h1m
k8ssandra-reaper-operator-6d7fc46fcb-m5f2m            1/1     Running     0          3h5m
prometheus-k8ssandra-kube-prometheus-prometheus-0     2/2     Running     1          43m
traefik-d5896685d-29j5h                               1/1     Running     0          45m
```

4. Attempt to make an authentication request and observe the error

```
$ curl -L -X POST 'http://stargate.127.0.0.1.nip.io:8081/v1/auth' -H 'Content-Type: application/json' --data-raw '{"username": "'$CASS_USERNAME'", "password": "'$CASS_PASSWORD'"}'
{"description":"Failed to create token: org.apache.cassandra.stargate.exceptions.UnavailableException: Cannot achieve consistency level ONE"}
```

5. Bump the replicas up to 2 with a helm upgrade of the following:

```
cassandra:
  version: "3.11.7"
  clusterName: k8ssandra-cluster
  heap:
   size: 500M
   newGenSize: 500M
  datacenters:
  - name: dc1
    size: 3
ingress:
  traefik:
    enabled: true
    repair:
      enabled: true
      host: repair.127.0.0.1.nip.io
kube-prometheus-stack:
  prometheus:
    enabled: true
    prometheusSpec:
      externalUrl: http://localhost:9090/prometheus
      routePrefix: /prometheus
    ingress:
      enabled: true
      paths:
        - /prometheus
  grafana:
    enabled: true
    ingress:
      enabled: true
      path: /grafana
    adminUser: admin
    adminPassword: admin123
    grafana.ini:
      server:
        root_url: http://localhost:3000/grafana
        serve_from_sub_path: true
stargate:
  replicas: 2
```

6. Observe that the second stargate pod is ready

```
$ k get pods
NAME                                                  READY   STATUS      RESTARTS   AGE
k8ssandra-cass-operator-86958b76d5-w8ntw              1/1     Running     0          3h
k8ssandra-cluster-dc1-default-sts-0                   2/2     Running     0          102m
k8ssandra-cluster-dc1-default-sts-1                   2/2     Running     0          105m
k8ssandra-cluster-dc1-default-sts-2                   2/2     Running     0          109m
k8ssandra-dc1-stargate-65444d8cb-nxlg9                1/1     Running     0          3h
k8ssandra-dc1-stargate-65444d8cb-x7kj9                1/1     Running     0          6m37s
k8ssandra-grafana-b485f8785-htmv6                     2/2     Running     0          38m
k8ssandra-kube-prometheus-operator-65d6cc8fd4-2c94c   1/1     Running     0          3h
k8ssandra-reaper-k8ssandra-5877c75f54-2zhgs           1/1     Running     20         175m
k8ssandra-reaper-k8ssandra-schema-zl4hk               0/1     Completed   0          175m
k8ssandra-reaper-operator-6d7fc46fcb-m5f2m            1/1     Running     0          3h
prometheus-k8ssandra-kube-prometheus-prometheus-0     2/2     Running     1          38m
traefik-d5896685d-29j5h                               1/1     Running     0          39m
```

6. Attempt the same auth request and observe that it works

```
$ curl -L -X POST 'http://stargate.127.0.0.1.nip.io:8081/v1/auth' -H 'Content-Type: application/json' --data-raw '{"username": "'$CASS_USERNAME'", "password": "'$CASS_PASSWORD'"}'
{"authToken":"a6638843-44e4-43f6-9cc8-3b318c40a4b8"}
```

**Expected behavior**

While not a good production deployment with only a single replica, I'd still expect that requests should work.

**Environment (please complete the following information):**

* Helm charts version info

```
$ helm ls -A
NAME     	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART           	APP VERSION
k8ssandra	default  	8       	2021-02-19 10:13:44.219711 -0500 EST	deployed	k8ssandra-0.51.0	3.11.10    
traefik  	default  	1       	2021-02-19 09:24:36.836962 -0500 EST	deployed	traefik-9.14.3  	2.4.5 
```

* Helm charts user-supplied values

```
$ helm get values k8ssandra
USER-SUPPLIED VALUES:
cassandra:
  clusterName: k8ssandra-cluster
  datacenters:
  - name: dc1
    size: 3
  heap:
    newGenSize: 500M
    size: 500M
  version: 3.11.7
ingress:
  traefik:
    enabled: true
    repair:
      enabled: true
      host: repair.127.0.0.1.nip.io
kube-prometheus-stack:
  grafana:
    adminPassword: admin123
    adminUser: admin
    enabled: true
    grafana.ini:
      server:
        root_url: http://localhost:3000/grafana
        serve_from_sub_path: true
    ingress:
      enabled: true
      path: /grafana
  prometheus:
    enabled: true
    ingress:
      enabled: true
      paths:
      - /prometheus
    prometheusSpec:
      externalUrl: http://localhost:9090/prometheus
      routePrefix: /prometheus
stargate:
  replicas: 1
```

then

```
$ helm get values k8ssandra
USER-SUPPLIED VALUES:
cassandra:
  clusterName: k8ssandra-cluster
  datacenters:
  - name: dc1
    size: 3
  heap:
    newGenSize: 500M
    size: 500M
  version: 3.11.7
ingress:
  traefik:
    enabled: true
    repair:
      enabled: true
      host: repair.127.0.0.1.nip.io
kube-prometheus-stack:
  grafana:
    adminPassword: admin123
    adminUser: admin
    enabled: true
    grafana.ini:
      server:
        root_url: http://localhost:3000/grafana
        serve_from_sub_path: true
    ingress:
      enabled: true
      path: /grafana
  prometheus:
    enabled: true
    ingress:
      enabled: true
      paths:
      - /prometheus
    prometheusSpec:
      externalUrl: http://localhost:9090/prometheus
      routePrefix: /prometheus
stargate:
  replicas: 2
```

* Kubernetes version information:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.15", GitCommit:"2adc8d7091e89b6e3ca8d048140618ec89b39369", GitTreeState:"clean", BuildDate:"2021-01-22T22:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

Kind with configuration: `kind create cluster --image "kindest/node:v1.16.15"  --config kind.config.yaml`

```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: k8ssandra
nodes:
- role: worker
- role: worker
- role: worker
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 32080
    hostPort: 8080
    protocol: TCP
  - containerPort: 32443
    hostPort: 8443
    protocol: TCP
  - containerPort: 32090
    hostPort: 9000
    protocol: TCP
  - containerPort: 30081
    hostPort: 8081
    protocol: TCP
  - containerPort: 30082
    hostPort: 8082
    protocol: TCP
  - containerPort: 32091
    hostPort: 9042
    protocol: TCP
  - containerPort: 32092
    hostPort: 9142
    protocol: TCP
```

**Additional context**
