### ISSUE TITLE
cqlsh commands show warnings

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra#396]
## Bug Report

** Update **
After starting a test with 3.11.7 I am seeing the same warnings.  So safe to assume this is related to the directory structure/permission changes in the container images that were made recently.

**Describe the bug**
After deploying a 4.0.0 based cluster for the first time and executing cqlsh commands within the Cassandra containers warnings on given on every execution - the commands work as expected though:

```
Warning: Cannot create directory at `/home/cassandra/.cassandra`. Command history will not be saved.
```

**To Reproduce**
1. Deploy a 4.0.0 cluster, I used this configuration

```
cassandra:
  version: "4.0.0"
  clusterName: k8ssandra-cluster
  heap:
   size: 500M
   newGenSize: 256M
  datacenters:
  - name: dc1
    size: 3
kube-prometheus-stack:
  prometheus:
    enabled: true
    prometheusSpec:
      externalUrl: http://localhost:9090/prometheus
      routePrefix: /prometheus
    ingress:
      enabled: true
      paths:
        - /prometheus
  grafana:
    enabled: true
    ingress:
      enabled: true
      path: /grafana
    adminUser: admin
    adminPassword: admin123
    grafana.ini:
      server:
        root_url: http://localhost:3000/grafana
        serve_from_sub_path: true
stargate:
  enabled: true
  replicas: 2
reaper:
  ingress:
    enabled: true
    host: repair.127.0.0.1.nip.io
backupRestore:
  medusa:
    enabled: true
    storage: s3
    bucketName: "jdinoto-k8ssandra-test"
    bucketSecret: "medusa-bucket-key"
```

2. Once deployed execute a cqlsh command like:

```
% CASS_USERNAME=$(kubectl get secret k8ssandra-cluster-superuser -o=jsonpath='{.data.username}' | base64 --decode)

% CASS_PASSWORD=$(kubectl get secret "k8ssandra-cluster-superuser" -o=jsonpath='{.data.password}' | base64 --decode)

% kubectl exec -it k8ssandra-cluster-dc1-default-sts-0 -c cassandra -- cqlsh -u $CASS_USERNAME -p $CASS_PASSWORD -e "describe keyspaces;"             
```

3. Observe that the result will always include a warning message

```
Warning: Cannot create directory at `/home/cassandra/.cassandra`. Command history will not be saved.


medusa_test  system_auth         system_traces        
reaper_db    system_distributed  system_views         
system       system_schema       system_virtual_schema
```

**Expected behavior**

Commands should execute without warnings, like 3.11.x.

**Environment (please complete the following information):**

* Helm charts version info

```
% helm ls -A
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
k8ssandra       default         1               2021-02-20 07:52:49.995951 -0500 EST    deployed        k8ssandra-0.53.0        3.11.10    
traefik         default         1               2021-02-20 07:52:34.286658 -0500 EST    deployed        traefik-9.14.3          2.4.5     
```

* Helm charts user-supplied values

```
% helm get values k8ssandra
USER-SUPPLIED VALUES:
backupRestore:
  medusa:
    bucketName: jdinoto-k8ssandra-test
    bucketSecret: medusa-bucket-key
    enabled: true
    storage: s3
cassandra:
  clusterName: k8ssandra-cluster
  datacenters:
  - name: dc1
    size: 3
  heap:
    newGenSize: 256M
    size: 500M
  version: 4.0.0
kube-prometheus-stack:
  grafana:
    adminPassword: admin123
    adminUser: admin
    enabled: true
    grafana.ini:
      server:
        root_url: http://localhost:3000/grafana
        serve_from_sub_path: true
    ingress:
      enabled: true
      path: /grafana
  prometheus:
    enabled: true
    ingress:
      enabled: true
      paths:
      - /prometheus
    prometheusSpec:
      externalUrl: http://localhost:9090/prometheus
      routePrefix: /prometheus
reaper:
  ingress:
    enabled: true
    host: repair.127.0.0.1.nip.io
stargate:
  enabled: true
  replicas: 2
```

* Kubernetes version information:

```
% kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.15", GitCommit:"73dd5c840662bb066a146d0871216333181f4b64", GitTreeState:"clean", BuildDate:"2021-01-22T22:45:59Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

Kind

**Additional context**
I would assume this has nothing to do with k8ssandra and is a result of changes in the images deployed for Cassandra with the management-api - so if this issue needs to be move there, we can do that.
