### ISSUE TITLE
Running helm upgrade when auth is enabled can cause a cluster rolling restart

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra#413]
## Bug Report

**Describe the bug**
I observed that scaling my Cassandra cluster up or down via `helm upgrade` when auth and Reaper are enabled (which they are by default) causes a cluster-wide rolling restart after the scaling operation. More specifically, there is a StatefulSet update which has the effect of a rolling restart. I also observed the StatefulSet update doing a `helm upgrade` that made no changes to the CassandraDatacenter.

https://github.com/helm/charts/issues/5167 describes the root of the problem. We auto generate random passwords for secrets. cass-operator watches the secrets for the roles that it creates. When `helm upgrade` runs, the password in the secret changes. This in turns triggers a reconciliation request in cass-operator. I think cass-operator detects a change in the StatefulSet due to this:

```yaml
        env:
        - name: REAPER_JMX_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: test-reaper-secret-k8ssandra
        - name: REAPER_JMX_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: test-reaper-secret-k8ssandra
```

This environment variable is from the podTemplateSpec of the StatefulSet that cass-operator creates. cass-operator add the `cassandra.datastax.com/resource-hash` annotation on the StatefulSet. During reconciliation the operator recreates the StatefulSet based on the current spec. It compares the new hash to the existing hash to determine if anything has changed. If the hashes are different cass-operator updates the StatefulSet

I confirmed the StatefulSet update and hash update simply by enabling Stargate.

**To Reproduce**
1. `helm install test k8ssandra/k8ssandra -f values.yaml`

**values.yaml:**
```yaml
cassandra:
  auth:
    enabled: true
  datacenters:
  - name: dc1
    size: 1
reaper:
  enabled: true
stargate:
  enabled: false
  replicas: 1
```

2. Wait for the CassandraDatacenter to become ready
3. Make a note of the StatefulSet's resource hash 

```
$ kubectl get sts test-dc1-default-sts -o=jsonpath="{.metadata.annotations.cassandra\.datastax\.com\/resource\-hash}"
```

4. Enable Stargate and upgrade
5. `helm upgrade test /k8ssandra/k8ssandra -f values.yaml`

**values.yaml:**
```yaml
cassandra:
  auth:
    enabled: true
  datacenters:
  - name: dc1
    size: 1
reaper:
  enabled: true
stargate:
  enabled: true
  replicas: 1
```

6. Wait a minute or two and repeat step 3.

Note that this happens frequently but not consistently. You may to repeat multiple times to reproduce.

**Expected behavior**
Scaling the cluster should not cause a cluster-wide rolling restart. Apply a `helm upgrade` that does not update the CassandraDatacenter should not cause a StatefulSet update.

* Helm charts version info

`$ helm ls -A` 

0.56.0
