### ISSUE TITLE
Reaper ingress is not working

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra#431]
## Bug Report

**Describe the bug**
Trying to access the reaper web application through the default ingress provided by `reaper.ingress.enabled=true` is not working.

The problem appears to be the name of the reaper service exposing the application, it has two `reaper`s in the name, the ingress rule is expecting 1.

```
% kubectl get ingressroute k8ssandra-reaper -o yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  annotations:
    meta.helm.sh/release-name: k8ssandra
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2021-02-25T05:42:48Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: k8ssandra
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: k8ssandra
    app.kubernetes.io/part-of: k8ssandra-k8ssandra-default
    app.kubernetes.io/version: 3.11.10
    helm.sh/chart: k8ssandra-0.60.0
  name: k8ssandra-reaper
  namespace: default
  resourceVersion: "975"
  selfLink: /apis/traefik.containo.us/v1alpha1/namespaces/default/ingressroutes/k8ssandra-reaper
  uid: 645738a9-39d5-49fd-8481-5d0ebfb37cbc
spec:
  entryPoints:
  - web
  routes:
  - kind: Rule
    match: Host(`repair.127.0.0.1.nip.io`)
    services:
    - kind: Service
      name: k8ssandra-reaper-service
      port: 8080
```

```
% kubectl get services
NAME                                     TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                                                                                                                AGE
cass-operator-metrics                    ClusterIP   10.96.104.208   <none>        8383/TCP,8686/TCP                                                                                                      24m
k8ssandra-cluster-dc1-all-pods-service   ClusterIP   None            <none>        9042/TCP,8080/TCP,9103/TCP                                                                                             24m
k8ssandra-cluster-dc1-service            ClusterIP   None            <none>        9042/TCP,9142/TCP,8080/TCP,9103/TCP,9160/TCP                                                                           24m
k8ssandra-cluster-seed-service           ClusterIP   None            <none>        <none>                                                                                                                 24m
k8ssandra-dc1-stargate-service           ClusterIP   10.96.236.27    <none>        8080/TCP,8081/TCP,8082/TCP,8084/TCP,8085/TCP,9042/TCP                                                                  25m
k8ssandra-grafana                        ClusterIP   10.96.53.23     <none>        80/TCP                                                                                                                 25m
k8ssandra-kube-prometheus-operator       ClusterIP   10.96.124.129   <none>        443/TCP                                                                                                                25m
k8ssandra-kube-prometheus-prometheus     ClusterIP   10.96.97.217    <none>        9090/TCP                                                                                                               25m
k8ssandra-reaper-reaper-service          ClusterIP   10.96.102.236   <none>        8080/TCP                                                                                                               25m
kubernetes                               ClusterIP   10.96.0.1       <none>        443/TCP                                                                                                                26m
prometheus-operated                      ClusterIP   None            <none>        9090/TCP                                                                                                               25m
traefik                                  NodePort    10.96.81.19     <none>        9042:32091/TCP,9142:32092/TCP,8081:30081/TCP,8080:30080/TCP,8082:30082/TCP,9000:32090/TCP,80:32080/TCP,443:32443/TCP   25m
```

**To Reproduce**
1. Deploy Traefik
2. Deploy k8ssandra with `reaper.ingress.enabled=true` and some functional value for `reaper.ingress.host`
3. Attempt to access reaper through a browser
4. Observe a 404

**Expected behavior**
Default ingress to the reaper web interface should allow access via a browser.

**Environment (please complete the following information):**

* Helm charts version info

```
% helm ls -a
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
backup          default         1               2021-02-25 00:51:30.885156 -0500 EST    deployed        backup-0.26.0                      
k8ssandra       default         2               2021-02-25 00:53:23.066031 -0500 EST    deployed        k8ssandra-0.60.0        3.11.10    
restore         default         1               2021-02-25 01:03:25.666224 -0500 EST    deployed        restore-0.27.0                     
traefik         default         1               2021-02-25 00:42:30.399295 -0500 EST    deployed        traefik-9.14.3          2.4.5 
```

* Helm charts user-supplied values

```
% helm get values k8ssandra
USER-SUPPLIED VALUES:
cassandra:
  auth:
    superuser:
      username: adminc
  clusterName: k8ssandra-cluster
  datacenters:
  - name: dc1
    size: 1
  heap:
    newGenSize: 256M
    size: 500M
  version: 3.11.10
kube-prometheus-stack:
  grafana:
    adminPassword: admin123
    adminUser: admin
    enabled: true
    grafana.ini:
      server:
        root_url: http://localhost:3000/grafana
        serve_from_sub_path: true
    ingress:
      enabled: true
      path: /grafana
  prometheus:
    enabled: true
    ingress:
      enabled: true
      paths:
      - /prometheus
    prometheusSpec:
      externalUrl: http://localhost:9090/prometheus
      routePrefix: /prometheus
medusa:
  bucketName: jdinoto-k8ssandra-test
  cassandraUser:
    secret: medusa-user
  enabled: true
  storage: s3
  storage_properties:
    region: us-east-1
  storageSecret: medusa-bucket-key
reaper:
  cassandraUser:
    username: adminr
  ingress:
    enabled: true
    host: repair.127.0.0.1.nip.io
  jmx:
    username: adminrj
stargate:
  cassandraUser:
    username: admins2
  enabled: true
  ingress:
    enabled: true
  replicas: 1
```

* Kubernetes version information:

```
% kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.15", GitCommit:"2adc8d7091e89b6e3ca8d048140618ec89b39369", GitTreeState:"clean", BuildDate:"2021-01-22T22:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:
Kind with config:

```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: k8ssandra
nodes:
- role: worker
- role: worker
- role: worker
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 32080
    hostPort: 8080
    protocol: TCP
  - containerPort: 32443
    hostPort: 8443
    protocol: TCP
  - containerPort: 32090
    hostPort: 9000
    protocol: TCP
  - containerPort: 30081
    hostPort: 8081
    protocol: TCP
  - containerPort: 30082
    hostPort: 8082
    protocol: TCP
  - containerPort: 32091
    hostPort: 9042
    protocol: TCP
  - containerPort: 32092
    hostPort: 9142
    protocol: TCP
```

```
% k get nodes
NAME                      STATUS   ROLES    AGE   VERSION
k8ssandra-control-plane   Ready    master   36m   v1.16.15
k8ssandra-worker          Ready    <none>   36m   v1.16.15
k8ssandra-worker2         Ready    <none>   36m   v1.16.15
k8ssandra-worker3         Ready    <none>   36m   v1.16.15
```
