### ISSUE TITLE
Scaling out after a restore results in new pods that cannot run

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra#461]
## Bug Report

**Describe the bug**

**To Reproduce**
1. `helm install test k8ssandra/k8ssandra -f values.yaml`

**values.yaml:**
```yaml
cassandra:
  clusterName: scaletest
  version: "3.11.10"
  heap:
    size: "1024M"
  auth:
    enabled: false
  datacenters:
  - name: dc1
    size: 2
reaper:
  enabled: false
medusa:
  enabled: true
  bucketName: my-bucket
  storageSecret: my-storage-secret
  storage: s3
  storage_properties:
    region: us-east-1
stargate:
  enabled: false
```
2. Wait for Cassandra cluster to become ready
3. Perform a backup, e.g., `helm install backup-test k8ssandra/k8ssandra -f backup-values.yml`

**backup-values.yaml:**
```yaml
name: backup-1
cassandraDatacenter:
  name: dc1
```

4. Wait for backup to complete. Monitor the progress with `kubectl get cassandrabackup backup-1 -o yam`. The status should look like this when it is done:

```yaml
status:
  cassdcTemplateSpec:
    # omitted for brevity
  finishTime: "2021-02-26T22:07:49Z"
  finished:
  - scaletest-dc1-default-sts-1
  - scaletest-dc1-default-sts-0
  startTime: "2021-02-26T22:07:25Z"
```

5. Scale out the cluster, `helm upgrade test k8ssandra/k8ssandra -f upgrade-values.yaml`

**upgrade-values.yaml:**
```yaml
cassandra:
  clusterName: scaletest
  version: "3.11.10"
  heap:
    size: "1024M"
  auth:
    enabled: false
  datacenters:
  - name: dc1
    size: 3
reaper:
  enabled: false
medusa:
  enabled: true
  bucketName: my-bucket
  storageSecret: my-storage-secret
  storage: s3
  storage_properties:
    region: us-east-1
stargate:
  enabled: false
```
6. Wait for the new Cassandra pod to become ready
7. Do a restore, `helm install restore-test k8ssandra/k8ssandra -f restore-values.yaml`

**restore-values.yaml:**
```yaml
name: restore-1
backup:
  name: backup-1
cassandraDatacenter:
  name: dc1
  clusterName: k8ssandra
inPlace: true
shutdown: false
```

8. It may take a few minutes for the `test-dc1-default-sts-2` pod to terminate and restart. When it does, check the logs of the `medusa-restore` container with `kubectl logs test-dc1-default-sts-2 -c medusa-restore`. The output will report this:

```
ERROR: No such backup
```

The `medusa-restore` container will be stuck in a CrashLoopBackoff, thus preventing the `cassandra` container from ever starting.

**Expected behavior**
The restore should run without error. There should be no restore attempted on `test-dc1-default-sts-2` since it did not exist at the time that the backup was created.

* Helm charts version info

1.0.0

**Additional context**

Two env vars get set on the `medusa-restore` container - `BACKUP_NAME` and `RESTORE_KEY`. The latter is a uuid generated by medusa-operator. When a restore is performed that uuid is written out to `/var/lib/cassandra/.last-restore`.
The entry point script for the container looks for the uuid in `/var/lib/cassandra/.last-restore`. If it is found and it matches `RESTORE_KEY` then no restore is performed. In this scenario though the file does not exist and the container will try to perform the restore operation. And course it fails the because there is no backup for this newly added C* node
