### ISSUE TITLE
How to setup medusa with k8ssandra??

### ISSUE THREAD

**Issue by AkashRajvanshi** [k8ssandra/k8ssandra#463]
**Type of question**

# Backup/restore-related question 
Hey, I follow the official getting started doc to set up a test backup restore Cassandra-cluster. -> https://k8ssandra.io/docs/topics/restore-a-backup/. but it will not run a medusa pod.

```bash
$ kubectl get pods
NAME                                                   READY   STATUS      RESTARTS   AGE
demo-cass-operator-b8d465c9f-t8qbx                     1/1     Running     0          7m12s
demo-dc1-default-sts-0                                 2/2     Running     0          6m56s
demo-dc1-stargate-8dfbc44b8-frmq5                      1/1     Running     0          7m12s
demo-grafana-6d58c8578-7gpnb                           2/2     Running     0          7m12s
demo-kube-prometheus-stack-operator-8574b9dbc4-4vvt5   1/1     Running     0          7m12s
demo-reaper-686774478c-95xpg                           1/1     Running     0          5m4s
demo-reaper-operator-6c8cbbf45-pnrxq                   1/1     Running     0          7m12s
demo-reaper-schema-6rxmq                               0/1     Completed   0          5m14s
prometheus-demo-kube-prometheus-stack-prometheus-0     2/2     Running     1          7m10s
```
how should I resolve this issue??

**What did you do?**

**Did you expect to see some different?**

**Environment**

* Helm charts version
1.0.0

**Comment by jsanda** [comment]
Hi @AkashRajvanshi 

It looks like the docs need to be updated. The chart configuration for the example should be:

```yaml
cassandra:
  datacenters:
  - name: dc1
    size: 3
medusa:
  enabled: true
   bucketName: k8ssandra-bucket-dev
   storageSecret: medusa-bucket-key
   storage: s3
   storage_properties:
     region: us-east-1
```

I will update the docs.
