### ISSUE TITLE
Minio/S3 compatible backends support is broken

### ISSUE THREAD

**Issue by adejanovski** [k8ssandra/k8ssandra#487]
## Bug Report

**Describe the bug**
It is not possible to correctly set the storage backend credentials for s3 compatible implementations as the current helm charts [only consider GCS and AWS S3](https://github.com/k8ssandra/k8ssandra/blob/v1.0.0/charts/k8ssandra/templates/medusa/medusa-config.yaml#L34-L38).

**To Reproduce**
Enable Medusa using Minio as a backend with the following values:

```
medusa:
  enabled: true

  multiTenant: true
  storage: s3_compatible

  storage_properties:
      port: 9000
      secure: "False"

  bucketName: k8ssandra-medusa
  storageSecret: medusa-bucket-key
```

Create a secret with the appropriate credentials:

```
apiVersion: v1
kind: Secret
metadata:
 name: medusa-bucket-key
type: Opaque
stringData:
 # Note that this currently has to be set to medusa_s3_credentials!
 medusa_s3_credentials: |-
   [default]
   aws_access_key_id = minio_key
   aws_secret_access_key = minio_secret
```

The Medusa container will fail to start due to a connection error to Minio as the credentials file cannot be found.

**Expected behavior**
The Medusa container should start nicely and connect to Minio if the secret is present.

**Environment (please complete the following information):**

* Helm charts version info

`1.0.0`  

* Kubernetes cluster kind:

kind
