### ISSUE TITLE
Make Cassandra JVM heap settings configurable

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra#50]
**Is your feature request related to a problem? Please describe.**
Users should be able to configure Cassandra's JVM heap settings with the k8ssandra-cluster helm chart. 

Here is an example `CassandraDatacenter` manifest that includes heap settings:

```yaml
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: k8ssandra-test
spec:
  clusterName: cluster1
  serverType: cassandra
  serverVersion: "3.11.7"
  managementApiAuth:
    insecure: {}
  size: 3
  storageConfig:
    cassandraDataVolumeClaimSpec:
      storageClassName: server-storage
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
  config:
    jvm-options:
      initial_heap_size: "800M"
      max_heap_size: "800M"
```

**Describe the solution you'd like**
There should be properties in the k8ssandra-cluster chart along with reasonable defaults that are consistent with Cassandra best practices. 

**Describe alternatives you've considered**

**Additional context**
Note that the value of the `config` property is actually just treated as raw JSON. This means that it is essentially an opaque blob to cass-operator.
