### ISSUE TITLE
Cant login with super user creds

### ISSUE THREAD

**Issue by slayerjain** [k8ssandra/k8ssandra#503]
## Bug Report

**Describe the bug**
Not able to login via superuser creds.
**To Reproduce**
1. Installed a fresh K8ssandra on EKS, along with other K8ssandra in other namespaces. 
2. Used dedicated nodes, so they've never restarted after creation. 
3. After few hours not able to login anymore with root creds. 
4. err:
`root@bash-7:/# cqlsh k8ssandra-k8s-dc2-service.k8ssandra-flux -u k8ssandra-superuser -p *password*
Connection error: ('Unable to connect to any servers', {'192.168.145.245': AuthenticationFailed('Failed to authenticate to 192.168.145.245: Error from server: code=0100 [Bad credentials] message="Provided username k8ssandra-superuser and/or password are incorrect"',), '192.168.132.190': AuthenticationFailed('Failed to authenticate to 192.168.132.190: Error from server: code=0100 [Bad credentials] message="Provided username k8ssandra-superuser and/or password are incorrect"',), '192.168.155.231': AuthenticationFailed('Failed to authenticate to 192.168.155.231: Error from server: code=0100 [Bad credentials] message="Provided username k8ssandra-superuser and/or password are incorrect"',)})`
5. tried nodetool repair
6. I was able to login for 5-10 mins, but then the same error soon after - cant login anymore. Maybe the node tool repair was unrelated, not sure. 

**Expected behavior**
Normal login
**Screenshots**

**Environment (please complete the following information):**

* Helm charts version info

`$ helm ls -A` 

```
k8ssandra-backup          	k8ssandra-flux	4       	2021-03-02 20:19:13.918109289 +0000 UTC	deployed	backupcronv2-0.1.0      	1.16.0
k8ssandra-cluster-flux    	k8ssandra-flux	7       	2021-03-02 19:57:24.974720292 +0000 UTC	deployed	k8ssandra-1.0.0
```

* Helm charts user-supplied values

`$ helm get values RELEASE_NAME` 
```
USER-SUPPLIED VALUES:
cassandra:
  cassandraLibDirVolume:
    size: 100Gi
    storageClass: gp2
  clusterName: k8ssandra
  datacenters:
  - name: k8s-dc2
    num_tokens: 256
    racks:
    - name: r1
    - name: r2
    - name: r3
    size: 3
  resources: {}
  version: 3.11.7
kube-prometheus-stack:
  enabled: false
medusa:
  bucketName: k8s-staging
  bucketSecretProvided: false
  enabled: true
  storage: s3
  storage_properties:
    region: us-west-2
  storageSecret: ""
stargate:
  enabled: false
  ```

* Kubernetes version information:

`kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-14T05:15:04Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: EKS via eksctl

**Additional context**
