### ISSUE TITLE
Make racks configurable

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra#54]
**Is your feature request related to a problem? Please describe.**
Users should be able to configure the racks of a `CassandraDatacenter`. Here is an example manifest:

```yaml
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: k8ssandra-test
spec:
  clusterName: cluster1
  serverType: cassandra
  serverVersion: "3.11.7"
  managementApiAuth:
    insecure: {}
  size: 3
  storageConfig:
    cassandraDataVolumeClaimSpec:
      storageClassName: server-storage
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
  racks:
    - name: rack1
      zone: us-central1-a
    - name: rack2
      zone: us-central1-b
    - name: rack3
      zone: us-central1-c
```

**Describe the solution you'd like**
The `racks` property of `CassandraDatacenter` should support templated values in the [cassdc.yaml](https://github.com/k8ssandra/k8ssandra/blob/main/charts/k8ssandra-cluster/templates/cassdc.yaml) template.
