### ISSUE TITLE
Expose configuration of additionalSeeds

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra#547]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
cass-operator allows for the configuration of  ` additionalSeeds` for each DC, we'd like to be able to chart this out via k8ssandra.

**Describe alternatives you've considered**
```
  datacenters:
  -
    name: dc1
    additionalSeeds: []
```
**Additional context**
This is generally for broader support of multi-cluster deployments.
