### ISSUE TITLE
How to get multi DC environment created? 

### ISSUE THREAD

**Issue by navjyotnishant** [k8ssandra/k8ssandra#566]
**Type of question**

 How to perform a particular operation 

**What did you do?**
Tried to spin up K8ssandra 2 DC with 3 node in each.

```
cassandra:
  version: "4.0.0"
  cassandraLibDirVolume:
    storageClass: local-path
    size: 5Gi
  allowMultipleNodesPerWorker: true
  heap:
   size: 1G
   newGenSize: 1G
  resources:
    requests:
      cpu: 1000m
      memory: 2Gi
    limits:
      cpu: 1000m
      memory: 2Gi
  datacenters:
  - name: k8s-dc1
    size: 3
    racks:
    - name: default
  - name: k8s-dc2
    size: 3
    racks:
    - name: default
kube-prometheus-stack:
  grafana:
  adminUser: admin
  adminPassword: admin
stargate:
  enabled: true
  replicas: 1
  heapMB: 256
  cpuReqMillicores: 200
  cpuLimMillicores: 1000


```

`helm install -f k8ssandra.yaml k8ssandra k8ssandra/k8ssandra`

Above command only create `k8s-dc1` DC and corresponding pods for 3 nodes.

**Did you expect to see some different?**
I would expect 2 DC to be created with 3 node in each DC.

**Environment**
DEV

* Helm charts version
` k8ssandra-1.0.0`

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-59) by [Unito](https://www.unito.io)
