### ISSUE TITLE
Grafana dashboard admin user password not working

### ISSUE THREAD

**Issue by hesh-bit** [k8ssandra/k8ssandra#567]
**Describe the bug**
I am setting up a POC environment of K8ssandra with guidelines from [Quick Start](https://k8ssandra.io/docs/getting-started/)

tried combinations:
- admin:admin
- admin:admin123
- admin:secret

**To Reproduce**
1. Go to grafana dashboard
2. put credentials
3. See error

**Expected behavior**
it should login and take me to dashboard home

* Helm charts version info
K8ssandra-1.0.0

* Helm charts user-supplied values

**scenario 1**
```
  datacenters:
  - name: dc1
    size: 1
    racks:
    - name: default
kube-prometheus-stack:
  grafana:
  adminUser: admin
  adminPassword: admin123
```
**output**
`username/password incorrect`

**scenario 2**
```
  datacenters:
  - name: k8s-vdc3
    size: 3
    racks:
    - name: default
kube-prometheus-stack:
  grafana:
  adminUser: admin
  adminPassword: admin
```
**output**
`username/password incorrect`

* Kubernetes cluster kind:
kubeadm

workaround I did to get thing rolling:

```
bin\bash to grafana pod
grafana-cli admin reset-admin-password admin123
```

then was able to login with admin:admin123 combination.

**Comment by jsanda** [comment]
Hi @hesh-bit 

I think you have an indentation error. `adminUser` and `adminPassword` need to be indented under `grafana`, e.g.:

```yaml
  datacenters:
  - name: k8s-vdc3
    size: 3
    racks:
    - name: default
kube-prometheus-stack:
  grafana:
    adminUser: admin
    adminPassword: admin
```
