### ISSUE TITLE
K8SSAND-55 ⁃ Investigate issues when running the full stack ITs in GHA

### ISSUE THREAD

**Issue by adejanovski** [k8ssandra/k8ssandra#582]
The full stack test suite currently fails in GHA due to disk space constraints: https://github.com/k8ssandra/k8ssandra/actions/runs/678853748

We should investigate what's eating up all the disk space and come up with some optimizations to allow the suite to run.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-55) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-55
┆priority: Medium

**Comment by burmanm** [comment]
On Ubuntu latest, the following gives you more disk space:

```yaml
      - name: Remove unused packages from disk
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet
```
