### ISSUE TITLE
K8SSAND-54 ⁃ Specify the number of seeds and nodes with k8ssandra chart

### ISSUE THREAD

**Issue by debjitk** [k8ssandra/k8ssandra#583]
How can we specify the number of seeds and nodes with k8ssandra chart ?

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-54) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-54
┆priority: Medium

**Comment by jsanda** [comment]
Hi @debjitk 

The seeds are automatically calculated and assigned by cass-operator. If cluster size < 3, then seeds == cluster size. If num_racks > 3, then num_seeds = num_racks.

You specify the number of nodes at the DC-level, e.g.:

```yaml
# my-values.yaml
cassandra:
  clusterName: example
  datacenters:
  - name: dc1
    size: 9
````

Hope that helps.
