### ISSUE TITLE
Fix getting-started docs - indentation for Grafana

### ISSUE THREAD

**Issue by jeffbanks** [k8ssandra/k8ssandra#584]
## Bug Report

**Describe the bug**
Fix indentation in getting-started docs for Grafana.

```yaml
cassandra:
  version: "3.11.10"
  cassandraLibDirVolume:
    storageClass: server-storage
    size: 5Gi
  allowMultipleNodesPerWorker: true
  heap:
   size: 1G
   newGenSize: 1G
  resources:
    requests:
      cpu: 1000m
      memory: 2Gi
    limits:
      cpu: 1000m
      memory: 2Gi
  datacenters:
  - name: dc1
    size: 3
    racks:
    - name: default
kube-prometheus-stack:
  grafana:
  adminUser: admin <-------------------------- NEEDS TO BE INDENTED.
  adminPassword: admin123 <----------------- NEEDS TO BE INDENTED.
stargate:
  enabled: true
  replicas: 1
  heapMB: 256
  cpuReqMillicores: 200
  cpuLimMillicores: 1000
```
