### ISSUE TITLE
K8ssandra backup to S3 via Medusa

### ISSUE THREAD

**Issue by navjyotnishant** [k8ssandra/k8ssandra#596]
**Type of question**

 Backup/restore-related question

**What did you do?**
Followed document https://k8ssandra.io/docs/topics/restore-a-backup/ in order to setup backup/restore. Is documentation up to date? 
**Did you expect to see some different?**
I expect to see medusa container running under cassandra node pods. but I do see only 2 container instead of 3. medusa container is not being created.

```
kubectl logs k8ssandra-dc1-default-sts-0 -c medusa
error: container medusa is not valid for pod k8ssandra-dc1-default-sts-0
```

```
 kubectl get pods
NAME                                                READY   STATUS      RESTARTS   AGE
k8ssandra-cass-operator-7d5df6d49-5hvpk             1/1     Running     0          98m
k8ssandra-dc1-default-sts-0                         2/2     Running     0          98m
k8ssandra-dc1-default-sts-1                         2/2     Running     0          91m
k8ssandra-dc1-default-sts-2                         2/2     Running     0          91m
k8ssandra-dc1-stargate-644f7fd75b-2w944             1/1     Running     0          98m
k8ssandra-grafana-679b4bbd74-lt9gb                  2/2     Running     0          15m
k8ssandra-kube-prometheus-operator-85695ffb-2vwqj   1/1     Running     0          98m
k8ssandra-medusa-operator-798567d685-7t52p          1/1     Running     0          15m
k8ssandra-reaper-7bb77d575c-clxrs                   1/1     Running     0          97m
k8ssandra-reaper-operator-79fd5b4655-h2p74          1/1     Running     0          98m
k8ssandra-reaper-schema-bqhfd                       0/1     Completed   0          97m
prometheus-k8ssandra-kube-prometheus-prometheus-0   2/2     Running     1          98m

```

**Environment**

DEV

* Helm charts version
1.0.0

**Comment by jsanda** [comment]
Hi @navjyotnishant 

Did you use the example `backup-restore-values.yaml` file in the docs? It actually has an indentation bug that will cause a CrashLoopBackOff in the Cassandra pod.

Can I see the output of `helm get values k8ssandra`?

**Comment by hesh-bit** [comment]
`helm get values k8ssandra`
```
USER-SUPPLIED VALUES:
cassandra:
  datacenters:
  - name: dc1
    size: 3
medusa:
  bucketName: ******
  enabled: true
  storage: s3
  storage_properties:
    region: us-east-1
  storageSecret: medusa-bucket-key
```

**Comment by jsanda** [comment]
Those properties look good now. Let's take a look at the what exactly Helm installed. Run `helm get manifest k8ssandra`. That will output all of the yaml files that Helm generates. I suggest redirecting to a file. I would like to see the manifest for the CassandraDatacenter object which will be named `dc1`.

**Comment by hesh-bit** [comment]
here the output specific to **CassandraDatacenter**, I have masked some keywords/links.

```
# Source: k8ssandra/templates/cassandra/cassdc.yaml
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: dc1
  labels:
    app.kubernetes.io/name: k8ssandra
    helm.sh/chart: k8ssandra-1.0.0
    app.kubernetes.io/instance: k8ssandra
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: k8ssandra-k8ssandra-default
  annotations:
    reaper.cassandra-reaper.io/instance: k8ssandra-reaper
spec:
  clusterName: k8ssandra
  serverType: cassandra
  serverVersion: "3.11.10"
  dockerImageRunsAsCassandra: true
  serverImage: datastax/cassandra-mgmtapi-3_11_10:v0.1.22
  managementApiAuth:
    insecure: {}
  size: 3
  storageConfig:
    cassandraDataVolumeClaimSpec:
      storageClassName: standard
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
  allowMultipleNodesPerWorker: false
  users:
    - secretName: k8ssandra-reaper
      superuser: true
    - secretName: k8ssandra-medusa
      superuser: true
    - secretName: k8ssandra-stargate
      superuser: true
  config:
    cassandra-yaml:
      num_tokens: 256
      authenticator: PasswordAuthenticator
      authorizer: CassandraAuthorizer
      role_manager: CassandraRoleManager
      roles_validity_in_ms: 3.6e+06
      roles_update_interval_in_ms: 3.6e+06
      permissions_validity_in_ms: 3.6e+06
      permissions_update_interval_in_ms: 3.6e+06
      credentials_validity_in_ms: 3.6e+06
      credentials_update_interval_in_ms: 3.6e+06
    jvm-options:
      additional-jvm-opts:
        - "-Dcassandra.system_distributed_replication_dc_names=dc1"
        - "-Dcassandra.system_distributed_replication_per_dc=3"
  podTemplateSpec:
    spec:
      initContainers:
      - name: server-config-init
      - name: jmx-credentials
        image: busybox
        imagePullPolicy: IfNotPresent
        env:
          - name: REAPER_JMX_USERNAME
            valueFrom:
              secretKeyRef:
                name: k8ssandra-reaper-jmx
                key: username
          - name: REAPER_JMX_PASSWORD
            valueFrom:
              secretKeyRef:
                name: k8ssandra-reaper-jmx
                key: password
          - name: SUPERUSER_JMX_USERNAME
            valueFrom:
              secretKeyRef:
                name: k8ssandra-superuser
                key: username
          - name: SUPERUSER_JMX_PASSWORD
            valueFrom:
              secretKeyRef:
                name: k8ssandra-superuser
                key: password
        args:
          - /bin/sh
          - -c
          - echo "$REAPER_JMX_USERNAME $REAPER_JMX_PASSWORD" > /config/jmxremote.password && echo "$SUPERUSER_JMX_USERNAME $SUPERUSER_JMX_PASSWORD" >> /config/jmxremote.password
        volumeMounts:
          - mountPath: /config
            name: server-config
      - name: get-jolokia
        image: busybox
        args:
          - /bin/sh
          - -c
          - wget -O  /config/***********
        volumeMounts:
          - mountPath: /config
            name: server-config
      - name: medusa-restore
        image: docker.io/k8ssandra/medusa:0.9.0
        imagePullPolicy: IfNotPresent
        env:
          - name: MEDUSA_MODE
            value: RESTORE
          - name: CQL_USERNAME
            valueFrom:
              secretKeyRef:
                name: k8ssandra-medusa
                key: username
          - name: CQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: k8ssandra-medusa
                key: password
        volumeMounts:
          - name: k8ssandra-medusa
            mountPath: /etc/medusa
          - name: server-config
            mountPath: /etc/cassandra
          - mountPath: /var/lib/cassandra
            name: server-data
          - name:  ***********
            mountPath: /etc/***********
      containers:
      - name: cassandra
        env:
          - name: LOCAL_JMX
            value: "no"
          - name: JVM_EXTRA_OPTS
            value: -javaagent:/etc/cassandra/******************
        volumeMounts:
          - name: cassandra-config
            mountPath: /etc/cassandra
      - name: medusa
        image: docker.io/k8ssandra/medusa:0.9.0
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: **********
        env:
          - name: MEDUSA_MODE
            value: GRPC
          - name: CQL_USERNAME
            valueFrom:
              secretKeyRef:
                name: k8ssandra-medusa
                key: username
          - name: CQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: k8ssandra-medusa
                key: password
        readinessProbe:
          exec:
            command: [ "/bin/grpc_health_probe", "-addr=:******" ]
          initialDelaySeconds: 5
        livenessProbe:
          exec:
            command: [ "/bin/grpc_health_probe", "-addr=:*****" ]
          initialDelaySeconds: 10
        volumeMounts:
          - name: k8ssandra-medusa
            mountPath: /etc/medusa
          - name: cassandra-config
            mountPath: /etc/cassandra
          - mountPath: /var/lib/cassandra
            name: server-data
          - mountPath: /etc/medusa-secrets
            name: **************
      volumes:
      - name: k8ssandra-medusa
        configMap:
          name: k8ssandra-medusa
          items:
            - key: medusa.ini
              path: medusa.ini
      - name: cassandra-config
        emptyDir: {}
      - name:  **********
        secret:
          secretName: ***********
```
