### ISSUE TITLE
migration from cass-operator to k8ssandra

### ISSUE THREAD

**Issue by andyallred** [k8ssandra/k8ssandra#669]
I have multiple cassandra clusters running with the cass-operator, and I cannot lose the data in those clusters. I also need to avoid any downtime, to the extent possible. They are all in EKS hosted kubernetes clusters.

An upgrade path or document, of how to import cass-operator based clusters into a 'full' k8ssandra setup would be needed.

One idea could be to create a new cluster in k8ssandra and then sync the data between clusters, and then 'just' swap the k8s service to point to new cluster. 

Avoiding any data loss, and minimizing downtime would be the highest priority. Temporarily using more resources would not be an issue in my use case.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-39) by [Unito](https://www.unito.io)

**Comment by jsanda** [comment]
Hi @andyallred 

Thanks for creating the ticket!

We recently added docs on migrating a cluster (that is already running in k8s) to k8ssandra. You can check that out [here](https://k8ssandra.io/docs/topics/migration/). Given you are already using cass-operator, I think we can avoid doing a full DC migration.

I did a bit of research on this. It does not look like Helm provides a way to add existing objects (e.g., CassandraDatacenter, cass-operator deployment, etc.) to an existing release. I think we might be able work around it by adding the appropriate labels.

We need to do some further investigation and testing in order to verify that adding labels and then running a `helm upgrade` will work.

**Comment by johnsmartco** [comment]
Thanks @andyallred and John @jsanda.  Just noting that I'm following this conversation and we'll update the [docs](https://k8ssandra.io/docs/topics/migration/) with recommendations, as needed, after the investigation is completed.

**Comment by jsanda** [comment]
I looked into this some more. https://github.com/helm/helm/pull/7649 makes it possible by adding some annotations and labels to the CassandraDatacenter (or other objects that you want to add to the Helm release). It can be done without down time as well. That's the good news :)

Now for the less than good news. k8ssandra does not completely expose all the properties in the CassandraDatacenter spec. This is by design. More properties will be exposed, but we want to be prescriptive how we go about it. k8ssandra already applies a lot advanced configuration changes to the CassandraDatacenter in support of thing like authentication, repairs with Reaper, and backup/restore with Medusa. The changes inhttps://github.com/helm/helm/pull/7649 add 3-way merge logic such that whatever you have defined in your spec will be merged with what you apply through Helm. In practice this means you will end up with a CassandraDatacenter that deviates from the k8ssandra prescription. This could make upgrade more complicated over time. 

My recommendation would be to do a diff of your existing datacenter spec against what will be created by Helm. You can run `helm template <release-name> k8ssandra/k8ssandra` for example to get the manifests that Helm will generate. I would go through the diff to determine what changes you want and then apply them.

If you can tolerate down time, I would do the following:

* Uninstall cass-operator
* Remove the finalizer from the CassandraDatacenter
* Delete the CassandraDatacenter
    * PVCs will remain intact
* Install k8ssandra using the right naming so that pods bind to existing PVCs

There are pros and cons to this. Some configuration settings that you currently use might not yet be exposed in k8ssandra. You would also incur some down time. On the pros side, you would be following the k8ssandra prescription so to speak, eliminating potential upgrade issues that you might face with the above approach.

@andyallred  I am happy to provide more details on both approaches, but I wanted to go ahead and provide a quick summary of my findings thus far. Let me know what you think.

**Comment by jsanda** [comment]
After further testing, I cannot recommend _adopting_ an existing CassandraDatacenter with the solution described in https://github.com/helm/helm/pull/7649. The merge semantics results in some but not all of the changes should be applied by k8ssandra.

I enabled Reaper and then ran a `helm upgrade` after I had already adopted a CassandraDatacenter that was created outside of k8ssandra. It resulted in Cassandra pods that failed to create. This was due to a missing volume. Helm merged in the init containers that k8ssandra adds, but it failed to merge the volume that the init containers mount. This prevented the pods from being created. The missing volume can be addressed relatively easily. It is future upgrades to newer versions of k8ssandra that have me concerned.

Due to these concerns I recommend doing a datacenter migration as described here https://docs.k8ssandra.io/tasks/migrate/. This approach avoids downtime.

If you can tolerate downtime, there is another, relatively easy solution:

* Delete/uninstall cass-operator
* Remove the finalizer from the CassandraDatacenter
* Delete the CassandraDatacenter
    * PVCs remain intact
* Change the `persistentVolumeReclaimPolicy` on each PV to `Retain`
* Delete the PVCs
* Create a new PVC for each PV
    * The PVC names need to be of the form `server-data-<cluster-name>-<datacenter-name>-<rack-name>-sts-n` where `n` is the pod's ordinal index in the statefulset. Note that names here need to match the names you will use in the new cluster. 
    * Update the `claimRef` in each PV to bind it to the new PVC   

@johnsmartco for the docs, I think we just need to add a blurb that if you are migrating from cass-operator https://docs.k8ssandra.io/tasks/migrate/ is the recommended approach.

@andyallred I am going to close the ticket. If you have additional questions, please feel free to reopen or create news tickets.

**Comment by andyallred** [comment]
https://docs.k8ssandra.io/tasks/migrate/  assumes clients can be modified. We have dozens of clients, maintained by different teams. That's not really an option. 

I'll test the other recommended solution, and try to minimize the downtime.

**Comment by jsanda** [comment]
I am opening this back up for some further investigation Someone suggested the `--force` option for `helm upgrade`. A quick test shows that might be a viable option. I will report back with more updates after I  get a chance to do some more testing.

**Comment by jsanda** [comment]
I am going to provide steps for migrating without downtime. It will involve updates to your CassandraDatacenter spec. That is unavoidable.

# Migration Steps
This outlines steps I tested for migrated a Cassandra cluster managed with Cass Operator to K8ssandra.

# Setup
I installed cass-operator via Helm. I then created my CassandraDatacenter with `kubectl apply` using this manifest:

```yaml
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: dc1
spec:
  clusterName: test
  config:
    cassandra-yaml:
      authenticator: PasswordAuthenticator
      authorizer: CassandraAuthorizer
      roles_update_interval_in_ms: 60000
      max_hint_window_in_ms: 4080000
      max_hints_file_size_in_mb: 256
      tombstone_warn_threshold: 5000
      compaction_throughput_mb_per_sec: 128
    jvm-options:
      initial_heap_size: 512M
      max_heap_size: 512M
  size: 1
  storageConfig:
    cassandraDataVolumeClaimSpec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      storageClassName: standard
  serverType: cassandra
  serverVersion: 3.11.7
  disableSystemLoggerSidecar: true      
```
## Verify superuser secret
cass-operator creates a default superuser. It stores the credentials in a secret named `<clusterName>-superuser`. For this example there should be a secret named `test-usperuser`. We will need to reference this secret later.

# Uninstall cass-operator
This needs to be done because cass-operator will be reinstalled with k8ssandra. Uninstalling cass-operator will **not** delete the CassandraDatacenter or any Cassandra pods. How you delete it depends on how you installed it. Since I installed with Helm, I use `helm uninstall`.

# Install k8ssandra 
We initially install k8ssandra with virtually everything disabled. We do this so that we can first verify that the CassandraDatacenter is added to the release and it looks the way we expect it to.

Use the following chart properties:

```yaml
# migration-values.yaml

cassandra:  
  enabled: false
  
  # version:

  # clusterName:

  # num_tokens:  
  
  # auth:
  #  enabled: false
  #  superuser:
  #    secret: test-superuser

  # datacenters:
  # - name: dc1
  #    size: 1
  #    racks:

stargate:
  enabled: false
reaper:
  enabled: false
kube-prometheus-stack:
  enabled: true
cass-operator:
  enabled: false
reaper-operator:
  enabled: false
```
Make sure to uncomment and set all of the properties under `cassandra` to the same values in your CassandraDatacenter spec. It is critical that they are the same; otherwise, your cluster may stop functioning!

Also make sure to keep Cassandra disabled for now.

Now run install with:

```
helm install test k8ssandra/k8ssandra -f migration-values.yaml
```

At this point the CassandraDatacenter is not yet part of the Helm release.

# Add annotations and labels
The following annotations and label need to be added to the CassandraDatacenter in order for it to be adopted into the Helm release.

```yaml
annotations:
  meta.helm.sh/release-name: test
  meta.helm.sh/release-namespace: default
  #reaper.cassandra-reaper.io/instance: test-reaper

labels:
  app.kubernetes.io/managed-by: Helm
```

**Note:** Adjust the values based on the actual name of your CassandraDatacenter and the namespace in which it is deployed.

These can be added with `kubectl patch` as follows:

```
$ kubectl patch cassdc dc1 --type merge -p '{"metadata": {"annotations": {"meta.helm.sh/release-name": "test", "meta.helm.sh/release-namespace": "default"}, "labels": {"app.kubernetes.io/managed-by": "

# Prepare for upgrade
Enable Cassandra in `migration-values.yaml` with:

```yaml
cassandra:
  enabled: true
```

Run the following:

```
helm upgrade test k8ssandra/k8ssandra -f migrate-values.yaml --force --dry-run
```
Carefully inspect the output, paying close attention to the CassandraDatacenter as it will be different from what you currently have deployed.

The `--force` option is necessary in order for Helm to apply k8ssandra's changes to the CassandraDatacenter.

# Perform upgrade
```
helm upgrade test k8ssandra/k8ssandra -f migrate-values.yaml --force 
```

## Check CassandraDatacenter spec

The spec should not have changed. Verify this with `kubectl get cassdc dc1 -o yaml`.

# Enable cass-operator
Make the following change in `migration-values.yaml`:

```yaml
cass-operator:
  enabled: true
```

Now perform another upgrade:

```
$ helm upgrade test k8ssandra/k8ssandra -f migration-values.yaml
```

Once cass-operator starts, you should see a rolling update of your Cassandra pods. 

# Conclusion
At this point the migration is complete. You can now proceed to enable the other K8ssandra components.
