### ISSUE TITLE
An in-place restore that shuts down the cluster will cause a rolling restart

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra#671]
## Bug Report

**Describe the bug**
I was working on some automated tests for backup/restore where the restore operation is configured to first shutdown the CassandraDatacenter. I observed an additional restart of the Cassandra pods.

**To Reproduce**

1. Install k8ssandra with backup/restore enabled - `helm install test k8ssandra/k8ssandra -f values.yaml`

```yaml
# values.yaml
cassandra:
  heap:
    size: 768M
    newGenSize: 256M
  resources:
    requests:
      cpu: 1
      memory: 1600Mi
    limits:
      cpu: 1
      memory: 1600Mi
  datacenters:
  - name: dc1
    size: 3
    #racks:
    #- name: r1
    #- name: r2
  loggingSidecar:
    enabled: false
medusa:
  enabled: true
  storage: s3
  bucketName: my-bucket
  storageSecret: medusa-bucket-key
  storage_properties:
    region: us-east-1
```

1. Wait for CassandraDatacenter to become ready
1. Create a backup - `helm install backup-test -f backup-values.yaml`

```yaml
# backup-values.yaml
name: backup-1
cassandraDatacenter:
  name: dc1
```

1. Wait for backup operation to complete
1. Restore the backup - `helm install restore-test -f restore-values.yaml`

```yaml
# restore-values.yaml
name: restore-1
backup:
  name: backup-1
cassandraDatacenter:
  name: dc1
  clusterName: test
inPlace: true
shutdown: true
```

1. Monitor the progress with `kubectl get pods`. You should observe all Cassandra pods terminate.
1. Cassandra pods are recreated.
1. After all Cassandra pods become ready, there will be a rolling update that causes pods to be restarted again, one at a time.

**Expected behavior**
The rolling update in step 8 should not happen.

**Screenshots**

**Environment (please complete the following information):**

* Helm charts version info
This behavior is present in 1.0 and in 1.1.0
* Helm charts user-supplied values
* Kubernetes version information:
* Kubernetes cluster kind:

**Additional context**
This issue is due to behavior in cass-operator. I created https://github.com/k8ssandra/cass-operator/issues/9 to track and address this.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-38) by [Unito](https://www.unito.io)
