### ISSUE TITLE
DOC - List all the sites required for access for systems behind VPN/firewall

### ISSUE THREAD

**Issue by ErickRamirezAU** [k8ssandra/k8ssandra#722]
**Is your feature request related to a problem? Please describe.**
During Kubecon EU, Manuel reported on Discord that his machine is unable to launch K8ssandra since sites like grafana.com is unreachable and requires proxy to be configured.

**Describe the solution you'd like**
List all the sites required for access to install/launch K8ssandra for systems behind VPN/firewall

**Describe alternatives you've considered**
N/A

**Additional context**
```
k8ssandra-grafana-757876dbcc-fn54m                    1/2     CrashLoopBackOff   6          9m19s
```
due to:
```
Error: ✗ Failed to send request: Get "https://grafana.com/api/plugins/repo/grafana-polystat-panel": \
  context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```
required:
```
  grafana:
    adminPassword: ...
    env:
      http_proxy: http://proxy/:port
      https_proxy: http://proxy/:port
```
