### ISSUE TITLE
Improve configurability of C* deployment

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra#76]
**Is your feature request related to a problem? Please describe.**
There are aspects of the C* deployment within K8ssandra which cannot be easily configurated.

**Describe the solution you'd like**
Make aspects of the C* deployment easily configurable like:

* Cluster size _(I believe this is already available)_

```
Users should be able to configure the cluster size of a CassandraDatacenter. Here is an example manifest:

apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: k8ssandra-test
spec:
  clusterName: cluster1
  serverType: cassandra
  serverVersion: "3.11.7"
  managementApiAuth:
    insecure: {}
  size: 3
  storageConfig:
    cassandraDataVolumeClaimSpec:
      storageClassName: server-storage
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
```

* Mulitple nodes per worker

```
By default cass-operator uses anti-affinity so that C* pods are not co-located on the same k8s worker node. There are times, particularly during development and testing, where we want to relax those constraints. {{CassandraDatacenter}} has the AllowMultipleNodesPerWorker property for this. We want to expose this setting.
```

* Version, document supported versions
* CPU/Memory resource allocations

```
Here is an example CassandraDatacenter that configures CPU and memory:

apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: example
spec:
  clusterName: example
  serverType: cassandra
  serverVersion: 3.11.7
  managementApiAuth:
    insecure: {}
  size: 3
  allowMultipleNodesPerWorker: true
  resources:
    requests:
      cpu: 1
      memory: 1Gi
    limits:
      cpu: 1
      memory: 1Gi
  storageConfig:
    cassandraDataVolumeClaimSpec:
      storageClassName: standard
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi  

Note that the operator requires resources to be specified when allowMultipleNodesPerWorker is true.
```

**Additional context**
Legacy reference: [Jira](https://k8ssandra.atlassian.net/browse/K8C-52)

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-133) by [Unito](https://www.unito.io)
