### ISSUE TITLE
Error: CassandraDatacenter.cassandra.datastax.com "dc1" is invalid: type: Required value

### ISSUE THREAD

**Issue by ashishFarEye** [k8ssandra/k8ssandra#831]
## Bug Report

**Describe the bug**
I'm not able to install K8ssandra on a cluster with an existing :1.4.1 cass-operator installation. 

**To Reproduce**

1. Install cass-operator 1.4.1 with namespace spoke
1. Install k8ssandra in another namespace

**Expected behavior**
successful installation of k8sssndra

**Screenshots**
failed to create resource: CassandraDatacenter.cassandra.datastax.com "k8s-dc2" is invalid: type: Required value

**Environment (please complete the following information):**

* Helm charts user-supplied values

$ helm get values RELEASE_NAME 

```
USER-SUPPLIED VALUES:
cassandra:
  cassandraLibDirVolume:
    size: 200Gi
    storageClass: gp2
  datacenters:
  - name: dc1
    racks:
    - affinityLabels:
        topology.kubernetes.io/zone: us-west-2a
      name: us-west-2a
    - affinityLabels:
        topology.kubernetes.io/zone: us-west-2b
      name: us-west-2b
    - affinityLabels:
        topology.kubernetes.io/zone: us-west-2c
      name: us-west-2c
    size: 3
  heap:
    newGenSize: 8G
    size: 8G
  resources:
    limits:
      cpu: 2500m
      memory: 8Gi
    requests:
      cpu: 1500m
      memory: 8Gi
  version: 3.11.10
kube-prometheus-stack:
  enabled: false
medusa:
  bucketName: prod-k8ssandra-s3-bucket
  enabled: false
  storage: s3
  storage_properties:
    region: us-west-2
  storageSecret: prod-k8ssandra-medusa-key
monitoring:
  grafana:
    provision_dashboards: false
  prometheus:
    provision_service_monitors: false
stargate:
  cpuLimMillicores: 3000
  cpuReqMillicores: 3000
  enabled: false
  heapMB: 1024
  replicas: 3

```

* Kubernetes version information:

kubectl version
Client:- 1.16
Server:- 1.19
* Kubernetes cluster kind:
EKS

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-484) by [Unito](https://www.unito.io)
