### ISSUE TITLE
Be able to configure a nodeSelector for cassandra pods

### ISSUE THREAD

**Issue by sisso** [k8ssandra/k8ssandra#926]
**Is your feature request related to a problem? Please describe.**
Currently is not possible to define a nodeSelector to select what type of nodes a cassandra pod should run. If you have big nodes in your cluster for specific use cases, like video card processing, k8ssandra will just use it.

**Describe the solution you'd like**
Add a nodeSelector property that should be forward to the STS spec that creates cassandra nodes.

**Describe alternatives you've considered**
Only deploy k8ssandra into a cluster with the node type you want.

┆Issue is synchronized with this [Jira Bug](https://k8ssandra.atlassian.net/browse/K8SSAND-642) by [Unito](https://www.unito.io)

**Comment by sisso** [comment]
In discord was point me that the same could be achieve using tolerations, that is already supported.

Considering it, I am dropping my feature request.

**Comment by jsanda** [comment]
You can already configure node affinity by using racks. This might need to be documented. Here is an example overrides file that declares racks:

```yaml
cassandra:
  heap:
    size: 512M
    newGenSize: 256M
  datacenters:
    - name: dc1
      size: 3
      racks:
        - name: r1
          affinityLabels:
            topology.kubernetes.io/zone: zone1
        - name: r2
          affinityLabels:
            topology.kubernetes.io/zone: zone2
        - name: r3
          affinityLabels:
            topology.kubernetes.io/zone: zone3
```

Let me know if this covers your use cases and/or if you have questions.
