### ISSUE TITLE
K8SSAND-700 ⁃ Reaper image should use non-root user

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra#963]
**Is your feature request related to a problem? Please describe.**
For improved security the Reaper image should be configured to use a non-root user. See #292 for background.

**Describe the solution you'd like**
Update the Reaper image as necessary to use a non-root user. Note that we need a ticket in https://github.com/thelastpickle/cassandra-reaper since that is where the work needs to be done.

┆Issue is synchronized with this [Jira Bug](https://k8ssandra.atlassian.net/browse/K8SSAND-700) by [Unito](https://www.unito.io)
┆Reviewer: 5e66c4695df5fb0cfee2e364
┆Epic: Pod Security Enhancements
┆Issue Number: K8SSAND-700
┆Priority: Medium

**Comment by jeffbanks** [comment]
Part of overall security phase 1 epic, K8ssandra changes for default securityContext settings [PR#1126] (https://github.com/k8ssandra/k8ssandra/pull/1126) as applied for `reaper-operator`.

* Updated mount path used for security context controls as: `/etc/cassandra-reaper` as  described in `reaper-operator` [PR#84](https://github.com/k8ssandra/reaper-operator/pull/84) to build on foundations of `reaper-operator` [PR#68](https://github.com/k8ssandra/reaper-operator/pull/68)
* Support for K8ssandra w/ image changes in `reaper` [PR#1113](https://github.com/thelastpickle/cassandra-reaper/pull/1113) and [PR#1139](https://github.com/thelastpickle/cassandra-reaper/pull/1139)
* Reaper-operator applied security defaults include the following:

```yaml
# -- PodSecurityContext for the reaper-operator pod.
podSecurityContext: {}

# -- SecurityContext for the reaper-operator container.
securityContext:
  runAsNonRoot: true
  runAsUser: 65534
  runAsGroup: 65534
  readOnlyRootFilesystem: true
```
